### ISSUE TITLE
Custom tasks

### ISSUE THREAD

**Issue by fleed** [MicrosoftDocs/vsts-docs#1084]
Is it possible to use custom tasks (e.g.: cake, https://github.com/cake-build/cake-vso)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87686bea-7c46-cd47-d1a9-128e16b63a23
* Version Independent ID: ace78317-e562-e35d-781d-23cd7d2dfff2
* Content: [CI Build in code using YAML](https://docs.microsoft.com/en-us/vsts/pipelines/build/yaml?view=vsts)
* Content Source: [docs/pipelines/build/yaml.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/yaml.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by chrisrpatterson** [comment]
Yes just install them into the account and reference them as you would any other task.

**Comment by atrauzzi** [comment]
Yeah, but how?

**Comment by atrauzzi** [comment]
How do I get a reference of all the tasks proper names and parameters?

**Comment by fleed** [comment]
Example of using the cake task:

```yaml
- task: Cake@0
    displayName: Run cake script (Build task)
    inputs:
      script:build.cake
      target: Build
```
