### ISSUE TITLE
variables in yaml

### ISSUE THREAD

**Issue by StevenTCramer** [MicrosoftDocs/vsts-docs#1664]
copying from https://docs.microsoft.com/en-us/vsts/pipelines/targets/nuget?view=vsts&tabs=yaml#tabpanel_-jWHD7xAY7-1_yaml

```
variables:
- Major: '1'
- Minor: '0'
- Patch: '0'

steps:
- task: NuGetCommand@2
  inputs:
    command: pack
    versioningScheme: byPrereleaseNumber
    majorVersion: '$(Major)'
    minorVersion: '$(Minor)'
    patchVersion: '$(Patch)'
```
into my vsts yaml I get the following:
.vsts-ci.yml (Line: 5, Col: 3): Unexpected value 'Major'
.vsts-ci.yml (Line: 6, Col: 3): Unexpected value 'Minor'
.vsts-ci.yml (Line: 7, Col: 3): Unexpected value 'Patch'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2512189-84f9-f997-0255-13b276c233b4
* Version Independent ID: c7ccb0ba-4221-bdac-85e1-111eaf51943b
* Content: [Publishing to NuGet feeds](https://docs.microsoft.com/en-us/vsts/pipelines/targets/nuget?view=vsts&tabs=yaml)
* Content Source: [docs/pipelines/targets/nuget.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/targets/nuget.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **amullans**

**Comment by elbatk** [comment]
hey @alexmullans , I don't know too much about YAML syntax, any idea why this code sample isn't working or what needs to be changed?

**Comment by alexmullans** [comment]
I'm still new as well. Perhaps @vijayma or @DavidStaheli can help? If I had to guess, remove the single quotes (```) e.g. `majorVersion: $(Major)`.

**Comment by vtbassmatt** [comment]
The problem is in the variables syntax. We expect a map, not a sequence there. (The single quotes in the inputs are fine.)

```yaml
variables:
  Major: '1'
  Minor: '0'
  Patch: '0'
```
