### ISSUE TITLE
Unexpected value 'container'

### ISSUE THREAD

**Issue by seesharprun** [MicrosoftDocs/vsts-docs#1670]
Whenever I try to use a container image in a pool, I get a ``Unexpected value 'container'`` error message.

Here's the YAML file that I am attempting to use:

```
resources:
  containers:
  - container: pandocContainer
    image: seesharprun/content-generation-pandoc:0.1.0
pool:
  name: 'Hosted Ubuntu 1604'
  container: pandocContainer
steps:
  - script: pandoc -v
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3339a2e0-be29-1363-f588-b231d4472c02
* Version Independent ID: 72dd11a3-704d-d0fd-6dfa-cf49f3352de3
* Content: [Container Jobs in Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=vsts&tabs=yaml)
* Content Source: [docs/pipelines/process/container-phases.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/container-phases.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **macoope**

**Comment by seesharprun** [comment]
Here's the build result:

![image](https://user-images.githubusercontent.com/5067401/45314182-0fd3d080-b4ff-11e8-9381-fea0aa44f9d7.png)

It's a public repository at <https://dev.azure.com/seesharprun/Demo>.

**Comment by vtbassmatt** [comment]
I'll take this one

**Comment by vtbassmatt** [comment]
Try changing to:

```yaml
resources:
  containers:
  - container: pandocContainer
    image: seesharprun/content-generation-pandoc:0.1.0
pool:
  vmImage: 'Ubuntu 16.04'     # changed
  container: pandocContainer  # changed
steps:
  - script: pandoc -v
```

I *think* what's happening is we see a `name` we don't recognize, which implies a private pool, and then we don't allow `container` because we don't have a first-class way to pass a container name to a private pool.

**Comment by wesselkranenborg** [comment]
I _think_ this is not correct. We are also facing this problem with this configuration.

```
resources:
  containers:
  - container: build
    image: microsoft/dotnet:2.1-sdk-alpine
pool:
  container: build
  vmImage: 'Ubuntu 16.04'
```
