### ISSUE TITLE
Automatically retain build if triggering build was retained

### ISSUE THREAD

**Issue by cosminstirbu** [MicrosoftDocs/vsts-docs#1738]
Hello,

Is there a policy that can retain a build when the triggering build was retained?

For instance on our Android project we have a build that creates the .apk for a test environment, and when this one succeeds it triggers a new build that creates the same .apk for the release environment.

We'd like when we create a Release for the test build (which retains the build) - to have our release build retained as well.

Is that possible?

Thank you,
Cosmin

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43a285f9-738d-9f76-4de0-a4c4ecf6f5f5
* Version Independent ID: 9581a043-4873-bf0a-138f-85f6a61ae950
* Content: [Build and release retention policies](https://docs.microsoft.com/en-us/azure/devops/pipelines/policies/retention?view=vsts)
* Content Source: [docs/pipelines/policies/retention.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/policies/retention.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vijayma** [comment]
Not at present. Your best bet would be to put the test and release builds as two jobs in the same build.

**Comment by cosminstirbu** [comment]
I understand. Thanks.

**Comment by cosminstirbu** [comment]
Is there a way I can export a job from one build and import it in a different build?

**Comment by vijayma** [comment]
No, you can export the whole build, import it, and then remove the rest of the jobs. Or, you can you task groups to share the same job across multiple pipelines. (PS: We currently have a bug where we show the YAML editor when you import a pipeline. We will rollout a fix for that next week).

**Comment by cosminstirbu** [comment]
We might consider migrating to YAML.

Does the YAML approach assume keeping the YAML files in the same repo with the source code?

We have already scripted all of our build steps using Cake, and it might worth "scripting" the actual VSTS build infrastructure as well.

**Comment by vijayma** [comment]
@vtbassmatt, can you comment on the use of multiple repos - one for YAML and one for source code. I believe this is possible, but are there any limitations in terms of triggers, etc?

**Comment by vtbassmatt** [comment]
You will need a "stub" pipeline in your source code repo. This can simply invoke your other repo's pipeline using [templates](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=vsts#in-other-repos). The main limitation is that any resources -- other repositories, service connections, etc. -- that you want to use must be defined in the source code repo.

```yaml
# azure-pipelines.yml in your source repo
resources:
  repositories:
  - repository: templates  # this name will be used after the '@' in the step
    name: contoso/example-templates
    type: github

steps:
# This file will be pulled from the contoso/example-templates repository
- template: steps.yml@templates
```

```yaml
# steps.yml in your other repo, github.com/contoso/example-templates
steps:
- task: msbuild@
- task: vstest@2
```
