### ISSUE TITLE
How to express ACR image?

### ISSUE THREAD

**Issue by AArnott** [MicrosoftDocs/vsts-docs#1746]
The doc shows an ACR image being downloaded with:

```yaml
resources:
  - container: my_private_container
    image: private:ubuntu14
    endpoint: my_acr_connection
```

But that [doesn't work](https://andrewarnott.visualstudio.com/OSS/_build/results?buildId=123&view=logs). I've also tried.

```yaml
resources:
  - container: my_private_container
    image: ubuntu14
    endpoint: my_acr_connection
```

That too, [didn't work](https://andrewarnott.visualstudio.com/OSS/_build/results?buildId=122&view=logs).

```yaml
resources:
  - container: my_private_container
    image: myregistryname.azurecr.io/ubuntu14
    endpoint: my_acr_connection
```

That [didn't work either](https://andrewarnott.visualstudio.com/OSS/_build/results?buildId=121&_a=summary&view=logs).

Can we please get updated docs with the proper way to do this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3339a2e0-be29-1363-f588-b231d4472c02
* Version Independent ID: 72dd11a3-704d-d0fd-6dfa-cf49f3352de3
* Content: [Container Jobs in Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=vsts&tabs=yaml#other-settings)
* Content Source: [docs/pipelines/process/container-phases.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/container-phases.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **macoope**
