### ISSUE TITLE
Run `xcodebuild` as a `script` step

### ISSUE THREAD

**Issue by nick-thompson** [MicrosoftDocs/vsts-docs#1789]
Is it possible to run an `xcodebuild` from the command line using the `script` step? My project carries a small shell script which calls `xcodebuild` and moves some files around to prepare the release archive, ideally I could just have something like this in my pipelines config:

```
jobs:
- job: OSX
  pool:
    vmImage: 'xcode9-macos10.13'
  steps:
  - script: /bin/bash ./scripts/run.sh build
```

Is that possible currently? Or planned for the future?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36460c87-c713-0930-461b-92da65e415e6
* Version Independent ID: 047d39f1-481b-c135-36e9-6cfc1cc92e99
* Content: [Xcode build and release task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/xcode?view=vsts)
* Content Source: [docs/pipelines/tasks/build/xcode.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/xcode.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **dastahel**
