### ISSUE TITLE
Create Your First Pipeline - dotnet-core succeeds with test failures

### ISSUE THREAD

**Issue by snerks** [MicrosoftDocs/vsts-docs#1823]
Hi,

Following steps described here:
https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started-yaml?view=vsts

An Azure Build Pipeline was created, with a fork of this GitHub repo:
https://github.com/MicrosoftDocs/pipelines-dotnet-core

**Scenario**
Modify a unit test, to ensure that it will fail.

**Expected Outcome**
Build Pipeline to fail

**Actual Outcome**
Build Pipeline succeeds. (Unit test failure is reported)

**Other Info**
Using the same approach with the `pipelines-javascript` project, the Build Pipeline fails, if a Unit Test fails.

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by karanjitsingh** [comment]
I've created a PR for the same.
cc @PBoraMSFT

**Comment by PBoraMSFT** [comment]
@karanjitsingh - with the failOnStderr, would the publish test results task kick in at all?

**Comment by karanjitsingh** [comment]
@PBoraMSFT you're right, I guess we have to use both `failOnStderr` as well as `continueOnError`

**Comment by karanjitsingh** [comment]
@snerks, since all tasks will run even if there is script failure, if this breaks your expected behavior. You can use conditional publish test results

```yml
# Build ASP.NET Core project using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core?view=vsts

pool:
  vmImage: 'Ubuntu 16.04'
  
variables:
  buildConfiguration: 'Release'

steps:
- script: |
    dotnet build --configuration $(buildConfiguration)
    dotnet test dotnetcore-tests --configuration $(buildConfiguration) --logger trx
    dotnet publish --configuration $(buildConfiguration) --output $BUILD_ARTIFACTSTAGINGDIRECTORY
  failOnStderr: true

- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
  condition: succeededOrFailed()

- task: PublishBuildArtifacts@1
```

This will publish your tests even when the script has failed.
