### ISSUE TITLE
Multiple Python version and images without templates

### ISSUE THREAD

**Issue by datapythonista** [MicrosoftDocs/vsts-docs#1855]
I want to set up my CI in Azure-pipelines to run my tests in:

- Python 3.6 / Linux
- Python 3.7 / Linux
- Python 3.6 / Windows
- Python 3.7 / Windows

I see that I can test with different Python versions easily by using matrix, but I'm guessing if there is a simple way to do the same with the images. I think it might be possible to use templates for it, but I'd like to keep everything simple and in a single file if that's an option.

This is what I've got so far for testing py3.6/py3.7 in Linux:

```
- job: 'Test'
  pool:
    vmImage: 'Ubuntu 16.04'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: python -m unittest discover tests
    displayName: 'Run unittest tests'
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=vsts)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **macoope**
