### ISSUE TITLE
Using Insertion for dependsOn

### ISSUE THREAD

**Issue by lifesoccult** [MicrosoftDocs/vsts-docs#1857]
I would like to create a template that has dynamic `dependsOn` values. I've tried this out according to your Insertion directions, but I get an error of: `Expected a scalar value`. Is this possible? Can this be a feature request? Here's my config (non-relevant entries redacted):

## .vsts-ci.yml File
```
resources:
  repositories:
  - repository: pipeline-common
    type: git
    name: pipeline-common

variables:
  INT_TEST_DIR: $(Build.Repository.LocalPath)/integration-tests
  PIPELINE_COMMON_DIR: $(Build.Repository.LocalPath)/pipeline-common

phases:
  - template: integration-tests.yml@pipeline-common
  - template: ios-modules.dependson.yml@pipeline-common
    parameters:
      myDependsOn:
        - Unit_Test
        - User_Acceptance_Test
        - Integration_Test
```

## Template File
```
parameters:
  myDependsOn: []

phases:
  - phase: Unit_Test
    queue: 'Redacted'
    steps:
      - script: pod update
        displayName: pod update
      - script: fastlane unit_test
        displayName: Unit Test
      - task: PublishTestResults@2
        displayName: Publish unit test report
        condition: succeededOrFailed()
        inputs:
          testRunner: 'JUnit'
          testResultsFiles: 'fastlane/test_output/report.junit'
      - task: PublishBuildArtifacts@1
        displayName: Archive unit test report
        condition: succeededOrFailed()
        inputs:
          pathtoPublish: 'fastlane/test_output/report.junit'
          artifactName: 'unit_test_report.junit'

  - phase: Publish_CocoaPod
    queue: 'Redacted'
    dependsOn:
      - {{ parameters.myDependsOn }}
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    steps:
      - bash: |
          git clone <redacted> $PIPELINE_COMMON_DIR
          $PIPELINE_COMMON_DIR/deploy_pod.sh
        displayName: Deploy Package
```

Thanks,

Jonathan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=vsts#template-expressions)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
I'm assuming it's a copy-paste error that you left out the leading `$`:

```yaml
    dependsOn:
      - ${{ parameters.myDependsOn }}
```

I wasn't able to repro the issue you're seeing. It's possibly related to using the `phases` syntax, which we've deprecated and replaced with `jobs`. Here are the files which were successful for me:

```yaml
## azure-pipelines.yml
jobs:
- job: A
  steps:
  - script: echo A

- template: insert.yml
  parameters:          # it also worked when removed
    myDependsOn: [A]   # these two lines

## insert.yml
parameters:
  myDependsOn: []

jobs:
- job: First
  steps:
  - script: echo First

- job: Second
  steps:
  - script: echo Second
  dependsOn:
  - ${{ parameters.myDependsOn }}
```
