### ISSUE TITLE
Run task if file/directory exists

### ISSUE THREAD

**Issue by Thilas** [MicrosoftDocs/vsts-docs#1877]
It would be really nice if we could create conditions based on the existence of a file/directory (even better a glob pattern).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f151218-9a11-0078-e038-f96198a76143
* Version Independent ID: 09c4d032-62f3-d97c-79d7-6fbfd89910e9
* Content: [Conditional expressions - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=vsts)
* Content Source: [docs/pipelines/process/conditions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/conditions.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vtbassmatt** [comment]
Interesting idea for a feature. You can simulate this using a script task that sets a variable.

```yaml
- bash: |
    if [ -f your-file-here.txt ]; then
      echo "##vso[task.setVariable variable=FILEEXISTS]true"
    fi
- task: Foo@1
  condition: eq(variables.FILEEXISTS, 'true')
```

(From memory, not tested, etc.)

**Comment by Thilas** [comment]
Thanks for the feedback! That's pretty much the kind of workaround I'm using for this.

**Comment by damianszczepanik** [comment]
When expecting to implement something like assertion I propose following:

```
  - task: PowerShell@2
    displayName: "Assert that directory ${{ parameters.filePath }} exists"
    inputs:
      targetType: "inline"
      script: "Get-Item -Path ${{ parameters.filePath }}"
```
This fails the pipeline when passed path does not exist. It also print out the task name so understanding the failure reason is easy.
