### ISSUE TITLE
Helm delete task usage not clear / inconsistent with YAML

### ISSUE THREAD

**Issue by timwebster9** [MicrosoftDocs/vsts-docs#1879]
You'd think that to do the equivalent of  `helm delete --purge somerelease` all one would have to do is this:

```
- task: HelmDeploy@0
  displayName: 'Delete some release'
  continueOnError: true
  enabled: true
  inputs:
    connectionType: $(kubectlConnectionType)
    azureSubscription: '${{ parameters.serviceConnection }}'
    azureResourceGroup: $(aksResourceGroup)
    kubernetesCluster: $(clusterName)
    command: 'delete'
    releaseName: 'somerelease'
    arguments: '--purge'
```

However what you get instead is this:

```
2018-09-25T19:02:46.1423957Z Error: command 'delete' requires a release name
2018-09-25T19:02:46.1548264Z [command]/usr/local/bin/helm delete --purge
2018-09-25T19:02:46.1653116Z ##[error]Error: command 'delete' requires a release name
```

However this works:

```
- task: HelmDeploy@0
  displayName: 'Delete some release'
  continueOnError: true
  enabled: true
  inputs:
    connectionType: $(kubectlConnectionType)
    azureSubscription: '${{ parameters.serviceConnection }}'
    azureResourceGroup: $(aksResourceGroup)
    kubernetesCluster: $(clusterName)
    command: 'delete'
    arguments: '--purge somerelease'
```

Using these tasks requires a lot of trial and error.  Either the usage needs to be documented better, or the task definitions and arguments need to be consistent in how they are used.

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc7eeb7f-4e6b-8fee-1d7f-582cfb018b02
* Version Independent ID: 00fb3082-1069-9060-012c-0b6d75ef120b
* Content: [Package and deploy Helm Charts](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/helm-deploy?view=vsts)
* Content Source: [docs/pipelines/tasks/deploy/helm-deploy.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/helm-deploy.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **dastahel**

**Comment by RoopeshNair** [comment]
@timwebster9 - thank you for your feedback. we will get this looked at. Adding @azooinmyluggage

**Comment by timwebster9** [comment]
Thanks @RoopeshNair 

One further thing I might add.  For all of these tasks that invoke some sort of command-line tool, it would be very useful to have a 'free' argument on the task where one could pass any command they want to the underlying tool.  This way the task definition logic wouldn't have to necessarily keep up with the tool itself.

For example, with a new task argument called `commandAndArgs` (sorry couldn't think of a better name):

```
- task: HelmDeploy@0
  displayName: 'Delete some release'
  continueOnError: true
  enabled: true
  inputs:
    connectionType: $(kubectlConnectionType)
    azureSubscription: '${{ parameters.serviceConnection }}'
    azureResourceGroup: $(aksResourceGroup)
    kubernetesCluster: $(clusterName)
    commandAndArgs: 'delete --purge $(someRelease)'
```

I realise that these task commands probably map to to drop-down list in the Visual Designer, but for YAML and automation, this needs to be as flexible as possible.
