### ISSUE TITLE
Error trying to build a container from within a container (DIND).

### ISSUE THREAD

**Issue by atrauzzi** [MicrosoftDocs/vsts-docs#1937]
My build container...builds containers! 😆 

Unfortunately, that means when I go to build, I get this message: _"Got permission denied while trying to connect to the Docker daemon socket"_

I have this in my yaml:

```yaml
resources:
  containers:
  - container: "build-image"
    endpoint: "build-image"
    image: "[REDACTED].azurecr.io/[REDACTED]/build-image:latest"

pool:
  vmImage: 'Ubuntu 16.04'

container: "build-image"

steps:

  # ...other steps

  - task: Docker@1
    displayName: "Build Docker Container"
    inputs:
      imageName: "$(REGISTRY_URI):$(VERSION_SLUG)"

```

I'm able to accomplish this during my Travis-CI tasks, hoping I can here as well so that I can finish porting over our builds to your service! 😄

**Comment by vtbassmatt** [comment]
@dakale I don't know how to build a container from within a container - is there some syntax I can recommend to people?

**Comment by dakale** [comment]
Heres a sample I came up with, that works but is a little different from what you have: 

```yml
resources:
  containers:
  - container: CONTAINER_NAME
    image: IMAGE

phases:
- phase: Build_container_in_container'
  queue:
    name: 'Hosted Ubuntu 1604'
    container: CONTAINER_NAME

  steps:
  - script: |
      cd SAMPLE_DIR && npm install && npm run build
    displayName: Build sample

  - script: |
      echo "Copying built dist into container (pseudo-multistage)"
     # Note: This Dockerfile copies the dist folder built above into the container
     # ie it uses the build containers context to build a container on the host 
      sudo docker build SAMPLE_DIR
    displayName: Build container artifact
```

The reason I call it pseudo multistage is being this has the same basic outcome of [Docker multistage builds](https://docs.docker.com/develop/develop-images/multistage-build/) without actually using the feature. 

The benefit of the way you are doing it is, of course, you can execute tasks instead of just `RUN`ning commands. 

I think the workaround is going to be related to the `sudo docker build` 

When the build runs in a container it creates a user inside the container to run as, which wont match the user on the host (a user called vsts, which is in the docker group, allowing you to run docker without sudo)

__For now I recommend:__ just using a script to execute docker build directly, youll just need to template in your registry, image, version etc into the script but I think it will be easy to convert 

If you dont want to change the Docker task step, you might be able to make something like this work: 
https://vitorbaptista.com/how-to-access-hosts-docker-socket-without-root

where basically you add the user inside the container to the group with the GID that owns the docker socket on the host

Let me know if you have any questions
