### ISSUE TITLE
name isn't actually the pipeline name

### ISSUE THREAD

**Issue by lwajswaj** [MicrosoftDocs/vsts-docs#1951]
According to the documentation the pipeline is defined as

```yml
name: string  # name of the pipeline
resources:
  containers: [ container ]
  repositories: [ repository ]
variables: { string: string } | variable
trigger: trigger
jobs: [ job | templateReference ]
```

However when azure-pipelines.yml is defined as:

```yml
name: Pipeline Name
resources:
  repositories:
  - repository: self
    clean: true
    type: git
```

The value "Name" ends up being the "Build #" rather than "Pipeline Name"
