### ISSUE TITLE
Task for choosing Visual Studio command line tools version.

### ISSUE THREAD

**Issue by vadimcn** [MicrosoftDocs/vsts-docs#1977]
These should be a task, similar to UsePythonVersion, for choosing Visual Studio command line tools, in case one wants to use Microsoft compiler but not msbuild.   For example, try configuring cmake project for "Unix Makefiles" while using Microsoft cl.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29f86c97-f534-50ad-bfb1-a2cf78c7af94
* Version Independent ID: acea40e3-512b-4d9a-9389-71b8b24327be
* Content: [Visual Studio Build build and release task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/visual-studio-build?view=vsts)
* Content Source: [docs/pipelines/tasks/build/visual-studio-build.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/visual-studio-build.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vijayma** [comment]
Thanks for the suggestion. We have added this to our backlog.

**Comment by andlabs** [comment]
Possible workaround for now? I've had success invoking the relevant batch files directly based on the info on [the MSDN page about the Visual Studio Command Prompt](https://docs.microsoft.com/en-us/cpp/build/building-on-the-command-line?view=vs-2019#developer_command_file_locations) and the agent READMEs ([VS2015](https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/win/Vs2015-Server2012R2-Readme.md), [VS2017](https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/win/Vs2017-Server2016-Readme.md)). For example:

```yaml
  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
      meson setup build-shared --buildtype=release --backend=vs2017
    displayName: 'Prepare shared build'
```

(meson depends on the environment being set up properly regardless of what backend it uses, unlike cmake.)
