### ISSUE TITLE
System.PullRequest.* variables don't seem to be populated

### ISSUE THREAD

**Issue by rchakra3** [MicrosoftDocs/vsts-docs#1999]
I've got a step that runs only if the build was a result of a PR:
`condition: eq(variables['Build.Reason'], 'PullRequest')`

However, none of the `System.PullRequest` variables seem to get populated (I get a bad substitution error). 

Here's an example of a job that fails with a bad substitution error:
```
- job: Tests
  pool:
    vmImage: 'Ubuntu-16.04'
  container: golang
 ....
  steps:
  - checkout: self
    persistCredentials: true
  - bash: |
      git merge-base --is-ancestor "${System.PullRequest.TargetBranch}" "${System.PullRequest.SourceBranch}"
    displayName: "Check if branch is rebased against target"
    condition: eq(variables['Build.Reason'], 'PullRequest')
```

Am I doing something wrong here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Predefined build variables - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=vsts)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**
