### ISSUE TITLE
Question about multiple projects

### ISSUE THREAD

**Issue by StefH** [MicrosoftDocs/vsts-docs#2047]
The code example is for building all projects is like:
``` yml
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
```

But how to build multiple projects defined by csproj filenames?
Like building `./src/ClassLibrary1/ClassLibrary1.csproj` and `./src/ClassLibrary2/ClassLibrary2.csproj`.

This command fails:
``` yml
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: './src/ClassLibrary1/ClassLibrary1.csproj;./src/ClassLibrary2/ClassLibrary2.csproj'
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96561b11-820d-b386-4208-e88e9552f5fc
* Version Independent ID: 42918fea-f9ad-260c-ec38-70254a47de5d
* Content: [.NET Core build and release task - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core?view=vsts)
* Content Source: [docs/pipelines/tasks/build/dotnet-core.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/dotnet-core.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **amullans**
