### ISSUE TITLE
The "Push NuGet packages" example does not work when pushing to MyGet?

### ISSUE THREAD

**Issue by StefH** [MicrosoftDocs/vsts-docs#2051]
I'm using this task:

``` yml
- task: DotNetCoreCLI@2
  displayName: 'MyGet !'
  inputs:
    configuration: '$(BuildConfiguration)'
    command: 'push'
    projects: '**/*.csproj'
    packagesToPush: '**/*.nupkg'
    nuGetFeedType: 'external' 
    publishVstsFeed: 'https://www.myget.org/F/stef-test/api/v2/package'
    publishFeedCredentials: '$(MyGetKey)'
    versioningScheme: 'byPrereleaseNumber'
```

However the build pipeline shows this error:
```
Job Job1: Step input publishFeedCredentials references service connection {***} which could not be found. The service connection does not exist or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz
```

Where `{***}` is the API Key from MyGet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96561b11-820d-b386-4208-e88e9552f5fc
* Version Independent ID: 42918fea-f9ad-260c-ec38-70254a47de5d
* Content: [.NET Core build and release task - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core?view=vsts)
* Content Source: [docs/pipelines/tasks/build/dotnet-core.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/dotnet-core.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **amullans**
