### ISSUE TITLE
Setting Common Environment Variables

### ISSUE THREAD

**Issue by RehanSaeed** [MicrosoftDocs/vsts-docs#2084]
Is there a way to specify environment variables for all build steps and jobs? I want to repeat the same environment variables everywhere. As an aside, do I need to specify the environment variables below for quicker build times or do the images include them out of the box?

```
jobs:

- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: ./foo.sh
    env:
      COREHOST_TRACE: 0
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
  - script: ./bar.sh
    env:
      COREHOST_TRACE: 0
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1

- job: macOS
  pool:
    vmImage: 'xcode9-macos10.13'
  steps:
  - script: ./foo.sh
    env:
      COREHOST_TRACE: 0
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
  - script: ./bar.sh
    env:
      COREHOST_TRACE: 0
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
```
