### ISSUE TITLE
Where does the file go?

### ISSUE THREAD

**Issue by maudormiston** [MicrosoftDocs/vsts-docs#212]
It'd be nice if this actually documented where the file ends up, and what environment variable the path of said file is bound to!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a5f8376-3654-0ed4-d9f8-d15f28350783
* Version Independent ID: f393daba-6515-6c26-71ac-b557e8c8dad1
* [Content](https://docs.microsoft.com/en-us/vsts/build-release/tasks/utility/download-secure-file)
* [Content Source](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/tasks/utility/download-secure-file.md)
* Service: unspecified

**Comment by bryoncline** [comment]
I found it in this location; hope this helps:
../../../../../opt/vsts/work/_temp/

**Comment by Glitch0011** [comment]
Hi @maudormiston and @bryoncline, according to the JSON settings [here](https://github.com/Microsoft/vsts-tasks/blob/2c02c93bb7899f53d2b07a8487a13ccb4f776010/Tasks/DownloadSecureFile/task.json), the path is set to an environment variable defined as "secureFilePath".

This is supposed to be set to an environment variable but is being mangled into a long hex-name for some reason.

```
2018-03-01T12:12:30.2875816Z Name                           Value                                                                                   
2018-03-01T12:12:30.2876814Z ----                           -----                                                                                   
2018-03-01T12:12:30.2884607Z 8504415A9DC43BDA7F65501AA43... D:\a\_temp\Example.secret
```

It's odd, isn't it?

**Comment by maudormiston** [comment]
I ended up just using a marketplace add-on with the same name which quite sensibly lets you set where you want the file to go.

Weirdly secureFilePath did not work for me, it prefixed it with a long hex string. I found this out by using an addon to print all variables in scope.

**Comment by Glitch0011** [comment]
Much neater than my solution `(((gci env:*) | where { $_.Value -like "*Example.secret*" }).Value)`

**Comment by madhurig** [comment]
To avoid having the hash, you can set the reference name for the task in the UI:
![image](https://user-images.githubusercontent.com/3269636/37291769-bf520940-25e5-11e8-9204-cbf50cbb3dd7.png)

Then the variable will contain the reference name instead of a generated hash.

Thanks,
Madhuri

**Comment by steve-hawkins** [comment]
Thanks Madhuri,

I'm having trouble finding an example of setting a reference to a task output in yaml

I've tried setting the name for the task, but that appears to stop any environment variable from being created with the secureFilePath as the value:-

```
  - task: DownloadSecureFile@1
    displayName: Download Secure File
    name: secureFile
    inputs:
      secureFile: secure.file
```

One observation I have made is that when you use the DownloadSecureFile task from yaml and don't specify a name the environment variable is called 'DOWNLOADSECUREFILE_SECUREFILEPATH' consistently.

```
  - task: DownloadSecureFile@1
    displayName: Download Secure File
    inputs:
      secureFile: secure.file
```

Interestingly if you have more than one DownloadSecureFile task then the environment variable names change to 'DOWNLOADSECUREFILE1_SECUREFILEPATH', 'DOWNLOADSECUREFILE2_SECUREFILEPATH', etc

```
  - task: DownloadSecureFile@1
    displayName: Download Secure File
    inputs:
      secureFile: secure.file

  - task: DownloadSecureFile@1
    displayName: Download Another Secure File
    inputs:
      secureFile: secure.file
```

I have raised a [PR](https://github.com/Microsoft/vsts-tasks/pull/6675) on this to allow a custom directory to be optionally specified as I don't feel the environment variable is a reliable method
