### ISSUE TITLE
Spacing for Conditional Insertion is wrong in docs

### ISSUE THREAD

**Issue by markjm** [MicrosoftDocs/vsts-docs#2149]
Docs have
steps:
```
steps:

# msbuild
- ${{ if eq(parameters.toolset, 'msbuild') }}:
  - task: msbuild@1
  - task: vstest

```
Note the '-' for the conditional is aligned with steps. This whole conditional block should be indented out one more space

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6724abea-bbdc-bf66-ed5e-3214fa6c3e66
* Version Independent ID: 4f8dab21-3f0e-da32-cc0e-1d85c13c0065
* Content: [Job and step templates - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=vsts#conditional-insertion)
* Content Source: [docs/pipelines/process/templates.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/templates.md)
* Product: **devops**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **alewis**
