### ISSUE TITLE
Publishing NPM package to Azure DevOps Services package management feed

### ISSUE THREAD

**Issue by mogusbi-sage** [MicrosoftDocs/vsts-docs#2156]
I've tried to follow the instructions to publish an npm package to package management feed but I cannot seem to get this work at all using the snippet below.

```
      - task: Npm@1
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
        inputs:
          command: publish
        displayName: 'Publish package'
```

The `.npmrc` file has been checked in (although looking at the output it's overwritten by the `NPM` task so it should all be pointing to the correct place. However it fails with `Error: Input required: publishEndpoint` but it's not clear what this publish endpoint as I'd assume it would either read the `.npmrc` file or default to the registry in the services packages feed

Adding the registry URL as the `publishEndpoint` also doesn't work.

How can I get it to publish it to publish to my package management feed/registry?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c99686eb-6c78-0336-1ec3-802a53c9868d
* Version Independent ID: 6eaf1acb-24d4-5bb7-3935-17abe7e59dd9
* Content: [Building JavaScript and Node.js apps with Azure Pipelines or TFS - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/javascript?view=vsts&tabs=yaml#package-and-deliver-your-code)
* Content Source: [docs/pipelines/languages/javascript.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/languages/javascript.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**
