### ISSUE TITLE
Add a snippet that demonstrates publishing a package to an Azure Artifacts Feed

### ISSUE THREAD

**Issue by gldraphael** [MicrosoftDocs/vsts-docs#2178]
I had to use something like this:

```yaml
- task: Npm@1
  inputs:
    command: publish
    publishRegistry: useFeed
    publishFeed: feedName
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4cb48a1-d0bf-40b7-4645-910d4006fee9
* Version Independent ID: 9bddd101-2bc2-f65c-6a12-e395b76a2b98
* Content: [Publishing npm packages - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/targets/npm?view=vsts&tabs=yaml)
* Content Source: [docs/pipelines/targets/npm.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/targets/npm.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **amullans**
