### ISSUE TITLE
Variables not recognized from variable groups

### ISSUE THREAD

**Issue by jdogg89** [MicrosoftDocs/vsts-docs#2303]
when I run my script to login to quay and push my image, my environment variables are not recognized:
- script: |
    docker login -u $(quayUser) -p $(quayPswd) quay.io
output:
2018-10-31T15:33:35.8408915Z /home/vsts/work/_temp/XXX.sh: line 1: quayUser: command not found
2018-10-31T15:33:35.8409887Z /home/vsts/work/_temp/XXX.sh: line 1: quayPswd: command not found

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Pipeline variables - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=vsts&tabs=yaml%2Cbatch)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vtbassmatt** [comment]
Can you paste in the entire relevant section of the YAML you tried? There's not enough here to troubleshoot (except that your macros are being passed through without replacement, which then makes Linux try to execute `quayUser`).

**Comment by jdogg89** [comment]
```
# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
#testing build
pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'quay.io/blah/blah:$(build.buildId)'

steps:
- script: docker build -f Dockerfile -t $(imageName) .
  displayName: 'docker build'

- script: |
    docker login -u $(quayUser) -p $(quayPswd) quay.io
    docker push $(imageName)
  displayName: 'Push to Quay.io'
```

**Comment by jdogg89** [comment]
I've tried running it as bash instead of script as well and that didn't change anything

**Comment by jdogg89** [comment]
@vtbassmatt let me know if you need more info

**Comment by vtbassmatt** [comment]
Got it. You have to explicitly map in [variable groups](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=vsts&tabs=schema#variables). Something like this:
```yaml
pool:
  vmImage: 'Ubuntu 16.04'

variables:
- name: imageName
  value: 'quay.io/blah/blah:$(build.buildId)'
- group: myQuayVarGroup  # the name of the group which contains quayUser and quayPswd

steps:
- script: docker build -f Dockerfile -t $(imageName) .
  displayName: 'docker build'

- script: |
    docker login -u $(quayUser) -p $(quayPswd) quay.io
    docker push $(imageName)
  displayName: 'Push to Quay.io'
```
