### ISSUE TITLE
How to add custom extension tasks?

### ISSUE THREAD

**Issue by joseph-cloudthing** [MicrosoftDocs/vsts-docs#2321]
For example the Cordova extension from the marketplace by Microsoft.

Exporting an existing visual template gives:
```
- task:
    id: 61ec6339-4a6a-4a69-875e-5a6f4db157a2
    versionSpec: 1.*
    definitionType: task
  displayName: 'Cordova: Prepare'
  inputs:
    cordovaCommand: prepare $(app_platform)
    cwd: "some-directory"
```
but when using that in yaml I receive:
```
azure-pipelines.yml (Line: 6, Col: 5): Expected a scalar value
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8098f527-ebdf-60d5-3989-5228b7a207c1
* Version Independent ID: ce27c817-9599-00ef-5af2-3ac1dbad8dc6
* Content: [Build and Release Tasks in Azure Pipelines and TFS - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/tasks?view=vsts&tabs=yaml)
* Content Source: [docs/pipelines/process/tasks.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/tasks.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by joseph-cloudthing** [comment]
https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=vsts#optional-install-and-test-your-extension might be another place for this...

**Comment by joseph-cloudthing** [comment]
Figured it out:
```
- task: 61ec6339-4a6a-4a69-875e-5a6f4db157a2@1
  displayName: 'Cordova: Prepare'
  inputs:
    cordovaCommand: prepare $(app_platform)
    cwd: "some-directory"
```
Surely I can replace the uuid with something nicer though...?
