### ISSUE TITLE
How can the display name be dynamically updated to use env variables defined during the build

### ISSUE THREAD

**Issue by CoolDadTx** [MicrosoftDocs/vsts-docs#2327]
I'm using YAML step templates to group common build stuff we need. In one template we calculate the version of our app. What I want to do is display this version in the log output as part of a display name on another step. I cannot find any way to do this. The display name is shown when the build starts and doesn't appear to be configurable unless you pass it as a parameter to the template which doesn't really make sense in my case.

```yaml
steps:
- powershell: |
      # Do version calculation...
      $version = "1.2.3.4"
      Write-Host "##vso[task.setvariable variable=MyVersion]$version"
   displayName: Calculate Version

-powershell: Write-Host "$env:MyVersion"
  displayName: "Version = '$(MyVersion)'
```
I want the second step to show in the logs for the display name Version = 1.2.3.4 but instead it shows $(MyVersion). Is there any way to get this to work? I tried move the second Powershell task to a separate step template and that didn't change anything.
For completeness, I also tried a template expression here.

```yaml
displayName: ${{ variables['MyVariable'] }}
```

**Comment by vtbassmatt** [comment]
That value isn't available until the step executes. By then, `displayName` of the subsequent step has already been chosen and committed. What you're asking for isn't unreasonable, but it's a new feature -- dynamically-updateable display names. A good place to talk over new feature ideas is (as you know, but including for others' benefit) https://github.com/Microsoft/azure-pipelines-yaml.

It's possible to achieve this with a multi-job configuration, using output variables. The reason this works is that the second job depends on the first, so nothing is committed until after it completes.

```yaml
jobs:
- job: Produce
  steps:
  - powershell: |
      # Do version calculation...
      $version = "1.2.3.4"
      Write-Host "##vso[task.setvariable variable=theVersion;isOutput=true]$version"
    displayName: Calculate Version
    name: calcVersionNumber

- job: Consume
  dependsOn: Produce
  variables:
    MyVersion: $[ dependencies.Produce.outputs['calcVersionNumber.theVersion'] ]
  steps:
  - powershell: Write-Host "$env:MyVersion"
    displayName: Version = $(MyVersion)
```
