### ISSUE TITLE
Sample: Build and Publish from a multi-project solution to Azure Artifact Feed

### ISSUE THREAD

**Issue by sameera** [MicrosoftDocs/vsts-docs#2378]
For anyone going through the doc https://docs.microsoft.com/en-us/azure/devops/pipelines/targets/nuget?view=vsts&tabs=yaml
and finding it hard to figure out how to do the above, maybe the following sample would prove helpful:

Premise:
You have your Package configuration setup in the csproj (through Visual Studio, for example) and do not need to separately execute `nuget pack` - The reason you may want to do this is if these packages are part of a larger build and you don't need to increment each package version on every build. This way you can decide to increment locally and let VSTS deploy packages only if the version had been upgraded by you explicitly in the source code.

```
# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- task: NuGetCommand@2
  inputs:
    command: push
    packagesToPush: '$(Build.SourcesDirectory)/**/*.nupkg;!$(Build.SourcesDirectory)/**/*.symbols.nupkg'
    publishVstsFeed: 'your-nuget-feed-name'
    allowPackageConflicts: true
```

Things to note:
- Using `allowPackageConflicts:true` only works on Windows. Therefore, I had to use the default hosted Visual Studio pool (rather than a Linux VM).
- `packagesToPush` has to be set because, the MSBUILD configuration (i.e. the csproj settings), does not push the packages to `Build.ArtifactStagingDirectory` which is the default.
