### ISSUE TITLE
Incorrect syntax for passing user-defined vars/oauth token

### ISSUE THREAD

**Issue by tescales** [MicrosoftDocs/vsts-docs#2420]
```
  - powershell: Write-Host "This is a script that could use $env:SYSTEM_ACCESSTOKEN"
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
```
Does not work. Error "Expected a scalar value"

Tried various combinations of 
```
env: { VAR: value }
```
et cetera but can't find the right incantation. Please update the docs?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Pipeline variables - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=vsts&tabs=yaml%2Cbatch)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by tescales** [comment]
Hi thanks for getting back to me. The relevant portions of YAML are:

```
variables:
  - name: the_token
    value: $(System.AccessToken)

jobs:
  - job: run_all
    pool: Hosted
    steps: 
    - task: PowerShell@2
      displayName: "Get-WorkItems"
      inputs:
        targetType: filePath
        filePath: pipeline\get-workitems.ps1
```

...and in get-workitems.ps1:
```
$workitems = Invoke-RestMethod -Uri $url -Headers @{ Authorization = "Bearer $env:THE_TOKEN" };
```
I did manage to get it to work by explicitly assigning it to the step with

```
    - task: PowerShell@2
      displayName: "Get-WorkItems"
      env:
        THE_TOKEN: $(System.AccessToken)
```

But it seems like the first approach should have worked as well, per the example on the page:

```
variables:
  the_token: $(System.AccessToken)

jobs:
- job: Test
  steps:
  - script: echo Now I can use $(the_token)

```

Unless I'm missing something?

**Comment by vtbassmatt** [comment]
Nope, I was just wrong when I copied and pasted some docs. That *is* generally how variables work, but in the case of secrets, we actually map in the fact that it's a secret, as well. Net result: you must map secrets at the step (task) level. It's a security feature, and incorrectly documented. I'll fix it.

**Comment by vtbassmatt** [comment]
Only bare secrets have to be mapped per-step. Secrets from a variable group correctly map in:

```yaml
variables:
- group: GroupWithAndWithoutSecrets

steps:
- script: |
    echo Not secret: $(NotSecret)
    echo Is secret: $(IsSecret)
  displayName: Echo some vars
```
![image](https://user-images.githubusercontent.com/714283/48782852-0ad48f80-ecad-11e8-9cd0-d369260cb491.png)

We don't have plans to enable dynamic group names. You may be able to make something work with template parameters, though.
