### ISSUE TITLE
Reg Code coverage build artifacts

### ISSUE THREAD

**Issue by rizwaans** [MicrosoftDocs/vsts-docs#2599]
Hi, I am a newbie to Azure Devops pipelines. 

I am trying to see if there is way to have the Code coverage reports ( build artifacts) published directly to local machine rather downloading it. and have it run on some browser to check the reports.

for reference:https://docs.microsoft.com/en-us/azure/devops/pipelines/test/review-code-coverage-results?view=vsts 
Artifacts section. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fabbd5e2-993f-89da-665f-f39ab63d7c42
* Version Independent ID: 493c2582-69a4-1bbe-03b5-0bb5f1d41aed
* Content: [Code coverage Azure Pipelines and TFS - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/test/review-code-coverage-results?view=vsts)
* Content Source: [docs/pipelines/test/review-code-coverage-results.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/test/review-code-coverage-results.md)
* Product: **devops**
* GitHub Login: @vinojos
* Microsoft Alias: **vinojos**

**Comment by mohacsizs** [comment]
+1 
It would be useful to publish uncompressed code coverage html reports as artifacts, and then browse them online from azure (AFAIK GitLab supports this).

**Comment by vinodjo** [comment]
Adding @PBoraMSFT for appropriate guidance on this.

**Comment by ldcl289** [comment]
Any news on how to solve this problem?
I have the same situation where the only outcome from enabling coverage collection is a .coverage, which only allows me to download, but it doesn't seem to be process on the summary tab or to block pull requests (which is something that we are requiring).
My team's environment is a mix between c++ with c# code.

Thanks.

**Comment by TroySchmidt** [comment]
This will post the coverage results as an official tab.  The good news is that you can merge multiple coverage files.  This only requires that that `reportgenerator` tool is installed globally on your build server.  The code below is using the `coverlet.collector` NuGet package installed in the test project.  That is what provides the collector `XPlat Code Coverage`.  Also, this is for .NET Core 3.1.

```yml
    - task: CmdLine@2
      displayName: Run Tests and ReportGenerator
      inputs:
        targetType: 'inline'
        script: |
          dotnet test --logger:trx --collect:"XPlat Code Coverage"
          reportgenerator "-reports:**\TestResults\*\coverage.cobertura.xml;**\TestResults\cobertura-coverage.xml" "-targetdir:$(System.DefaultWorkingDirectory)\coveragereport" "-reporttypes:HtmlInline_AzurePipelines_Dark;Cobertura;Badges" "-assemblyfilters:-Dapper*;-Dommel*"
      continueOnError: true

    - task: PublishTestResults@2
      displayName: 'Publish Test Results'
      inputs:
        testResultsFormat: 'VSTest' # Options: JUnit, NUnit, VSTest, xUnit, cTest
        testResultsFiles: '**/TestResults/*.trx' 
        testRunTitle: API.Tests

    - task: PublishCodeCoverageResults@1
      displayName: 'Publish code coverage report'
      inputs:
        codeCoverageTool: 'cobertura'
        summaryFileLocation: '$(System.DefaultWorkingDirectory)\coveragereport\Cobertura.xml'
        reportDirectory: '$(System.DefaultWorkingDirectory)\coveragereport'
```
