### ISSUE TITLE
Task Fails: ##[error]Value cannot be null.  Parameter name: hashAndAlgorithm

### ISSUE THREAD

**Issue by jockerman-ipspark** [MicrosoftDocs/vsts-docs#2615]
I have tried to configure and use this task with and without parameterized inputs.  Every build fails on this task with the following:

2018-11-29T23:12:13.0615583Z ##[error]Value cannot be null.
Parameter name: hashAndAlgorithm

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b03d67d0-8738-72e6-dbe7-324c1784d4fc
* Version Independent ID: bbb4d774-cd98-3ecb-7ccf-5f49e6f2b425
* Content: [Download Pipeline Artifact task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-pipeline-artifact?view=vsts)
* Content Source: [docs/pipelines/tasks/utility/download-pipeline-artifact.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/download-pipeline-artifact.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **midenn**

**Comment by jayllon** [comment]
I'm experiencing exactly the same problem. Releases fail while downloading artifacts.

**Comment by elbatk** [comment]
Hi @jockerman-ipspark  and @jayllon , that's not supposed to happen. Are you still having this issue? I'm going to loop @alexmullans in, but it would probably be most helpful if you can submit the logs and issue to the Azure DevOps Developer Community (https://developercommunity.visualstudio.com/spaces/21/index.html), which is actively monitored by the product team. I'm going to close this here as a docs here, but if you find that a docs change should be made, please feel free to reach back out!

**Comment by alexmullans** [comment]
@mitchdenny I think you've got a fix coming for this one?

**Comment by katlimruiz** [comment]
I think I found the issue to be that I was using PublishBuildArtifact and then DownloadPipelineArtifact. The correct pair is PublishPipelineArtifact and DownloadPipelineArtifact.

**Comment by infogulch** [comment]
This is still an issue for me.  I have builds called A and B.  In build A I'm using DownloadPipelineArtifact to download the artifacts from build B because it's used as an input to build A.  This fails with the error in the title of the issue.

Here is the (translated) yaml of this pipeline step:
```
steps:
- task: DownloadPipelineArtifact@1
  displayName: 'Download Pipeline Artifact'
  inputs:
    buildType: specific
    project: '51479742-74ca-4d83-859f-c8b0720c0fba'
    pipeline: 957
    branchName: refs/heads/master
    buildVersionToDownload: latestFromBranch
    artifactName: drop
    targetPath: 'images/install-internal-service/'
```

Debug logs for this step (it's the first step in the pipeline): [vsts-issue-2615.log](https://github.com/MicrosoftDocs/vsts-docs/files/3267704/vsts-issue-2615.log)
