### ISSUE TITLE
Needs proper working examples for Java Tool Installer (for Windows/Mac/Linux)

### ISSUE THREAD

**Issue by brunoborges** [MicrosoftDocs/vsts-docs#2675]
This task is impossible to use without a working example for all three operating systems. The documentation does not cover the intrinsic details of where the JDK archive (ZIP/TAR.GZ) will be placed, where it will be extracted, how JAVA_HOME will be set, and how it can be used later.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 182d85e3-f124-b440-78cb-2b1c52617ae0
* Version Independent ID: 26372d15-3e1a-0e8b-f5bb-abf0165f6480
* Content: [Java Tool Installer task - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/java-tool-installer?view=vsts)
* Content Source: [docs/pipelines/tasks/tool/java-tool-installer.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/tool/java-tool-installer.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by brunoborges** [comment]
Pinging @DavidStaheli

**Comment by DavidStaheli** [comment]
Keep-alive

**Comment by darrenfurr** [comment]
This worked for me...
```
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: "11"
      jdkArchitectureOption: x64
      jdkSourceOption: localDirectory
      jdkFile: "/builds/openjdk-11.0.2_linux-x64_bin.tar.gz"
      jdkDestinationDirectory: "/builds/binaries/externals"
      cleanDestinationDirectory: true
```

**Comment by brunoborges** [comment]
@darrenfurr The installer does not describe how to drop the file (the .tar.gz for example) in a location one can reference from the yaml configuration.

It would also be helpful to reference a publicly hosted file (https URL) instead of a storage endpoint or a local file.

Lastly, versionSpec is tricky these days. Is it 1.11? 1.8? 8.0? 11.0? What's the standard and how is this version going to be used?

**Comment by darrenfurr** [comment]
@brunoborges - Valid points & it would be nice if the pipeline task supported that. I was just trying to provide an example that worked for me using a local file.

**Comment by luzlab** [comment]
So there's a type in the documentation - "azureStorage" should actually be "AzureStorage". This is an example of a working JavaToolInstaller task that pulls the JDK from Azure Storage. The file in Azure Storage should be an archive (.zip, .gz, etc) of the JAVA_HOME directory (so it includes the bin, lib, include, jre, etc directories).

```
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '6'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: AzureStorage
    azureResourceManagerEndpoint: gss-build-artifacts
    azureStorageAccountName: gssbuildassets
    azureContainerName: jdk
    azureCommonVirtualFile: 'jdk1.6.0_45.zip'
    jdkDestinationDirectory: '$(Agent.ToolsDirectory)/jdk6'
    cleanDestinationDirectory: false
```
