### ISSUE TITLE
Variable Group YAML Syntax

### ISSUE THREAD

**Issue by MattMencel** [MicrosoftDocs/vsts-docs#2680]
The documentation for variable groups in YAML just references one group.  Is it possible to have several as well as some single variables?

I know this doesn't work...

```
variables:
- group: 'Group-A
- group: 'Group-B'
  myVarA: 'foo'
  myVarB: 'bar'
```

**Comment by vtbassmatt** [comment]
Great feedback, I'll get this fixed. You can use this:

```yaml
variables:
- group: 'Group-A
- group: 'Group-B'
- name: 'myVarA'
  value: 'foo'
- name: 'myVarB'
  value: 'bar'
```
