### ISSUE TITLE
Are build variables supported in trigger paths?

### ISSUE THREAD

**Issue by simonness** [MicrosoftDocs/vsts-docs#2691]
I have a monorepo where I'd like to share a generic pipeline yaml file amongst several projects.

Builds do not seem to automatically trigger correctly if I use the following yaml:

```
trigger:
  batch: true
  branches:
    include:
    - '*'
  paths:
    include:
    - src/$(projectName)/*
```

Where `projectName` is a variable manually defined on the pipeline after its creation.  If I replace `$(projectName)` for the actual folder name in the yaml automatic triggers work as expected.  Are build variables supported in trigger paths?

I'd also like to +1 #2967 with a view to supporting monorepos, to prevent lots of CI builds triggering on new branch creation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5673ec1-c7d1-e0ac-043a-8fc3d5b226a9
* Version Independent ID: b4872831-51c0-6cf8-1c56-de20beb38a80
* Content: [Build pipeline triggers - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=vsts&tabs=yaml)
* Content Source: [docs/pipelines/build/triggers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/triggers.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by seangwright** [comment]
I'm running into this issue.

My `.yml` looks as follows

```
trigger:            
  batch: true       
  branches:         
    include:        
    - master        
  paths:
    include:
    - $(build.custom.projectName)/*

pool:
  name: Hosted Windows 2019 with VS2019

steps:
- template: build-pipeline-release-steps.yml
  parameters:
    projectName: $(build.custom.projectName)
```

Where my steps are all defined in `build-pipeline-release-steps.yml` and `build.custom.projectName` is a variable defined for the pipeline in the Pipelines UI.

This allows me to re-use the same `.yml` for every project in the repo.

Manually queuing a build works fine but a merge of a branch into `master` does not kick off a build.

In other `.yml` files where the `path` trigger does not include a variable, my build starts when the branch is merged into `master`.
