### ISSUE TITLE
I need to test against .net core 1.0, 1.1, 2.0, 2.1, 2.2.

### ISSUE THREAD

**Issue by aensidhe** [MicrosoftDocs/vsts-docs#2706]
I have open source project. For build we need to use .net core sdk 2.2, for tests I need .net core runtimes: 1.0, 1.1, 2.0, 2.1, 2.2.

How can I install several runtimes and/or sdks with this tool?

```yaml
    - task: DotNetCoreInstaller@0
      displayName: Installing .net core runtime 1.0.13
      inputs:
        version: '1.0.13'
        packageType: runtime
    - task: DotNetCoreInstaller@0
      displayName: Installing .net core runtime 1.1.10
      inputs:
        version: '1.1.10'
        packageType: runtime
    - task: DotNetCoreInstaller@0
      displayName: Installing .net core sdk 2.2.100
      inputs:
        version: '2.2.100'
        packageType: sdk
```

That does not work.

If I install sdk first, runtime later - it does not work too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9660c58-3366-f1be-8380-d6cf1d3c0150
* Version Independent ID: 226a4fd8-bce8-3333-d8d6-7af933c7b060
* Content: [.NET Core Tool Installer task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/dotnet-core-tool-installer?view=vsts)
* Content Source: [docs/pipelines/tasks/tool/dotnet-core-tool-installer.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/tool/dotnet-core-tool-installer.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **dastahel**

**Comment by vigneshmsft** [comment]
you can always run tests in different agents(just download one version in one agent) for all these different versions

**Comment by aensidhe** [comment]
@vigneshmsft that defeats any benefits of using azure pipelines. If I can't reduce amount of code needed for my cross-platform CI, then I don't need azure pipelines.

I solved that problem in another way: I install 1 [sdk using task and everything else manually](https://github.com/progaudi/azure-pipelines/blob/master/library/install.yml). But I would like to use task everywhere.

**Comment by vigneshmsft** [comment]
If I am not wrong your script downloads SDK and not the runtime.
using the task did  you try installing different version of SDKs(SDKs include the runtimes as well)?

**Comment by aensidhe** [comment]
@vigneshmsft 

1. SDK contains some runtime
2. I need 2.2 SDK to build the project

**Comment by mu88** [comment]
I have almost the same issue: I need to install two versions of the .NET Core SDK (2.2 and 3.0-preview7), because my project uses ElectronNET (needs .NET Core 2.2) and Blazor (needs .NET Core 3.0).

How can I do this?

**Comment by hiyadav** [comment]
Hey @vigneshmsft @mu88 @tairan @aensidhe 
We have enabled the functionality to install mutliple sdk/runtime versions using UseDotNetV2 task. You can use the task multiple times to install different versions and they will all be available for the remaining tasks in the pipeline.

**Comment by aliostad** [comment]
Having the same problem.

**Comment by MariusVolkhart** [comment]
My guess is that folks may be looking for the matrix strategy.

```yaml
strategy:
  matrix:
    core2:
      netCoreVersion: '2.1.x'
    core3:
      netCoreVersion: '3.1.x'

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: UseDotNet@2
  inputs:
    version: '2.1.x'

- task: UseDotNet@2
  inputs:
    version: $(netCoreVersion)
    packageType: runtime
```
