### ISSUE TITLE
Syntax is not working

### ISSUE THREAD

**Issue by westandy-dcp** [MicrosoftDocs/vsts-docs#2744]
I have this in a build.yml file that is being run:
steps:
 - bash: |
    echo "Hello world running in directory $PWD"
  - script: npm run build
  - script: npm run test

And I'm getting this error


build.yml (Line: 4, Col: 3, Idx: 76) - (Line: 4, Col: 3, Idx: 76): While parsing a block collection, did not find expected '-' indicator.

As helpful as that error message is, I am stumped.  I am using this Document's syntax.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 797838e7-f32b-868e-8766-8d96973bf18f
* Version Independent ID: 20c9e62d-56ec-f5a0-c3f9-6f72bf96252e
* Content: [Cross-platform scripting - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/cross-platform-scripting?view=vsts&tabs=yaml#feedback)
* Content Source: [docs/pipelines/scripts/cross-platform-scripting.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/scripts/cross-platform-scripting.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by andyjlewis** [comment]
Could you please point to the example in the doc that shows the pattern that's not working for you?

**Comment by vtbassmatt** [comment]
Your spacing is off. YAML is (highly) whitespace sensitive per its spec. The `-` characters need to be either at the same level as `steps` or indented by 2 spaces.

```yaml
# Either this:
steps:
- bash: |
    echo "Hello world running in directory $PWD"
- script: npm run build
- script: npm run test

# Or this:
steps:
  - bash: |
      echo "Hello world running in directory $PWD"
  - script: npm run build
  - script: npm run test

```
