### ISSUE TITLE
Checkout section is incorrect and incomplete

### ISSUE THREAD

**Issue by mydiemho** [MicrosoftDocs/vsts-docs#2752]
1. `checkout` didn't work, I have to use `repo` (I found this by using the GUI designer then look at the generated yaml)
2. Example should be updated to show there `repo`,  `clean`, and `fetchDepth` etc. need to be under the `resources` section
```
resources:
  - repo: self  # self represents the repo where the initial Pipelines YAML file was found
    clean: boolean  # whether to fetch clean each time
    fetchDepth: number  # the depth of commits to ask Git to fetch
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=vsts&tabs=example#checkout)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **macoope**
