### ISSUE TITLE
`GithubRelease` task: clarify the `action`

### ISSUE THREAD

**Issue by kittaakos** [MicrosoftDocs/vsts-docs#2755]
First off, the `action` must be [case sensitive](https://github.com/Microsoft/azure-pipelines-tasks/issues/9062#issuecomment-446851662) as of today.
Secondly, it is strange that I have to use the `Edit` `action` if I would like to create the tag as part of creating the GH release.

See here:
https://github.com/Microsoft/azure-pipelines-tasks/blob/d9cfbdfcfcd98bf8dfb162128123075d3035cc40/Tasks/GithubReleaseV0/main.ts#L56-L66

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b12d2c4-f871-1d14-0c16-91e58fb1130b
* Version Independent ID: 6b9e1d67-f303-7445-e573-830309ba49a4
* Content: [GitHub Release task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/github-release?view=vsts)
* Content Source: [docs/pipelines/tasks/utility/github-release.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/github-release.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **dastahel**

**Comment by RoopeshNair** [comment]
@Raiyan Alam<mailto:Mohammed.Alam@microsoft.com> – can you please take a look?

Thanks
Roopesh Nair

**Comment by raiyanalam** [comment]
@kittaakos Apologies for the inconvenience. 
 The task can create tags even when `create ` action is used. However, you need to provide us what tag you want us to create. For doing this we have a parameter called 'tagSource'. Set it to 'manual' and in the 'tag' parameter mention the tag you want to create. Here is the yaml that would might be useful to you:

```
jobs:
- job: release_macOS
  displayName: 'Release Build (macOS)'
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - script: rm -rf dist && mkdir dist && echo `date` > dist/my-release.txt && zip -jr ./dist/my-release.zip ./dist/my-release.txt
    displayName: 'Create Release'
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: dist/my-release.zip
      artifactName: 'my-release.zip'
    displayName: 'Publish Release'
  - task: GithubRelease@0
    inputs:
      gitHubConnection: kittaakos
      repositoryName: kittaakos/azure-sandbox
      assets: $(build.artifactstagingdirectory)/*.zip
      action: 'create'
      target: '$(build.sourceVersion)'
      tagSource: 'manual'
      tag: '$(myVariableForUserDefinedTag)'
      title: 'Tag Title'
      assetUploadMode: 'delete'
      isDraft: true

```
