### ISSUE TITLE
Document YAML ${{ if }}:

### ISSUE THREAD

**Issue by bricelam** [MicrosoftDocs/vsts-docs#2793]
I don't see any documentation about the special `${{ if condition() }}` YAML property name syntax...

Example:
``` yml
pool:
  ${{ if in(variables['Build.Reason'], 'PullRequest') }}:
    name: my-pr-pool
  ${{ if notin(variables['Build.Reason'], 'PullRequest') }}:
    name: my-ci-pool
```
