### ISSUE TITLE
Tasks and Versioning

### ISSUE THREAD

**Issue by westandy-dcp** [MicrosoftDocs/vsts-docs#2816]
I feel like this needs more explanation.  I'm trying to create an artifact in my release pipeline and I'm getting this error:
Job &lt;MyJob&gt;: Step references task 'ArchiveBackendArtifacts' at version '0' which does not exist.

Here's my pipeline definition:

jobs:
  - job: ${{ parameters.componentName }}
    displayName: ${{ parameters.componentName }}
    pool:
      vmImage: "ubuntu-16.04"
    steps:
      - template: build.yml
      - task: ArchiveBackendArtifacts@1
        displayName: Archive Backend
        inputs:
          archiveFile: $(Build.ArtifactStagingDirectory)/backend.zip
          includeRootFolder: false
          rootFolderOrFile: $(System.DefaultWorkingDirectory)/packages/backend/.funcpack
          condition: succeeded()

The build.yml file looks like this:
steps:
  - script: npm install
    workingDirectory: packages/backend
    displayName: Installing Backend
  - script: npm run build
    workingDirectory: packages/backend
    displayName: Building Backend
  - script: npm run test
    workingDirectory: packages/backend
    displayName: Testing Backend

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8098f527-ebdf-60d5-3989-5228b7a207c1
* Version Independent ID: ce27c817-9599-00ef-5af2-3ac1dbad8dc6
* Content: [Build and Release Tasks in Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/tasks?view=vsts&tabs=yaml)
* Content Source: [docs/pipelines/process/tasks.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/tasks.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by elbatk** [comment]
Hi @westandy-dcp , the best place to post product issues is the [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html), which is actively monitored by the product team. Please link the ticket there on this thread though, as if there is a docs update that comes out of it, I'd like to help with that for future users!

**Comment by elbatk** [comment]
Also, out of curiosity, where are you finding that task?

**Comment by alexmullans** [comment]
@westandy-dcp it looks like you're trying to use the [Archive Files](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/archive-files?view=vsts) task, but have changed the task name in your YAML from `ArchiveFiles@2` to `ArchiveBackendArtifacts@1`, which doesn't exist (unless you've created and published a custom task by that name?). If you change the task name to `ArchiveFiles@2`, does your build run correctly?

**Comment by westandy-dcp** [comment]
So, I had no idea that the task names such as `ArchiveFiles` were predefined.  From the YAML docs, I got the impression that you can just make up the task name as you wish.  Is there a list somewhere of the MS Azure predefined tasks?  

I finally got this to work with this:

```
  - task: ArchiveFiles@2
    displayName: Archive Backend
    inputs:
      archiveFile: $(Build.ArtifactStagingDirectory)/backend.zip
      includeRootFolder: false
      rootFolderOrFile: $(System.DefaultWorkingDirectory)/packages/backend/functions/.funcpack

  - task: PublishBuildArtifacts@1
    displayName: Publish Backend Artifacts
    inputs:
      artifactName: GasSchedulingFunctionApp
      PathtoPublish: $(Build.ArtifactStagingDirectory)/backend.zip
```
