### ISSUE TITLE
timeoutInMinutes doesn't have any effect in Job

### ISSUE THREAD

**Issue by imedmar** [MicrosoftDocs/vsts-docs#2916]
I have tried to set `timeoutInMinutes` both as a child of `job` and a child of `script`, but the job always times out since it goes over the default of 30 minutes. 

FYI, my pipelines are private under a free subscription. Is it possible that the timeout config is capped at 30 for free subscriptions?
If not, then is this a bug or inaccurate documentation?

It'd be great if someone could verify this.

Related article [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=vsts&tabs=schema).

**Comment by vtbassmatt** [comment]
The documentation [mentions that private jobs on hosted agents only get 30 minutes](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?tabs=yaml&view=vsts#timeouts). It's not directly in the schema topic you referenced, but it's linked from there.

**Comment by tashrifbillah** [comment]
@vtbassmatt @steved0x  @andyjlewis  my project is public, yet it gets cancelled at 60 minutes:
https://dev.azure.com/tbillah/tbssDemo

I am using `timeoutInMinutes` with `script`:
```
steps:
- script: |
    docker build -t $(imageName) -f Dockerfile.centos7 --build-arg USER=$(user) --build-arg CWD=$(wd) .
  displayName: 'Build a docker image'
  timeoutInMinutes: 120
```

Here is my yml file:
https://github.com/tashrifbillah/tbss_containers/blob/b23ec1e914c580d0fcb903d4884eae7e52257b15/azure-pipelines.yml

For details, here is the GitHub repo:
https://github.com/tashrifbillah/tbss_containers

**Comment by vtbassmatt** [comment]
That's a step timeout, you need to set the job timeout:

```yaml
timeoutInMinutes: 120

steps:
- script: |
    docker build -t $(imageName) -f Dockerfile.centos7 --build-arg USER=$(user) --build-arg CWD=$(wd) .
  displayName: 'Build a docker image'
```
