### ISSUE TITLE
Path filters ignored on 1st push to new branches for CI builds

### ISSUE THREAD

**Issue by philip-reed** [MicrosoftDocs/vsts-docs#2967]
I had a weird issue that I don't think is explained above.
If you have two build definitions defined with CI triggers enabled as follows:

```
# Build Def A
# Only want this build to trigger if something changes under docs/A
trigger:
  branches:
    include:
    - master
    - users/*
  paths:
    include:
    - docs/A/*   
```

```
# Build Def B
# Only want this build to trigger if something changes under docs/B
trigger:
  branches:
    include:
    - master
    - users/*
  paths:
    include:
    - docs/B/*   
```

Then create a new user branch and push something to it with a change under docs/A/, both builds are triggered.
Presumably this is because both docs/A & docs/B have been **created** and this is considered a change.
Subsequent changes under docs/A/ only trigger Build A as expected. 
Not sure if this is expected behaviour?
If it is expected behaviour, how might someone prevent all of the builds triggering for each 1st push to a new branch?  This is in the context of having multiple projects/solutions in a single repository, which i'm not sure is best practice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5673ec1-c7d1-e0ac-043a-8fc3d5b226a9
* Version Independent ID: b4872831-51c0-6cf8-1c56-de20beb38a80
* Content: [Build pipeline triggers - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=vsts&tabs=yaml)
* Content Source: [docs/pipelines/build/triggers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/triggers.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by MattMencel** [comment]
Is there any progress on this?  I have several dozen builds configured in a monorepo... my triggers are configured like this...

``` yaml
trigger:
  batch: true
  branches:
    include:
      - master
      - feature/*
  paths:
    include:
      - 'PATH/TO/BUILD/CODE'
```

When I push new code to a feature branch, instead of just building for the included build path, it runs every build in the repo.

This happens before the merge to master, and there are no build policies specified on `feature/*` in the repo.
