### ISSUE TITLE
Clarification on use of “preview” functionality

### ISSUE THREAD

**Issue by Kissaki** [MicrosoftDocs/vsts-docs#3029]
I am trying to use pipeline artifacts rather than build artifacts - which these two articles suggest to prefer.

However, when I add the `PublishPipelineArtifact@0` task description into the yaml file it says this is not a known task (and a build indeed fails). Do I have to somehow and somewhere enable this preview functionality?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 861ce7a5-4fa4-55f1-2c97-46a9cc6a2f66
* Version Independent ID: bdf954b9-9bbe-8b34-b674-71ad8153519d
* Content: [Publish and consume Pipeline artifacts in builds - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=vsts&tabs=yaml)
* Content Source: [docs/pipelines/artifacts/pipeline-artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/artifacts/pipeline-artifacts.md)
* Product: **devops**
* GitHub Login: @alexmullans
* Microsoft Alias: **amullans**

**Comment by mitchdenny** [comment]
Can I just confirm that you are using Azure DevOps service (not Azure DevOps server). Also can you provide a snippet out of your YAML file so we can take a quick look.

**Comment by Kissaki** [comment]
Yes, service at dev.azure.com

I tried using in my steps section of the azure-pipelines.yml configuration:

```
- task: PublishPipelineArtifact@1
  inputs:
    artifactName: 'public'
    targetPath: 'public'
```

Build fails with
![image](https://user-images.githubusercontent.com/93181/51274778-5024ed00-19d0-11e9-9893-b97a6467513b.png)

Config file editor error:
![image](https://user-images.githubusercontent.com/93181/51274840-82cee580-19d0-11e9-9093-56d4f61027bd.png)

Using build artifact on the other hand works fine with
```
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: 'public'
    artifactName: public
```

**Comment by mitchdenny** [comment]
@steved0x we haven't released the V1 of PublishPipelineArtifact, can you use ```PublishPipelineArtifact@0``` instead. The error you are seeing actually suggests something wrong with the structure of the YAML document as well.

Could you try just this in a pipeline?

```yaml
steps: 
- task: PublishPipelineArtifact@0
   inputs:
     artifactName: public
     targetPath: public 
```
