### ISSUE TITLE
RS5 build agent?

### ISSUE THREAD

**Issue by shizn** [MicrosoftDocs/vsts-docs#3037]
Any timeline for RS5 build agent with process isolation container support?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43799c5d-2f13-cc76-a1c0-a3f850e16d4e
* Version Independent ID: 97a5b73f-faf7-f9c0-9269-fc79984616d6
* Content: [Deploy a build and release agent on Windows - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=vsts)
* Content Source: [docs/pipelines/agents/v2-windows.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/v2-windows.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vtbassmatt** [comment]
We don't have plans to do anything special for process isolation containers. You can specify additional `docker run` arguments, though:
```yaml
resources:
  containers:
  - container: mycontainer
    image: mcr.microsoft.com/windows/nanoserver:1809
    options: --isolation=process

pool: my1809privatepool

container: mycontainer
steps:
- script: ver
```

If you run into agent issues, drop by https://github.com/Microsoft/azure-pipelines-agent to file an issue.
