### ISSUE TITLE
Predefined Variables are not replaced in "displayName" from the .yml file?

### ISSUE THREAD

**Issue by StefH** [MicrosoftDocs/vsts-docs#3118]
When using this yml:
``` yml
variables:
  tag: $(Build.BuildNumber)

- script: docker tag $(DOCKER_ID)/$(imageName):latest $(DOCKER_ID)/$(imageName):$(tag)
  displayName: 'Tag Docker image [$(imageName):$(tag)]'
```

The logging in Azure DevOps build shows `Tag Docker image [MyImageName:$(Build.BuildNumber)]`, but I would expect something like `Tag Docker image [MyImageName:20190124.2]`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Predefined build variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=vsts)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by zufengxu** [comment]
same issue here

**Comment by anouarattn** [comment]
same issue guys here, any solution ?

**Comment by zufengxu** [comment]
give it a try using syntax like this :

${{ variables.tag }}

**Comment by anouarattn** [comment]
not working,
even ${{ $(variables.tag) }} or ${{ '$(variables.tag)' }}

thank you

**Comment by wagnerbsouza** [comment]
Same here :disappointed: 
![image](https://user-images.githubusercontent.com/49475734/71170326-4f897c00-225b-11ea-9bbf-ea18de538d43.png)

Task:
```
- task: CopyFiles@2
    displayName: 'Copy files to $(Build.ArtifactStagingDirectory)'
    inputs:
      Contents: |
        bin/**
        deploy/**
        build/libs/**
        gradle.properties
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
```

**Comment by bjeromeHCS** [comment]
This is working for me:

```
variables:
  - name: branchName
    value: $(Build.SourceBranchName) # value = "myBranch" as example

steps:
  - checkout: self
    displayName: Checkout repo@${{ variables.branchName }} # Shows "Checkout repo@myBranch"
```

Single quotes aren't necessary.
