### ISSUE TITLE
Deploying multi containers with Azure DevOps

### ISSUE THREAD

**Issue by shellwhale** [MicrosoftDocs/vsts-docs#3166]
Hello,
I would like to implement a pipeline that would automatically run my docker-compose.yml file. One of the containers runs a PHP server and I'd like to be able access it from the web. I saw the doc [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/docker?view=azdevops&tabs=yaml) but I find it quite counter intuitive. 

```yaml
pool:
  vmImage: 'Ubuntu 16.04

- script:
    docker-compose -f docker-compose.yml --project-directory .`
```

Is this azure-pipelines.yml file correct ? What should I do after pushing it to the branch root of my repo if I want to see/access the build ?
