### ISSUE TITLE
Referencing a secret variable in a matrix substitution is not working

### ISSUE THREAD

**Issue by frankie567** [MicrosoftDocs/vsts-docs#3231]
Let's consider a use case where you have a build job with a matrix, so that you can build your app for different configurations:

```yaml
jobs:
  - job: 'build'
    pool:
      vmImage: 'ubuntu-16.04'
    strategy:
      matrix:
        INSTANCE_1:
          NAME: 'Instance 1'
          FOO: $(INSTANCE1_FOO)
          SECRET: $(INSTANCE1_SECRET)
        INSTANCE_2:
          NAME: 'Instance 2'
          FOO: $(INSTANCE2_FOO)
          SECRET: $(INSTANCE2_SECRET)
    variables:
        - group: 'variable-group'
    steps:
        ...
```

We have defined a variable group named `variable-group` with the variables `INSTANCE1_FOO`, `INSTANCE1_SECRET`, `INSTANCE2_FOO`, `INSTANCE2_SECRET`, where `*_SECRET` are secret variables.

When doing this, during the job, the `*_FOO` variables do have their value assigned, but not the `*_SECRET` variables.

Is this by design for security reasons? Or is it a bug?

Best regards!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4827aa99-ae62-bd63-6f2f-a87a4065ed27
* Version Independent ID: c9e461ee-7f42-3503-9460-18fa3a807bbb
* Content: [Variable groups for Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/variable-groups?view=azure-devops&tabs=yaml#use-a-variable-group)
* Content Source: [docs/pipelines/library/variable-groups.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/variable-groups.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**
