### ISSUE TITLE
Explain how to pass parameters to a step template

### ISSUE THREAD

**Issue by letmaik** [MicrosoftDocs/vsts-docs#3273]
This article currently says:

&gt; The above example shows only how to use parameters with a job template. But you can also use parameters with step templates.

I tried to pass parameters when using step templates but just got an error "Unexpected value 'parameters'".

This is what I tried:
```
jobs:
- job: foo
  pool:
    vmImage: vs2017-win2016
  parameters:
    FOO: bar
  steps:
  - template: foo.yml
```

Where `foo.yml` is a step template:
```
steps:
- script: echo ${{ FOO }}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6724abea-bbdc-bf66-ed5e-3214fa6c3e66
* Version Independent ID: 4f8dab21-3f0e-da32-cc0e-1d85c13c0065
* Content: [Job and step templates - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops)
* Content Source: [docs/pipelines/process/templates.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/templates.md)
* Product: **devops**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **alewis**

**Comment by vtbassmatt** [comment]
Sorry for the confusion. Your example should read:
```yaml
jobs:
- job: foo
  pool:
    vmImage: vs2017-win2016
  steps:
  - template: foo.yml
    parameters:
      FOO: bar
```
