### ISSUE TITLE
Clarify download location of Universal Packages

### ISSUE THREAD

**Issue by letmaik** [MicrosoftDocs/vsts-docs#3318]
Where are the contents of a universal package downloaded to?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 405dfb6a-2f3d-1d74-2d28-d00be3bb069d
* Version Independent ID: d446b533-c215-6302-3df2-93b1ffd936df
* Content: [Publish and download Universal Packages in pipelines - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/universal-packages?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/artifacts/universal-packages.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/artifacts/universal-packages.md)
* Product: **devops**
* GitHub Login: @alexmullans
* Microsoft Alias: **amullans**

**Comment by eknraw** [comment]
It appears to be $(Build.SourcesDirectory).

You can get it to go somewhere else by using "downloadDirectory": 

```
- task: UniversalPackages@0
  displayName: 'Universal download'
  inputs:
    command: download
    vstsFeed: 'PackageFeed'
    vstsFeedPackage: 'Package'
    vstsPackageVersion: 1.0.0
    downloadDirectory: '$(Build.SourcesDirectory)\anotherfolder'
```
