### ISSUE TITLE
Can the parameter type is bool?

### ISSUE THREAD

**Issue by vanthoainguyen** [MicrosoftDocs/vsts-docs#3325]
like 
```
# File: templates/steps-with-params.yml

parameters:
  runExtendedTests: false

steps:
- script: npm test
- ${{ if eq(parameters.runExtendedTests, true) }}:
  - script: npm test --extended
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6724abea-bbdc-bf66-ed5e-3214fa6c3e66
* Version Independent ID: 4f8dab21-3f0e-da32-cc0e-1d85c13c0065
* Content: [Job and step templates - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#step-re-use)
* Content Source: [docs/pipelines/process/templates.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/templates.md)
* Product: **devops**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **alewis**
