### ISSUE TITLE
How to define multiple file paths for "Projects" Task argument?

### ISSUE THREAD

**Issue by PureKrome** [MicrosoftDocs/vsts-docs#3343]
Hi all 👋 

So the `DotNetCoreCLI@2` Task has the option to set 1 or more Project paths.

![image](https://user-images.githubusercontent.com/899878/52719641-1f999880-2ffa-11e9-902e-16a1b8bcbd23.png)

![image](https://user-images.githubusercontent.com/899878/52719696-3b04a380-2ffa-11e9-91f6-c62bd752bd45.png)

Can someone please provide some valid syntax for this, please?

I've tried the following and they don't seem to work:

```
- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: ['/tests/<Foo1>/<Foo1>.csproj', '/tests/<Foo2>/<Foo2>.csproj']
    arguments: '--configuration $(buildConfiguration)'
  displayName: 'dotnet test'  
```

```
- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: 
    - '/tests/<Foo1>/<Foo1>.csproj'
    - '/tests/<Foo2>/<Foo2>.csproj'
    arguments: '--configuration $(buildConfiguration)'
  displayName: 'dotnet test'  
```

Can anyone help, please?
