### ISSUE TITLE
Sample yaml for signing and provisioning

### ISSUE THREAD

**Issue by nacient** [MicrosoftDocs/vsts-docs#3347]
Hello, 

I am following this documentation for an xcode10 pipeline in Azure DevOPS which requires signing and provisioning of an iOS app. The signing happens correctly but provisioning with a valid provisioning profile fails in the xcode task that uses that profile that InstallAppleProvisioningProfile@1 should install. 

This documentation is great but it is missing a sample yaml companion to refer to for when signing and provisioning apps since yaml is now the recommended way to go by Microsoft. 

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e66a70d-e359-9d0a-0143-a9e43b263795
* Version Independent ID: 7b320a02-0a63-947a-3017-4826ab461112
* Content: [Sign Your Mobile App During CI - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/mobile/app-signing?view=azure-devops&tabs=apple-install-during-build)
* Content Source: [docs/pipelines/apps/mobile/app-signing.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/apps/mobile/app-signing.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by VitorRigoni** [comment]
Took me a bit, but I found this. Had to use the yaml editor in azure devops to check with intellisense which were the options:

```yaml
- task: XamariniOS@2
    inputs:
      solutionFile: '**/*iOS.csproj'
      configuration: 'AppStore'
      packageApp: true
      signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
      signingProvisioningProfileID: '$(APPLE_PROV_PROFILE_UUID)'
```
