### ISSUE TITLE
Question about skipping a job in the template?

### ISSUE THREAD

**Issue by vanthoainguyen** [MicrosoftDocs/vsts-docs#3356]
What is the coolest way of toggle off a step in the template.
For example, only run integration tests if branch is master, i attempted to do this way but it doesn't work.

```
# File: azure-pipelines.yml
variables
   runExtendedTests: 'false'

steps:
- script: npm install

- powershell: Write-Host "$("##vso[task.setvariable variable=runExtendedTests]") true"
  displayName: 'toggle on integrationTests'
  conditions:  eq(variables['Build.SourceBranch'], 'refs/heads/master')

- template: templates/steps-with-params.yml  # Template reference
  parameters:
    runExtendedTests: $(runExtendedTests)
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6724abea-bbdc-bf66-ed5e-3214fa6c3e66
* Version Independent ID: 4f8dab21-3f0e-da32-cc0e-1d85c13c0065
* Content: [Job and step templates - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#step-re-use)
* Content Source: [docs/pipelines/process/templates.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/templates.md)
* Product: **devops**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **alewis**

**Comment by vtbassmatt** [comment]
Hmm, this won't work because the parameter will already be expanded with the static value of the variable before the PowerShell step gets a chance to run. This should work, though:

```yaml
# File: azure-pipelines.yml
variables
   runExtendedTests: 'false'

steps:
- script: npm install

- powershell: Write-Host "$("##vso[task.setvariable variable=runExtendedTests]") true"
  displayName: 'toggle on integrationTests'
  conditions:  eq(variables['Build.SourceBranch'], 'refs/heads/master')

- template: templates/steps-with-params.yml  # Template reference
  # the template uses `variables.runExtendedTests` directly
  # it's correctly set by the preceding step
```

This works because the template is effectively "`#include`d" and acts as if it were directly specified in the parent pipeline.
