### ISSUE TITLE
Version 1 of the task is not available

### ISSUE THREAD

**Issue by landrus** [MicrosoftDocs/vsts-docs#3444]
I tried today to move from version 0 to version 1 but I was getting the following error (which means the version is not available):
An error occurred while loading the YAML build pipeline: wrong number of segments

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b03d67d0-8738-72e6-dbe7-324c1784d4fc
* Version Independent ID: bbb4d774-cd98-3ecb-7ccf-5f49e6f2b425
* Content: [Download Pipeline Artifact task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-pipeline-artifact?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/download-pipeline-artifact.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/download-pipeline-artifact.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **midenn**

**Comment by elbatk** [comment]
Hi @landrus , you shouldn't be getting an error when trying to use V1 of that task, I've reached out to some people to see what's up!

**Comment by DanielSel** [comment]
+1, I have exactly the same issue.

**Comment by mitchdenny** [comment]
Thanks for reporting the issue. Can you provide an example of the YAML that you are using? And if possible the org name (just want to check whether there is a deployment issue going on).

**Comment by DanielSel** [comment]
Organization Name is my username (danielsel), Project is 'saw'
I would give a link to an example, but since it fails trying to load the yaml it doesn't even reach the state where a build is started.

A build from the affected pipeline: https://dev.azure.com/danielsel/saw/_build/results?buildId=73

The offending Build job (before I changed to V0 of the DownloadPipelineArtifact Task):

```yaml
- job: saw_openwrt
  displayName: 'Package SAW for OpenWrt (opkg)'
  dependsOn:
  - solc
  - saw_ts
  condition: succeeded()
  pool:
    vmImage: ubuntu-16.04
  steps:
  - task: DownloadPipelineArtifact@1
    inputs:
      buildType: current
      artifactName: saw-contract
      downloadPath: $(Build.SourcesDirectory)/router/openwrt_pkgs/saw/files/etc/saw
```

Thank you for the quick response and the effort! Very much appreciated :)
