### ISSUE TITLE
Unable to provide env variables to container

### ISSUE THREAD

**Issue by jrjohnson** [MicrosoftDocs/vsts-docs#3461]
Trying to pass environment to a container:

```
resources:
  containers:
    - container: mysql
      image: mysql:5.7
      ports:
        - 13306:3306
      env:
        - MYSQL_USER: test_user
        - MYSQL_PASSWORD: test_password
        - MYSQL_DATABASE: test_database
```

But I'm not able to find the right way to get this done. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d1c794c-d676-fc7e-758e-3464f16a1554
* Version Independent ID: 941de04a-2d34-ec82-8612-00e4070de673
* Content: [Service Containers - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/service-containers?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/service-containers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/service-containers.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **dakale**

**Comment by dakale** [comment]
Hi @jrjohnson 

You can specify the container environment with:

```yaml
- container: mycontainer
    image: myimage
    env:
      FOO: bar
```

and reference the container as a service. Or, if you define your service inline:

```yaml
services:
    nginx:
      image: nginx
      ports:
      - 127.0.0.1:8080:80/tcp
      env:
        SOME_ENV: value 
```
