### ISSUE TITLE
Wrong git is launched on Windows

### ISSUE THREAD

**Issue by Leon99** [MicrosoftDocs/vsts-docs#3561]
According to the doc,
&gt; Windows agents include Git Bash
however, when run on a self-hosted agent, it uses C:\WINDOWS\system32\bash.exe, which is WSL's bash, not Git bash.
It doesn't work BTW, but I'll file it separately as product feedback.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 797838e7-f32b-868e-8766-8d96973bf18f
* Version Independent ID: 20c9e62d-56ec-f5a0-c3f9-6f72bf96252e
* Content: [Cross-platform scripting - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/cross-platform-scripting?view=azure-devops&tabs=yaml#consider-bash)
* Content Source: [docs/pipelines/scripts/cross-platform-scripting.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/scripts/cross-platform-scripting.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by DrSensor** [comment]
Bash also not working on me when it has 2 bash steps.
```yaml
steps:
- bash: |
    curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $RUSTUP_TOOLCHAIN
    echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
  displayName: Install rust

- bash: |
    rustup target add $TARGET
  displayName: Install toolchains
```

The `Install rust` step is working but not with the `Install toolchains` step which give this error message:
```
##[section]Starting: Install toolchains
==============================================================================
Task         : Bash
Description  : Run a Bash script on macOS, Linux, or Windows
Version      : 3.148.2
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613738)
==============================================================================
Generating script.
##[error]Unable to locate executable file: 'bash'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also verify the file has a valid extension for an executable file.
##[section]Finishing: Install toolchains
```
