### ISSUE TITLE
What is the correct syntax for passing a list

### ISSUE THREAD

**Issue by MAHDTech** [MicrosoftDocs/vsts-docs#3570]
What would be the correct syntax in this scenario.

1. Lets say I have a job which is using a step template as follows.

```yaml
# Job.yml
jobs:
  - job: TEST
    displayName: Testing passing a list environment variables to a step template
    pool:
      name: MyPoolName
      vmImage: MyVMImage
    strategy:
      parallel: 1
    continueOnError: false
    workspace:
      clean: all
    timeoutInMinutes: 5
    cancelTimeoutInMinutes: 5
    steps:
      - template: Steps.yml
        parameters:
            pwsh: true
            ScriptPath: "$(Build.SourcesDirectory)/Scripts/Test.ps1"
            EnvVars:
              - VAR1: HELLO
              - VAR2: WORLD
```

2. Inside the step template, I would like to have an "each" like loop to add all the environment variables. In this scenarios, the EnvVars key names "VAR1, VAR2" are unknown to the receiving template, as such I need a looping mechanism

```yaml
# Steps.yml

parameters:
    EnvVars: []

steps:
  - task: PowerShell@2
    displayName: 'Execute PowerShell Script'
    enabled: true
    timeoutInMinutes: ${{ parameters.Timeout }}
    inputs:
        targetType: 'filePath'
        filePath: ${{ parameters.ScriptPath }}
        pwsh: ${{ parameters.pwsh }}
        env:
        - ${{ each Var in parameters.EnvVars }}: # What is the correct syntax for this
            ${{ Var }} # And this?
```

What is the correct syntax for the above? or is there a better method I should be using?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cshell#expansion-of-variables)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**
