### ISSUE TITLE
Conditional insertion based on boolean parameter always inserts even when parameter is false

### ISSUE THREAD

**Issue by asottile** [MicrosoftDocs/vsts-docs#3577]
This is simplified from a [concrete example](https://github.com/asottile/azure-pipeline-templates/blob/2dbaf69cd7f99dcc02e6da598f0913f7bfebf552/job--python-tox.yml#L70-L76)

(completely untested, though I hope it's valid syntax)

```yaml
parameters:
    bool_param: true

jobs:
- job: ${{ format('t_{0}', parameters.bool_param }}
  steps:
  - ${{ if parameters.bool_param }}:
    - script: echo it was true
```

```yaml
- template: t.yml
- template: t.yml
  parameters:
    bool_param: false
```

Workaround:

This appears to work, but I don't know why

```yaml
  - ${{ if eq(parameters.bool_param, true) }}:
    # ...
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6724abea-bbdc-bf66-ed5e-3214fa6c3e66
* Version Independent ID: 4f8dab21-3f0e-da32-cc0e-1d85c13c0065
* Content: [Job and step templates - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops)
* Content Source: [docs/pipelines/process/templates.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/templates.md)
* Product: **devops**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **alewis**
