### ISSUE TITLE
Passing environment variables as parameters

### ISSUE THREAD

**Issue by MAHDTech** [MicrosoftDocs/vsts-docs#3579]
Hi,

The documented example example indicates that a mapping of environment variables can be used.

```yaml
env:  # mapping of environment variables to add
```

Is it possible to parameterise this by passing a mapping, as I cannot get this to work based on the example docs.

For example;

```yaml
# StepTemplate.yml

parameters:
    PassedVariables: {}

steps:
    - task: PowerShell@2
     # snip #
        inputs:
            targetType: 'filePath'
            filePath: MyExampleScript.ps1
            env:
            ${{ insert }}: ${{ parameters.PassedVariables }}
```

```yaml
# EntryPoint.yml
jobs:
  - job: MyTestJob
    # snip
    - template: StepTemplate.yml
        variables:
            SomeVariable: 'This is an example variable'
        parameters:
            PassedVariables:
                Var1: 'Hello World'
                Var2: $(SomeVariable)
```

The issue I am having is, I was expecting that when I run my script I can echo the $ENV:XXX variable but it doesn't seem to work correctly, probaly an ID10T error but where am I going wrong?

```PowerShell
# MyExampleScript.ps1
Write-Host "$ENV:Var1 $ENV:Var2" # Doesnt work :(
Write-Host "$Var1 $Var2" # I never expected this to work but tried anyways
```

Apologies for the short example, hopefully makes sense, otherwise I can expand upon it later.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0e444c2-69c6-4d71-6fd0-94d0f4097d3a
* Version Independent ID: 3a727833-1cc3-c2fb-c5b3-22605eee2721
* Content: [PowerShell task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/powershell?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/powershell.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/powershell.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vtbassmatt** [comment]
I think you're really close, just have a syntax problem with `env` -- it's a peer of `inputs`. Here's what worked for me:

```yaml
# azure-pipelines.yml
steps:
- checkout: none
- template: template.yml
  parameters:
    PassedVariables:
      Var1: 'Hello World'
      Var2: 'Foo bar'


# template.yml
parameters:
  PassedVariables: {}

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Get-ChildItem Env:
  env:
    ${{ insert }}: ${{ parameters.PassedVariables }}

```
