### ISSUE TITLE
Difference between variables['variableName'] and $(variableName)

### ISSUE THREAD

**Issue by amirschw** [MicrosoftDocs/vsts-docs#3695]
Can you please explain the difference between the two? I was using the $() format until now, but recently encountered a problem when sending a variable as a parameter to a template like this: $(variableName). Sending it using variables['variableName'] worked.

Example:
```
# File: templates/steps-with-params.yml
parameters:
  publishToFeed: 'false'

steps:
- ${{ if eq(parameters.publishToFeed, 'true') }}:
  - task: PkgESNuGetPublisher@0
    inputs: ...
```

This does not work:
```
# File: azure-pipelines.yml

variables:
  publishToFeed: 'true'

steps:
- template: templates/steps-with-params.yml
  parameters:
    publishToFeed: $(publishToFeed)
```

While this works:
```
# File: azure-pipelines.yml

variables:
  publishToFeed: 'true'

steps:
- template: templates/steps-with-params.yml
  parameters:
    publishToFeed: ${{ variables['publishToFeed'] }}
```

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**
