### ISSUE TITLE
Examples using $() syntax are confusing

### ISSUE THREAD

**Issue by vtbassmatt** [MicrosoftDocs/vsts-docs#3777]
Since $() is one of the ways to reference variables in Bash, this can be confusing, especially given our upper-case/replace-'.' behavior. Make the examples more clear.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#share-variables-across-pipelines)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by julie-ng** [comment]
I needed this in order to include the git sha in my docker image tags e.g.: `67-ba75256` where 67 is the build number. 

I agree, the `''` syntax is weird. But I got it working through trial and error:

```
 echo '##vso[task.setvariable variable=buildSha]'$(git rev-parse --short HEAD)''
```

Fuller example:

```yaml
variables:
  imageTag: $(azureContainerRegistry)/$(Build.Repository.Name):$(Build.BuildId)

steps:
- script: |
    echo '##vso[task.setvariable variable=buildSha]'$(git rev-parse --short HEAD)''
    echo '$(buildSha) variable set'
  displayName: set build sha variable

- script: docker build --tag $(imageTag)-$(buildSha) .
  displayName: build and tag image
```

**Comment by vtbassmatt** [comment]
Note for anyone else reading along: the fuller example echos literally `$(buildSha) variable set` which, given the single quotes, is probably what @julie-ng wanted. `setVariable` doesn't update rgw current environment, just subsequent processes, and this confuses lots of people.

For anyone reading this who wants to echo the buildSha in the same step, I use a pattern like this:
```yaml
steps:
- script: |
    buildSha=$(git rev-parse --short HEAD)
    echo "##vso[task.setvariable variable=buildSha]$buildSha"
    echo "$(buildSha) variable set"   # this will echo the actual SHA
  displayName: set build sha variable
```

**Comment by julie-ng** [comment]
Actually that didn't echo the acutal SHA for me either 🤷‍♀️
https://dev.azure.com/julie-ng/demos/_build/results?buildId=78

Not a big deal. But definitely awkward syntax.

**Comment by vtbassmatt** [comment]
Thank you!  🤦‍♂️ this is why I should test scripts before I post them. The problem is that `$()` in Bash means "execute this command and return the output as a string." Corrected:
```yaml
steps:
- script: |
    buildSha=$(git rev-parse --short HEAD)
    echo "##vso[task.setvariable variable=buildSha]$buildSha"
    echo "$buildSha variable set"   # this will echo the actual SHA
  displayName: set build sha variable
```
