### ISSUE TITLE
Expansion of variables in resources -> containers -> image

### ISSUE THREAD

**Issue by kbakk** [MicrosoftDocs/vsts-docs#3818]
I am trying to set up a pipeline (below) where I in the first job build an image, that is tagged with branch+commit hash+build no. This works as expected. However, in the test step I would like to use this image - but this fails - it seems like the variable in resources doesn't expand - from the output log:

```
##[command]/usr/bin/docker pull eu.gcr.io/$[ variables['buildImage'] ]
```

Is this possible to achieve? I would not like to push with a static image tag ("latest" or similar), as that will not guarantee that the test job uses the correct image. 

```yaml
variables:
  - group: docker registry
  - name: dockerRegistry
    value: eu.gcr.io
  - name: imageName
    value: company/my-project
  - name: buildImageTag
    value: $[ format('{0}-{1}', variables['Build.SourceBranchName'], variables['Build.SourceVersion']) ]
  - name: buildImage
    value: $[ format('{0}/{1}:{2}', variables['dockerRegistry'], variables['imageName'], variables['buildImageTag']) ]

resources:
  containers:
  - container: build_image
    image: $[ variables['buildImage'] ]
    endpoint: my-endpoint

jobs:
  - job: build
    pool:
      vmImage: ubuntu-16.04
    steps:
      - script: |
          echo $pswd | docker login --username _json_key --password-stdin https://$(dockerRegistry)
          docker build -t $(buildImage) .
          docker push $(buildImage)
        env:
          pswd: $(dockerPassword)

  - job: test
    dependsOn:
      - build
    pool:
      vmImage: ubuntu-16.04
    container: build_image
    steps:
      - script: printenv
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#feedback)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**
