### ISSUE TITLE
Dependency output expansion in matrix definition

### ISSUE THREAD

**Issue by bobvandevijver** [MicrosoftDocs/vsts-docs#3837]
The example about output variable expansion in a job matrix does not work. I've copied the exact example, but added an env step to verify the variable. The result was `SOME_VARIABLE=$[ dependencies.A.outputs['a_step.a'] ]`. Expansion does work when not used in a job matrix though.

``` 
jobs:
  - job: A
    steps:
      - powershell: echo "##vso[task.setvariable variable=a;isOutput=true]10"
        name: a_step

  # Map the variable into job B
  - job: B
    dependsOn: A
    strategy:
      matrix:
        x:
          some_variable: $[ dependencies.A.outputs['a_step.a'] ]
    steps:
      - bash: env #SOME_VARIABLE is not expanded correctly
``` 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?tabs=yaml%2Cbatch&view=azure-devops#feedback)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**
