### ISSUE TITLE
Can we set up pool with both private and microsoft managed?

### ISSUE THREAD

**Issue by trajano** [MicrosoftDocs/vsts-docs#3843]
Can we have it so that the build can use the pool of both microsoft managed and private ones in a single YAML?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#pool)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
You can assign different jobs to different pools:

```yaml
jobs:
- job: hostedbuild
  pool:
    vmImage: ubuntu-latest
  steps:
  - script: echo I run on hosted
- job: privatebuild
  pool: Default
  steps:
  - script: echo I run on the Default (private) pool
```

But you can't mix and match hosted agents with self-hosted.
