### ISSUE TITLE
Wrong VMImage for xamarin android

### ISSUE THREAD

**Issue by RaymsDev** [MicrosoftDocs/vsts-docs#3859]
When you create new pipeline for Xamarin Android in Azure DevOps, azure-pipelines.yaml the vmImage is ''MacOS".

```yaml
# Xamarin.Android
# Build a Xamarin.Android project.
# Add steps that test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin

trigger:
- master

pool:
  vmImage: 'macOS-10.13'
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c45a95ce-73c8-861e-f92d-a26f1667aa60
* Version Independent ID: ecb82128-cdf4-3834-62c1-2cf61989ab5e
* Content: [Build Xamarin apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/xamarin?view=azure-devops#feedback)
* Content Source: [docs/pipelines/languages/xamarin.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/languages/xamarin.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**
