### ISSUE TITLE
Are variables supposed to work for the artifactName input?

### ISSUE THREAD

**Issue by seangwright** [MicrosoftDocs/vsts-docs#3896]
I tried to set the `artifactName` using a variable

```yml
- task: PublishPipelineArtifact@0
  displayName: 'Publish Pipeline Artifact'
  inputs:
    artifactName: '$(Build_DefinitionName)'
    targetPath: '$(Build.ArtifactStagingDirectory)'
```

Is this supposed to work? If I'm not supposed to use a variable here how is the `artifactName` supposed to help me in identifying an artifact? Does it not matter that it won't have a unique name across many different builds or that it won't have a unique identifier across a single build pipeline?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41baa0b5-175c-a697-4b7d-c150259c6e6b
* Version Independent ID: 75085b15-1acc-526a-0495-74a13c42c1d5
* Content: [Publish Pipeline Artifacts task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-pipeline-artifact?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/publish-pipeline-artifact.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/publish-pipeline-artifact.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @mitchdenny
* Microsoft Alias: **midenn**
