### ISSUE TITLE
Explain how I can use a strategy that does not always use containers

### ISSUE THREAD

**Issue by Naatan** [MicrosoftDocs/vsts-docs#3921]
I want to do something like this:

```
strategy:
  matrix:
    linux:
      imageName: ubuntu-16.04
      containerImage: my-image
    mac:
      imageName: macos-10.13
    windows:
      imageName: vs2017-win2016

pool:
  vmImage: $(imageName)

container: $[ variables['containerImage'] ]
```

Only Linux should use a container, the others should not (particularly mac, which doesn't support containers). How am I meant to do this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3339a2e0-be29-1363-f588-b231d4472c02
* Version Independent ID: 72dd11a3-704d-d0fd-6dfa-cf49f3352de3
* Content: [Container Jobs in Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/process/container-phases.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/container-phases.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **macoope**
