### ISSUE TITLE
Job dependency on output variables is not working

### ISSUE THREAD

**Issue by thomasmktong** [MicrosoftDocs/vsts-docs#3955]
Hi. With the following yaml, my expected result would be only running the job `TypeScript` but not `DotNet`, but end up both jobs have run. Did I make anything wrong?

```
trigger: none
resources: [{ repo: self }]

jobs:
- job: PRDifferences
  displayName: Get PR Differences

  steps:    
  - powershell: |  
       $diff_frontend = 10
       $diff_backend = 0
       
       Write-Host "##vso[task.setvariable variable=difffrontend;isOutput=true]$diff_frontend"
       Write-Host "##vso[task.setvariable variable=diffbackend;isOutput=true]$diff_backend"
    displayName: 'Detect front/back end changes'

- job: DotNet
  dependsOn: PRDifferences
  condition: ne(dependencies.PRDifferences.outputs['diffbackend'], '0')

  steps:
  - script: "back end as changed, do back end build"

- job: TypeScript
  dependsOn: PRDifferences
  condition: ne(dependencies.PRDifferences.outputs['difffrontend'], '0')

  steps:
  - script: "front end as changed, do front end build"
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f151218-9a11-0078-e038-f96198a76143
* Version Independent ID: 09c4d032-62f3-d97c-79d7-6fbfd89910e9
* Content: [Conditional tasks - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/process/conditions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/conditions.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by VitorRigoni** [comment]
The way this works for me is by giving the powershell task a name and referencing it by it's name in the other jobs:

```yaml
trigger: none
resources: [{ repo: self }]

jobs:
- job: PRDifferences
  displayName: Get PR Differences

  steps:
  - task: PowerShell@2
    inputs:
    script: |  
       $diff_frontend = 10
       $diff_backend = 0
       
       Write-Host "##vso[task.setvariable variable=difffrontend;isOutput=true]$diff_frontend"
       Write-Host "##vso[task.setvariable variable=diffbackend;isOutput=true]$diff_backend"
    displayName: 'Detect front/back end changes'
    name: 'detectChanges'

- job: DotNet
  dependsOn: PRDifferences
  condition: ne(dependencies.PRDifferences.outputs['detectChanges.diffbackend'], '0')

  steps:
  - script: "back end as changed, do back end build"

- job: TypeScript
  dependsOn: PRDifferences
  condition: ne(dependencies.PRDifferences.outputs['detectChanges.difffrontend'], '0')

  steps:
  - script: "front end as changed, do front end build"
```
