### ISSUE TITLE
DotNetCoreCLI `pack` ignores include-symbols and include-source via arguments.

### ISSUE THREAD

**Issue by kieronlanning** [MicrosoftDocs/vsts-docs#4075]
Using the `DotNetCoreCLI` task with the `pack` command ignores the `arguments` property containing `include-source` and `include-symbols`.

Example:
```
- task: DotNetCoreCLI@2
  displayName: 'NuGet: Create packages'
  condition: succeeded()
  inputs:
    command: 'pack'
    configurationToPack: $(buildConfiguration)
    versioningScheme: byBuildNumber
    verbosityPack: Detailed
    modifyOutputPath: true
    packDirectory: '$(build.artifactstagingdirectory)/dropartifacts/'
    arguments: --include-symbols --include-source
```
