### ISSUE TITLE
Show script output

### ISSUE THREAD

**Issue by mchelen** [MicrosoftDocs/vsts-docs#4125]
When a script runs, the success or failure is recorded but no output is shown in the logs. Is there any way to see this output?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36fff5ec-d766-b589-39ff-9c69ab26dd5b
* Version Independent ID: 12deb045-2511-b5bf-9e41-0d223bef516b
* Content: [Shell Script task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/shell-script?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/shell-script.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/shell-script.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
All output to stdout and stderr ends up in the logs. If you have an example where this isn't happening, I'd be happy to take a look.

**Comment by mchelen** [comment]
@vtbassmatt Hmm maybe it's surpressing STDOUT when STDERR exists?
Here is an [example pipeline](https://dev.azure.com/mchelen-test/example/_build/results?buildId=13), the "Register Snapshot" task looks like this:

```yaml
- script: |
    curl -X PUT "http://localhost:9200/_snapshot/backups" -H "Content-Type:application/json" -d'{"type":"fs", "settings":{"location":"snapshots"}}'
  displayName: Register Snapshot
```
It should return `{"acknowledged":true}` or some error, but no output like this can be seen in the log.
