### ISSUE TITLE
Conditional install?

### ISSUE THREAD

**Issue by af4jm** [MicrosoftDocs/vsts-docs#4153]
If we specify a version that is already installed, will this step recognize that and skip reinstalling, or do we need a guard script?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9660c58-3366-f1be-8380-d6cf1d3c0150
* Version Independent ID: 226a4fd8-bce8-3333-d8d6-7af933c7b060
* Content: [.NET Core Tool Installer task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/dotnet-core-tool-installer?view=azure-devops)
* Content Source: [docs/pipelines/tasks/tool/dotnet-core-tool-installer.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/tool/dotnet-core-tool-installer.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @pulkitaggarwl
* Microsoft Alias: **puagarw**

**Comment by hiyadav** [comment]
If that version was installed in the installation path by the same task, it recognizes it and skips installation. Whereas, if the version was manually installed or installed in some other way, the task overrides that version.

If you're using the default installation path (agents tool directory) with a private agent, the installation of the version will only happen once, and will be skipped for consecutive runs. (given the version doesn't gets deleted from agents tool directory)

**Comment by af4jm** [comment]
What I'm trying to do is specify a specific SDK version to build with, whether Microsoft has it pre-installed or not

this is how I'm doing it currently (only relevant parts shown, but following steps include _dotnet restore, build, test, & publish_)... was hoping the change from *DotNetCoreInstaller@0* to *UseDotNet@2* would make the *pwsh* step unnecessary (& the condition on *UseDotNet*)
```
    variables:
        SdkVersion: '2.2.203'

    steps:
    -   pwsh: |
            $found = (Test-Path -Path "$(Agent.ToolsDirectory)\dotnet\sdk\${env:SdkVersion}")
            Write-Host -Object ".NET Core SDK ${env:SdkVersion}: $(If (${found}) {'found'} Else {'NOT found'})"
            Write-Host -Object "##vso[task.setvariable variable=NeedsSdk]$(If (${found}) {'0'} Else {'1'})"
        name: 'Test_CoreSdk'
        displayName: 'Check if .NET Core SDK $(SdkVersion) is installed'
        env:
            SdkVersion: $(SdkVersion)

    -   task: UseDotNet@2
        name: 'Install_CoreSdk'
        displayName: 'Install .NET Core SDK $(SdkVersion), if necessary'
        inputs:
            packageType: 'sdk'
            version: $(SdkVersion)
            installationPath: $(Agent.ToolsDirectory)/dotnet
        condition: ne(variables['NeedsSdk'], '0')
```

**Comment by hiyadav** [comment]
So, as I understood, you're trying to avoid re-downloading and installation of a version if it is already present in agents.toolsdirectory... 

Gladly, we are taking care of that in the new UseDotNetV2 task. Hence, when the version is once installed in agents.toolsdirectory on a private agent, the task will honor that and skip downloading. Thus you will not required pwsh step.

_However, kindly note that anything downloaded in the hosted agent during one pipeline/build/release, is not available in consecutive runs. Hence, in hosted agents, the version is downloaded every time._

**Comment by af4jm** [comment]
right... so I'm hoping that when MSFT's monthly update adds 2.2.203, the UseDotNet step will skip the install, since it will become redundant, and just do the "use that one!" part

I don't think the hosted agent applies to my specific case...
```yaml
stages:
-   stage: 'CI_build'
    jobs:
    -   job: 'CI_build'
        pool:
            name: Hosted Windows 2019 with VS2019
```
