### ISSUE TITLE
Setting parameters when using stages

### ISSUE THREAD

**Issue by cwoolum** [MicrosoftDocs/vsts-docs#4246]
Is it possible to set parameters for stages? I am using a template for my build but would like to share the parameters across stages. My syntax might just be wrong.

```
resources:
  repositories:
    - repository: templates
      type: git
      ref: refs/heads/release/1.1
      name: BuildTemplates

trigger:
  branches:
    include:
    - master
    - release/*

parameters:
  services:
  - version: $(Build.BuildNumber)
    dockerfileName: 'Dockerfile.Api'
    tagName: 'myacr.azurecr.io/myapi.api'
    generatesMigration: true
  - version: $(Build.BuildNumber)
    dockerfileName: 'Dockerfile.InternalApi'
    tagName: 'myacr.azurecr.io/myapi.internalapi'
  - version: $(Build.BuildNumber)
    dockerfileName: 'Dockerfile.PlaceIndexer'
    tagName: 'myacr.azurecr.io/myapi.indexer'

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - template: templates/MicroServices/build.yml@templates
    parameters: ${{ parameters }}
  
- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  jobs:
  - ${{ each service in parameters.services }}:   
    - deployment: Deploy
      displayName: Deploy ${{ service.tagName }}
      pool:
        vmImage: Hosted Ubuntu 1604
      environment: 'staging'
      strategy:
        runOnce:
          deploy:
            steps:
            - task: DownloadPipelineArtifact@1
              inputs:
                artifactName: 'manifests'
                downloadPath: '$(System.ArtifactsDirectory)/manifests'
            # Some other tasks           
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6724abea-bbdc-bf66-ed5e-3214fa6c3e66
* Version Independent ID: 4f8dab21-3f0e-da32-cc0e-1d85c13c0065
* Content: [Job and step templates - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#feedback)
* Content Source: [docs/pipelines/process/templates.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/templates.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
Parameters are completely consumed after template compilation, so they work for stage templates as well. I'd have to see your outer, containing pipeline as well to see what's happening.

**Comment by cwoolum** [comment]
This is the outer pipeline. I was going to use variables like so:

```
parameters:
  services:
  - version: $(Build.BuildNumber)
    dockerfileName: 'Dockerfile.Api'
    tagName: 'myacr.azurecr.io/myapi.api'
    generatesMigration: true
  - version: $(Build.BuildNumber)
    dockerfileName: 'Dockerfile.InternalApi'
    tagName: 'myacr.azurecr.io/myapi.internalapi'
  - version: $(Build.BuildNumber)
    dockerfileName: 'Dockerfile.PlaceIndexer'
    tagName: 'myacr.azurecr.io/myapi.indexer'
```

but that seemed wrong. Ideally, I need to pass that config into both stages.

**Comment by vtbassmatt** [comment]
Oh, I see. You want to specify the parameters once and pass them to two different templates. That's not easy to achieve with parameters (which are designed for re-using logic with different inputs, not re-using inputs with different logic 😄).

You can kind of simulate using multiple layers of templates. It's ugly, but if you want to `${{ each }}` over it, it's your only viable option. (We offer variable templates, but variables are strings so you don't get the key/value stuff that you're using from parameters.)

Something like:

```yaml
# azure-pipelines.yml
stages:
- template: outer-template.yml
  parameters:
    services:
    - version: $(Build.BuildNumber)
      dockerfileName: 'Dockerfile.Api'
      tagName: 'myacr.azurecr.io/myapi.api'
      generatesMigration: true
    - version: $(Build.BuildNumber)
      dockerfileName: 'Dockerfile.InternalApi'
      tagName: 'myacr.azurecr.io/myapi.internalapi'
    - version: $(Build.BuildNumber)
      dockerfileName: 'Dockerfile.PlaceIndexer'
      tagName: 'myacr.azurecr.io/myapi.indexer'
```

```yaml
# outer-template.yml
parameters:
  services: {}

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - template: templates/MicroServices/build.yml
    parameters:
      services: ${{ parameters.services }}
  
- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  jobs:  
  - template: templates/MicroServices/deploy.yml
    parameters:
      services: ${{ parameters.services }}
```

```yaml
# deploy.yml
parameters:
  services: {}

jobs:
- ${{ each service in parameters.services }}:   
  - deployment: Deploy
    displayName: Deploy ${{ service.tagName }}
    pool:
      vmImage: Hosted Ubuntu 1604
    environment: 'staging'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@1
            inputs:
              artifactName: 'manifests'
              downloadPath: '$(System.ArtifactsDirectory)/manifests'
          # Some other tasks
```

This is a great scenario, and one that we'll think about as we evolve the language. It's not exactly a doc bug, so I'll go ahead and close it now.
