### ISSUE TITLE
Dependent stage not firing execution

### ISSUE THREAD

**Issue by lusocoding** [MicrosoftDocs/vsts-docs#4251]
I've configured a multi stage pipeline with 4 stages but for some reason it only fires the build and the first deployment stage, while the others remain in a waiting state. 

There is no difference between the jobs defined in the various deployment stages, except for some renaming on variables to identify the correct environment.

One other thing I noticed is that in the detail page of the execution, only the first two stages are side by side. QA and UAT are below (graphically speaking) and there's no line connecting QA and DEV.

The below yaml is taken from the configuration to help identify the cause of the issue.

``` yaml
stages:

- stage: Build
  displayName: "Build Artefacts"
  jobs: (...)

- stage: DeployDev
  dependsOn: Build
  displayName: "DEV Deployment"
  jobs: (...)

- stage: DeployQA
  displayName: "QA Deployment"
  dependsOn: DeployDEV
  jobs: (...)

- stage: DeployUAT
  displayName: "UAT Deployment"
  dependsOn: DeployQA
  jobs: (...)
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4266f72c-c774-0046-4593-d01eb775d3c3
* Version Independent ID: f20827aa-a6c5-96a8-5969-e576ffbc2e38
* Content: [Stages in Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/stages?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/process/stages.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/stages.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**
