### ISSUE TITLE
How to use ${{ parameters.paramName }} inside expressions?

### ISSUE THREAD

**Issue by EM1L** [MicrosoftDocs/vsts-docs#4252]
for example I have the following condition in a step inside a template and the template takes a bolean parameter value:

    condition: and(succeeded(), &lt;?how-to-ref-param-value?&gt;)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c58a78-a567-e99a-9eb7-62dddd1b90b6
* Version Independent ID: 680a79bc-11de-39fc-43e3-e07dc762db18
* Content: [Expressions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops)
* Content Source: [docs/pipelines/process/expressions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/expressions.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by satrapu** [comment]
Short version: ${{ parameters.Name_1.Name_2...Name_N }}
Long version:  
I have defined several parameters:
```yaml
parameters:
  job:
    name: ''
    displayName: ''
  pool: ''
  containers:
    db4it: ''
  build:
    configuration: 'Release'
  sonar:
    enabled: True
    buildBreaker:
      enabled: True
```
  
And this is how I use them in a 'condition':
```yaml
- task: PowerShell@2
    name: sonar_build_breaker
    displayName: Run Sonar build breaker
    condition: |
      and
      (
          succeeded()
        , eq( ${{ parameters.sonar.enabled }}, True)
        , eq( ${{ parameters.sonar.buildBreaker.enabled }}, True)
      )
    inputs:
      targetType: 'filePath'
      filePath: '$(Build.SourcesDirectory)/Build/SonarBuildBreaker.ps1'
      arguments: >-
        -SonarToken "$(CurrentProject.Sonar.Token)" 
        -DotSonarQubeFolder "$(Agent.BuildDirectory)/.sonarqube"
      errorActionPreference: stop
      failOnStderr: True
      workingDirectory: $(Build.SourcesDirectory)
```

The whole pipeline can be found here: https://github.com/satrapu/aspnet-core-logging/blob/master/Build/azure-pipelines.job-template.yml
