### ISSUE TITLE
Deployment Job Demands are not working

### ISSUE THREAD

**Issue by geofflamrock** [MicrosoftDocs/vsts-docs#4265]
Hi, 

We are using deployment jobs inside a multi-stage yaml pipeline and are having an issue getting demands to work for a deployment job. 

If I specify a demand in a normal job such as

```
- stage: Build
  jobs:
    - job: Build
      pool:
        name: Local
        demands:
          - docker
```

it works fine and the correct agent will run the job, however using deployment jobs such as

```
- stage: Deploy
  jobs:
    - deployment: Internal
      pool:
        name: Local
        demands: 
          - docker
```

doesn't seem to work, as an agent that doesn't have docker installed is getting picked to run the deployment and the deployment fails.

Are demands supported in deployment jobs the same way as normal jobs (as the documentation seems to indicate)?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5aeeaace-1c5b-a51b-e41f-f25b806155b8
* Version Independent ID: fd7ff690-b2e4-41c7-a342-e528b911c6e1
* Content: [Deployment jobs - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs?view=azure-devops)
* Content Source: [docs/pipelines/process/deployment-jobs.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/deployment-jobs.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @shashankbarsin
* Microsoft Alias: **shasb**

**Comment by chshrikh** [comment]
@geofflamrock demands support in deployment jobs we have added recently, could you please see if it is working for you now

**Comment by geofflamrock** [comment]
@chshrikh thanks, it seems to be working now.

**Comment by praveendath92** [comment]
We are facing the same issue. It picks an agent from the correct pool but demands are not being met. 

Our usage looks like this

```
- deployment: PublishStuff
  displayName: 'Publish Stuff'
  pool:
    name: OurPool
    demands:
    - AGENT_ENV -equals prod
    - AGENT_TYPE -equals stuff
  environment: 'Stuff environment'
```

The selected agent is from the correct pool but the demands are not met. The exact same spec on a non deployment job working fine
