### ISSUE TITLE
Reference predefined variables in custom variables

### ISSUE THREAD

**Issue by xuhongxu96** [MicrosoftDocs/vsts-docs#4283]
I have a variable `TAG`, which content is predefined variable: `$(Build.RequestedForId)`.

```yaml
variables:
- name: TAG
  value: $(Build.RequestedForId)
```

In commands, `TAG` could be correctly converted to the final value (i.e. the value of the predefined variable).
However, in `displayName`, it couldn't.

E.g.

```yaml
steps:
- bash: docker build -t test:$(TAG) -f Dockerfile .
  displayName: 'docker build test:$(TAG)'
  workingDirectory: $(Build.SourcesDirectory)
```

The scripts running in bash is correct:
`docker build -t test:xxx -f Dockerfile .`

But the display name of the step is wrong:
`docker build test:$(Build.RequestedForId)`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Predefined variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**
