### ISSUE TITLE
Dynamic Iterative Insertion

### ISSUE THREAD

**Issue by tiny-dancer** [MicrosoftDocs/vsts-docs#4312]
Is there an example that could be provided on how to do the iterative insertion based on a list of jobs dynamically set from a prior step?

Ie. Instead of Job A and Job B known declaratively, they need to be retrieved from a database. Depending on point in time of execution it may run Job A - Z or simply Job A and B.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6724abea-bbdc-bf66-ed5e-3214fa6c3e66
* Version Independent ID: 4f8dab21-3f0e-da32-cc0e-1d85c13c0065
* Content: [Job and step templates - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#feedback)
* Content Source: [docs/pipelines/process/templates.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/templates.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
Yes, this would be cool. I need to spend some time to get the syntax just right before I put it in docs, but (from memory, untested) it goes something like this:

```yaml
jobs:
- job: generator
  steps:
  - bash: echo "##vso[task.setVariable variable=legs;isOutput=true]{'matrix':{'a':{'myvar':'A'}, 'b':{'myvar':'B'}}}"
    name: mtrx
- job: runner
  dependsOn: generator
  strategy: $[ dependencies.generator.mtrx.outputs['legs'] ]
  steps:
  - script: echo $(myvar) # will be 'A' in job 'a' and 'B' in job 'b'
```

The idea is to offer up a stringified-JSON representing the matrix legs in an output variable.
