### ISSUE TITLE
Error referencing step templates on a multi stage YAML pipeline

### ISSUE THREAD

**Issue by lusocoding** [MicrosoftDocs/vsts-docs#4358]
Trying to leverage the new features on Azure DevOps in conjunction with job and step templates for better organize the pipelines code. Currently I'm getting the below error when trying to run the pipeline:

> "An error occurred while loading the YAML build pipeline. Unable to cast object of type 'Microsoft.TeamFoundation.DistributedTask.Pipelines.TaskTemplateStep' to type 'Microsoft.TeamFoundation.DistributedTask.Pipelines.TaskStep'."

Is there any way to use the step templates with the new multi stage YAML pipeline definitions?

Below the templates that are currently in use:

``` yaml
# pipeline-master.yaml

name: $Date:yyyMMdd)Rev$(Rev:.r)

trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md

stages:
- stage: Build
  displayName: "Build Stage"
  jobs:
  - job: BuildJob
    pool:
      vmImage: windows-2019
    steps:
    - template: templates/steps/build-job-steps.yaml
      parameters:
        echo: Hello Build Stage

- stage: Deployment
  dependsOn: Build
  displayName: "Deployment Stage"
  jobs:
  - deployment: DeploymentJob
    pool:
      vmImage: windows-2019
    environment: az-devops-pipelines-yaml
    strategy:
      runOnce:
        deploy:
          steps:
          - template: templates/steps/deploy-job-steps.yaml
            parameters:
              echo: Hello Deployment Stage
```

``` yaml
#templates/steps/build-job-steps.yaml

parameters:
  echo: Parameter Not Given

steps:
  - task: PowerShell@2
    displayName: "Write Echo to Host"
    inputs:
      pwsh: true
      targetType: inline
      script: Write-Host "Build Steps say:" ${{ parameters.echo }}
```

``` yaml
# templates/steps/deploy-job-steps.yaml

parameters:
  echo: Parameter Not Given

steps:
  - task: PowerShell@2
    displayName: "Write Echo to Host"
    inputs:
      pwsh: true
      targetType: inline
      script: Write-Host "Deployment Steps say:" ${{ parameters.echo }}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6724abea-bbdc-bf66-ed5e-3214fa6c3e66
* Version Independent ID: 4f8dab21-3f0e-da32-cc0e-1d85c13c0065
* Content: [Job and step templates - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops)
* Content Source: [docs/pipelines/process/templates.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/templates.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**
