### ISSUE TITLE
where is yaml syntax?

### ISSUE THREAD

**Issue by katlimruiz** [MicrosoftDocs/vsts-docs#4362]
where is yaml syntax?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1c633b9-c8b2-e05d-de2c-7754894d28fd
* Version Independent ID: df031b76-0fe7-e138-dd36-2736757a97fd
* Content: [Manual Intervention task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/manual-intervention?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/manual-intervention.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/manual-intervention.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by RoopeshNair** [comment]
Manual Intervention is not supported in YAML pipeline. We haven't closed on the design, unfortunately no time-line that can be shared at this point in time. We will continue to track it

**Comment by rjminchuk** [comment]
It's been a few months, so I was wondering if there are details that can be shared about this now. Is there a time-line for this yet? There are seemingly no stage Gates/Approvals or Manual Interventions tasks for yaml release pipelines at the time of this writing.

**Comment by katlimruiz** [comment]
Good news, it is there and . I am using it already.

**Comment by rjminchuk** [comment]
Would you share your YAML? I'm trying this in a yaml pipeline (not a classic Release pipeline), but it's not working..

```
...
- stage: 'Gate_for_QA'
  dependsOn: 'Deploy_to_Dev'
  jobs:
  - job:
    pool: 'server'
    steps:
    - task: ManualIntervention@8
      displayName: 'Baseline Smoke Test in QA'
      inputs:
        instructions: 'my instructions.'
        emailRecipients: '["84cdwfd..........d385014314"]'
- stage: 'Deploy_to_QA'
  dependsOn: 'Gate_for_QA'
  jobs:
  - job:
    pool: 'my_agent_pool'
    steps: 
    - bash: echo 'deploy to qa1'
```

I copied the ManualIntervention@8 tasks yaml out of a classic release pipeline and set it to run on the "server," but I receive the following error message:

`Gate_for_qa:Job: "Task execution section of task definition for ID: bcb64569-d51a-4af0-9c01-ea5d05b3b622 is either missing or not valid."`

I also tried the task from an agent running in my own agent pool, but received a different error.

**Comment by RoopeshNair** [comment]
As I mentioned earlier, Manual Intervention is not supported in YAML pipelines yet. We have it on our backlog. tentatively 4-5 months based on current priorities. We are working on issues that impact broader set of users. We will continue to monitor this.

**Comment by katlimruiz** [comment]
You need to do the following:
1. Configure an new Environment e.g. Staging (in Pipelines/Environments)
2. On the right side, click on menu, click on Checks, add one and assign specific users or groups that can approve this.
3. Your Yaml should be something like this:

```
- stage: 'Deploy_to_QA'
  jobs:
  - deployment: Deploy_to_QA
    pool: 'my_agent_pool'
    environment: Staging <<<<<< This is the key
    strategy:
      runOnce:
        deploy:
          steps:
          - bash: echo 'deploy to qa1'
```

Add the environment entity below the job (which I defined as deployment, not a regular job).

NOTE: The only downside which I already reported to MS is that when the pipeline is waiting for the check it shows In Progress so it is confusing (you will see many pipelines "running", though they are not).
Besides that it works very well.

At first it drove me off the button Add Resources, and the only thing available now is Kubernetes, so I thought it was incomplete. But then I realized that it didn't require any. The key was the Checks option that was added some months ago.
