### ISSUE TITLE
Multiple demands??

### ISSUE THREAD

**Issue by mcgov** [MicrosoftDocs/vsts-docs#4382]
There is no instruction on how to pass multiple demands. What is the seperator, also this doesn't elaborate how to set keyword arguments. Just -exists version. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7541ee6-d2bb-84c0-fead-1aa8ee7d2372
* Version Independent ID: 5cf7c51e-37e1-6c67-e6c6-80262c4eb662
* Content: [Demands - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/demands?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/process/demands.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/demands.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by dotnetcanuck** [comment]
@mcgov Thanks to the following link, I was able to figure this out. Looks like they only support `exists` and `equals` checks right now, but this is how you'd do an `equals` check:

```
jobs:
  - job: Build
    pool:
      name: Your Pool Name Here
      demands:
        - Agent.OS -equals Linux # check if agent OS == Linux
        - SomeOtherDemand # this is an exists check
```

Ref -- https://github.com/Microsoft/azure-pipelines-agent/issues/1740
