### ISSUE TITLE
How to get the Matrix Name as a Variable

### ISSUE THREAD

**Issue by RehanSaeed** [MicrosoftDocs/vsts-docs#4405]
Is there a variable I can use to get the name of the matrix e.g. in the example below, it would be Linux, Mac or Windows.

```
stages:
- stage: Build
  jobs:
  - job: Build
    strategy:
      matrix:
        Linux:
          vmImageName: 'ubuntu-latest'
        Mac:
          vmImageName: 'macos-10.13'
        Windows:
          vmImageName: 'windows-latest'
    pool:
      vmImage: $(vmImageName)
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#feedback)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**
