### ISSUE TITLE
Where are my Matrix Artifacts?

### ISSUE THREAD

**Issue by RehanSaeed** [MicrosoftDocs/vsts-docs#4407]
I'm using a matrix to run my job on Linux and Windows like so:

```
stages:
- stage: Build
  jobs:
  - job: Build
    strategy:
      matrix:
        Linux:
          matrixName: Ubuntu
          vmImageName: ubuntu-latest
        Windows:
          matrixName: Windows
          vmImageName: windows-latest
    pool:
      vmImage: $(vmImageName)
steps:
    # ...
    - task: PublishPipelineArtifact@0
      inputs:
        artifactName: $(matrixName)
        targetPath: './Artifacts'
```

In my deploy stage, I need to directory path to the Linux and Windows artifacts which are located in `/home/vsts/work/1/Linux` and `/home/vsts/work/1/Windows` respectively. Does such a variable exist? If not, then it should.

```
- stage: Deploy
  jobs:
  - deployment: AzureArtifacts
    pool:
      vmImage: ubuntu-latest
    environment: 'Azure Artifacts'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DotNetCoreCLI@2
            inputs:
              command: 'push'
              packagesToPush: '/home/vsts/work/1/Windows/*.nupkg'
              nuGetFeedType: 'internal'
              publishVstsFeed: '/64e69c35-cb00-46e4-9cba-6d8faf1f41d6'
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 861ce7a5-4fa4-55f1-2c97-46a9cc6a2f66
* Version Independent ID: bdf954b9-9bbe-8b34-b674-71ad8153519d
* Content: [Publish and consume Pipeline artifacts in builds - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/artifacts/pipeline-artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/artifacts/pipeline-artifacts.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @alexmullans
* Microsoft Alias: **amullans**
