### ISSUE TITLE
Arguments property not include when doing restore

### ISSUE THREAD

**Issue by bender2k14** [MicrosoftDocs/vsts-docs#4425]
Added this task to one of my pipelines with these properties and values, including the property `arguments` with value `--runtime win-x86`...

```
- task: DotNetCoreCLI@2
  displayName: 'Restore NuGet'
  inputs:
    command: 'restore'
    projects: './src/MySolution.sln'
    feedsToUse: 'config'
    nugetConfigPath: './NuGet.config'
    arguments: '--runtime win-x86'
```

...but this is the command that got executed on the build server:
```
/usr/bin/dotnet restore /home/vsts/work/1/s/./src/MySolution.sln --configfile /home/vsts/work/1/Nuget/tempNuGet_158.config --verbosity Detailed
```

My were the arguments not included in the executed command?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d227a6f2-a94b-1c05-57e4-b63d42e2b9e5
* Version Independent ID: d063e189-d0fd-4ca3-c108-a0bd2ae49d22
* Content: [.NET Core CLI task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/dotnet-core-cli.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/dotnet-core-cli.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @pulkitaggarwl
* Microsoft Alias: **puagarw**
