### ISSUE TITLE
retrieve 'latest' from another pipeline

### ISSUE THREAD

**Issue by rusher** [MicrosoftDocs/vsts-docs#4530]
Just so other don't block on that. If wanting to download the latest artifact from another pipeline, option "definition" not listed here has to be used. Option corresponds to the ID of the initial pipeline builder. 
Example : 
```
      - task: DownloadPipelineArtifact@1
        displayName: 'Download some artifact files'
        inputs:
          buildType: 'specific'
          project: 'f36b9048-dabc-4752-8626-cc67cd5a2a4f'
          artifactName: 'test-pipe'
          buildVersionToDownload: 'latest'
          definition: '1'
          downloadPath: $(System.DefaultWorkingDirectory)
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b03d67d0-8738-72e6-dbe7-324c1784d4fc
* Version Independent ID: bbb4d774-cd98-3ecb-7ccf-5f49e6f2b425
* Content: [Download Pipeline Artifact task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-pipeline-artifact?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/utility/download-pipeline-artifact.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/download-pipeline-artifact.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @willsmythe
* Microsoft Alias: **wismyth**
