### ISSUE TITLE
How to pass secrets

### ISSUE THREAD

**Issue by kine** [MicrosoftDocs/vsts-docs#4543]
I am missing example of how to pass secret variables as input to the template. In general they should be mapped to environment, but how it works with templates? I have e.g. Variable group with secret value, I will put this variable group in variable section of my pipeline, and now I want to pass it to the template for stage, which is using template for job...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6724abea-bbdc-bf66-ed5e-3214fa6c3e66
* Version Independent ID: 4f8dab21-3f0e-da32-cc0e-1d85c13c0065
* Content: [Job and step templates - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#passing-parameters)
* Content Source: [docs/pipelines/process/templates.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/templates.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by WilliamAntonRohm** [comment]
@kine -- thank you for contacting us with your question.  I have asked the author to look into this.  In the meantime, you might consider asking your question here: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 

@vtbassmatt -- please consider adding the requested information.

**Comment by vtbassmatt** [comment]
@kine the template processing step doesn't look at secrets or any other runtime data, it simply merges the contents of the templates into a single YAML DOM. So you use secrets the same way as you'd use them in a non-templated YAML file.

```yaml
steps:
- task: MyTask@1
  inputs:
    someInput: $(someSecret)
```

vs.

```yaml
# azure-pipelines.yml
steps:
- template: template.yml
  parameters:
    mySecretParam: $(someSecret)

# template.yml
steps:
- task: MyTask@1
  inputs:
    someInput: ${{ parameters.mySecretParam }}
```

These will compile to roughly equivalent final pipelines.

**Comment by edwin-hendriks** [comment]
Thanks to the comment of Matt (@vtbassmatt) I was able to figure out why a script of mine was not working. But in my case I also had to figure out how to pass a secret to a script. I would really like it if Microsoft would update their documenation to include at least an example of this because it is a usecase that happens all to often. Below is an adaptation of the example of Matt that includes using a secret in a script. It also includes using a variable group which contains the variable __someSecret__ (which, by the way, should have __Allow access to all pipelines__ turned off for security reasons).

```yml
# azure-pipelines.yml
variables:
- group: variable-group-containing-someSecret

steps:
- template: template.yml
  parameters:
    mySecretParam: $(someSecret)
```

```yml
# template.yml
parameters:
  - name: mySecretParam
    type: string

steps:
- task: MyTask@1
  inputs:
    someInput: ${{ parameters.mySecretParam }}

- bash: |
    someBashCommand --user someUser --password $ENV_PASSWORD
  env:
      ENV_PASSWORD: ${{ parameters.mySecretParam }} # secrets should only be given to the script in this way

- powershell: |
    somePowershellCommand --user someUser --password $env:ENV_PASSWORD
  env:
      ENV_PASSWORD: ${{ parameters.mySecretParam }} # secrets should only be given to the script in this way
```

__Note:__ the first time you run this pipeline you will have to explicitly authorize the pipeline to use the variable group. You will be prompted to do so in the Azure DevOps web frontend when you open the running pipeline. And that is of course exactly the way things should be ;-).

__PS:__ I don't think this issue is closed as long as it is not properly documented under for instance https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#secret-variables. I hope MS will do that soon.

**Comment by Winbobob** [comment]
### Closest example in the current doc
- I did lots of research and this is the closest example that I can find in the doc, [which is how to pass secrets to a task](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#secret-variables:~:text=You%20can%20also%20use%20secret%20variables%20outside%20of%20scripts.).
- Also suggested to update the doc to mention how to use secrets to a template. I could create a PR to update the doc.

### The solution I found and verified to pass secrets to a template
- I just figured out an easier way to pass secrets to a template inspired by @vtbassmatt's comment **"template processing step simply merges the contents of the templates into a single YAML DOM"**

Assume you have created the secret variable by following [this step](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/set-secret-variables?view=azure-devops&tabs=yaml%2Cbash#secret-variable-in-the-ui).

```
steps:
- task: MyTask@1
  inputs:
    someInput: $(someSecret)
```

vs.

```
# azure-pipelines.yml
steps:
- template: template.yml

# template.yml
steps:
- task: MyTask@1
  inputs:
    someInput: $(someSecret)
```
should be equivalent, which means that **you could directly use secrets in a template instead of passing them as parameters**.
