### ISSUE TITLE
ZipAlign failed with exit code 127

### ISSUE THREAD

**Issue by MakhouT** [MicrosoftDocs/vsts-docs#4562]
I am getting this error for the zipAlign step. What is wrong here?

```
##[error]Error: The process '/usr/local/lib/android/sdk/build-tools/19.1.0/zipalign' failed with exit code 127
```

This is the relevant part in my pipeline
```  
- task: AndroidSigning@2
    inputs:
      apkFiles: '**/*.apk'
      jarsign: true
      jarsignerKeystoreFile: 'production.keystore'
      jarsignerKeystorePassword: '$(keystore_password)'
      jarsignerKeystoreAlias: '$(keystore_alias)'
      jarsignerKeyPassword: '$(keystore_password)'
      zipalign: true
      apksignerArguments: --out $(Build.SourcesDirectory)/app/build/outputs/apk/release/release.apk
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b1fbcd8-d799-879e-d672-9dee164401ef
* Version Independent ID: 7208d03d-9042-7753-ab4d-d1ad8e99ef1d
* Content: [Android signing build and release task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/android-signing?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/build/android-signing.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/android-signing.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @DavidStaheli
* Microsoft Alias: **dastahel**

**Comment by WilliamAntonRohm** [comment]
@MakhouT -- Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a few options where you might consider asking your question: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

**Comment by Petrulak** [comment]
@WilliamAntonRohm I am having the same issue, I have added  following step to my build pipelin
```
steps:
  - task: AndroidSigning@3
    inputs:
      apkFiles: '**/*.apk'
      apksign: true
      apksignerKeystoreFile: 'android-signing-keystore'
      apksignerKeystorePassword: $(signing_alias_psswd)
      apksignerKeystoreAlias: $(signing_alias)
      apksignerKeyPassword: $(signing_psswd)
      apksignerArguments: --out $(Build.SourcesDirectory)/${{parameters.outFile}}
      zipalign: true
```
And pipeline  throws 
`##[error]Error: The process '/usr/local/lib/android/sdk/build-tools/19.1.0/zipalign' failed with exit code 127` . 

When I flip `zipalign: false` it works properly.
