### ISSUE TITLE
multiple "drops"

### ISSUE THREAD

**Issue by mojobec** [MicrosoftDocs/vsts-docs#4563]
I have a build pipeline with multiple steps each one for a different platform (cross-platform app).
recently it started to publish multiple drops, each one with the exact same build artifacts,
because of that my release pipeline fails with the error "Found multiple files matching "D:\a\r1\a\{BuildName}\drop\Release_Android\*-anycpu.apk"

PublishBuildArtifacts yaml for all platforms 
```
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      ArtifactName: drop
      ArtifactType: Container
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b3f565b-88e4-88d6-a534-48ec21e6e3d8
* Version Independent ID: 9fca89ae-4a6e-a43a-2834-1a91ad44c256
* Content: [Publish Build Artifacts task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-build-artifacts?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/utility/publish-build-artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/publish-build-artifacts.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @DavidStaheli
* Microsoft Alias: **dastahel**
