### ISSUE TITLE
Inline array for iterative insertion

### ISSUE THREAD

**Issue by couven92** [MicrosoftDocs/vsts-docs#4603]
Is it possible to inline the array for iterative insertion, instead of taking it from `parameters`.

For example:

``` yml
steps:
- template: steps.yml
  parameters:
    ${{ each s in ['build', 'test', 'pack', 'publish'] }}:
      ${{ s }}:
        arguments: --configuration Release ${{ parameters[s].arguments }}
```

In the example above the template would add `--configuration Release` to the `arguments` property of each of the `build`, `test`, `pack`, `publish` objects in the arguments passed to `steps.yml`.

The example above does not work, Azure DevOps complains with
```
/templates/dotnetcore/azure-pipelines.yml@templates (Line: 23, Col: 7): Exactly 3 parameter(s) were expected following the directive 'each'. Actual parameter count: 6
```

If possible, what is the syntax? If this is not currently possible, can I suggest that as a feature, where can I suggest that feature?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6724abea-bbdc-bf66-ed5e-3214fa6c3e66
* Version Independent ID: 4f8dab21-3f0e-da32-cc0e-1d85c13c0065
* Content: [Job and step templates - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#template-expressions)
* Content Source: [docs/pipelines/process/templates.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/templates.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**
