### ISSUE TITLE
How to specify the name of a matrix?

### ISSUE THREAD

**Issue by NightOwl888** [MicrosoftDocs/vsts-docs#4607]
Currently, I have:

```yml
  - strategy:
    matrix:
      Windows:
        osName: 'Windows'
        imageName: 'windows-2019'
      Linux:
        osName: 'Linux'
        imageName: 'ubuntu-16.04'
      macOS:
        osName: 'macOS'
        imageName: 'macOS-10.14'

    displayName: 'Test on $(osName)'
```

What I am wondering is whether I can remove the duplicate osName parameter just so I can get a reference to the name that is already defined in the matrix? For example:

```yml
  - strategy:
    matrix:
      Windows:
        imageName: 'windows-2019'
      Linux:
        imageName: 'ubuntu-16.04'
      macOS:
        imageName: 'macOS-10.14'

    displayName: 'Test on $(matrix.name)'
```

Is this possible? If so, can the correct syntax for this be added to the documentation? If not, consider this a feature request.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5552e8c4-b0c2-f3ff-c69a-607166afb611
* Version Independent ID: 8e73c13c-9b2b-0eac-45ec-4bd3a8d01bb1
* Content: [Create a multi-platform pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started-multiplatform?view=azure-devops)
* Content Source: [docs/pipelines/get-started-multiplatform.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/get-started-multiplatform.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**
