### ISSUE TITLE
Can't use a task with a space in its name

### ISSUE THREAD

**Issue by aholler2** [MicrosoftDocs/vsts-docs#4633]
I can't use a task that has a space in it's name. I am attempting to use the Marketplace "ARM Outputs" extension with the ARM Outputs task in my pipeline.
My YAML task:
```
- task: ARM Outputs@5
          displayName: SQLServerARMOutputs
          inputs:
            ConnectedServiceNameSelector: 'ConnectedServiceNameARM'
            ConnectedServiceNameARM: 'GIS CloudCoE POC'
            resourceGroupName: '${{ parameters.resourceGroupName }}'
            whenLastDeploymentIsFailed: 'fail'
            deploymentNameFilter: 'sql-server-w-database*'
```

My error(s) (multiple attempts):
`20190625.19: "Job Job1: Step ARM Outputs has an invalid name. Valid names may only contain alphanumeric characters and '_' and may not start with a number."`

`20190625.20: "Job Job1: Step keesschollaart.arm-outputs.arm-outputs.ARM Outputs has an invalid name. Valid names may only contain alphanumeric characters and '_' and may not start with a number."`

Please allow for spaces in the task name. This is a complete stopper for our progress.

**Comment by WilliamAntonRohm** [comment]
Thanks for the suggestion! The product teams aren’t always watching this repository, so to make sure it gets in front of them for triage, please [submit your idea]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21) here.

**Comment by aholler2** [comment]
This issue is closed, however, I wanted to clarify what the solution actually was. YAML actually does support tasks that have spaces in their names. What was happening was that YAML was implicitly creating a value for the key "name" using the task name. The fix was to instead use the task as below:
```yaml
- task: ARM Outputs@5
  name: SqlServerARMOutputs
  displayName: SQL Server ARM Outputs
  inputs:
    ConnectedServiceNameSelector: ConnectedServiceNameARM
    ConnectedServiceNameARM: $(subscriptionConnectionName)
    resourceGroupName: $(resourceGroupName)
    prefix: ''
    whenLastDeploymentIsFailed: fail
    deploymentNameFilter: sql-server-w-database*
```

Specifying "name" is key if you want to use a task that has a space in its name.
