### ISSUE TITLE
Setting a variable in environment doesn't work

### ISSUE THREAD

**Issue by AlexanderMarkov** [MicrosoftDocs/vsts-docs#4638]
I try to use $(Build.SourceBranchName) variable in the environment property:

```
  - deployment: Deploy
    environment: $(Build.SourceBranchName)
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo my first deployment
```

but get an error "Job Deploy: Resource SourceBranchName) does not exist in environment $(Build."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5aeeaace-1c5b-a51b-e41f-f25b806155b8
* Version Independent ID: fd7ff690-b2e4-41c7-a342-e528b911c6e1
* Content: [Deployment jobs - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs?view=azure-devops#feedback)
* Content Source: [docs/pipelines/process/deployment-jobs.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/deployment-jobs.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @shashankbarsin
* Microsoft Alias: **shasb**
