### ISSUE TITLE
set vs values

### ISSUE THREAD

**Issue by chaholl** [MicrosoftDocs/vsts-docs#4646]
In the 'bake' action above, the overrides description says:
```
Overrides
Override values	(Optional; Relevant if action == bake and renderType == helm2) Additional override values that are to be used via --values switch when baking manifest files using helm
```
I believe the `-set` switch is actually being used as opposed to values. It may also be worth extending the example to demonstrate how multiple overrides are used. 
```
steps:
- task: KubernetesManifest@0
  name: bake
  displayName: Bake K8s manifests from Helm chart
  inputs:
    action: bake
    helmChart: charts/sample
    overrides: |
      image.repository:nginx
      something.else:value
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72bba72b-235b-ce64-b8fd-2c6ed52a9f1f
* Version Independent ID: 2ae1b3f1-e125-a9d2-a17c-d13047d69801
* Content: [Kubernetes Manifest task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/kubernetes-manifest?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/deploy/kubernetes-manifest.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/kubernetes-manifest.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @shashankbarsin
* Microsoft Alias: **shasb**
