### ISSUE TITLE
helm release name

### ISSUE THREAD

**Issue by chaholl** [MicrosoftDocs/vsts-docs#4679]
Is there a reason why the releaseName parameter isn't specified. Seems to work just fine?

eg.
```
steps:
- task: KubernetesManifest@0
  name: bake
  displayName: Bake K8s manifests from Helm chart
  inputs:
    action: bake
    helmChart: charts/sample
    releaseName: mega-thing
    overrides: 'image.repository:nginx'
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72bba72b-235b-ce64-b8fd-2c6ed52a9f1f
* Version Independent ID: 2ae1b3f1-e125-a9d2-a17c-d13047d69801
* Content: [Kubernetes Manifest task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/kubernetes-manifest?view=azure-devops#bake-action)
* Content Source: [docs/pipelines/tasks/deploy/kubernetes-manifest.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/kubernetes-manifest.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @shashankbarsin
* Microsoft Alias: **shasb**
