### ISSUE TITLE
Add: Correct and useful info on how to get the secure file path variable

### ISSUE THREAD

**Issue by johncrim** [MicrosoftDocs/vsts-docs#4719]
This is not clear from this documentation page (found [here](https://github.com/MicrosoftDocs/vsts-docs/issues/2330) after a bunch of searching). This info should be added to this page:

To obtain the secure file path in a variable, you can use the step `name` property. The secure file path variable is `(step name).secureFilePath`.  For example:

```yaml
- task: DownloadSecureFile@1
  name: CaCert
  displayName: 'Download CA cert'
  inputs:
	secureFile: 'ca.pem'

- script: |
	echo Installing $(CaCert.secureFilePath) to trusted CA directory...
	sudo chown root:root $(CaCert.secureFilePath)
	sudo chmod a+r $(CaCert.secureFilePath)
	sudo ln -s -t /etc/ssl/certs/ $(CaCert.secureFilePath)
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a5f8376-3654-0ed4-d9f8-d15f28350783
* Version Independent ID: f393daba-6515-6c26-71ac-b557e8c8dad1
* Content: [Download Secure File task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-secure-file?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/download-secure-file.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/download-secure-file.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @DavidStaheli
* Microsoft Alias: **dastahel**
