### ISSUE TITLE
Web config Transforms deleted prior to release

### ISSUE THREAD

**Issue by darrenferguson** [MicrosoftDocs/vsts-docs#4725]
In my azure devops project I have web config transforms e.g.

- Web.Preview.Config
- Web.Staging.Config

I want to apply them at release time, but they aren't present in the Artifact built by Azure Devops.

My MSBuild command in my build YAML looks like this:

```
- task: VSBuild@1
  displayName: 'Build'
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:TransformWebConfigEnabled=False /p:AutoParameterizationWebConfigConnectionStrings=False  /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
```

The build action on these files is "Content".

But yet they don't end up in the built artifact.

Can anyone help?

Many Thanks.
