### ISSUE TITLE
Cannot set pipeline parameters via Yaml and link to stages

### ISSUE THREAD

**Issue by deploymentking** [MicrosoftDocs/vsts-docs#4731]
I am trying to turn a manually created Build Pipeline that runs successfully into one I can put into a YAML file.

**I link the Storage Container URI as follows**
```
Setting to link == Storage Container URI
The pipeline parameter to link to this setting == Parameters.outputStorageUri
Display name == Storage Container URI
Value == outputStorageUri
```

**I link the Storage Container SAS Token as follows**
```
Setting to link == Storage Container SAS Token
The pipeline parameter to link to this setting == Parameters.outputStorageContainerSasToken
Display name == Storage Container SAS Token
Value == outputStorageContainerSasToken
```

I have two pipeline variables called `outputStorageUri` and `outputStorageContainerSasToken`

I have an Azure Deployment step that has this in the **Override template parameters** field
```
-product Cinch -environment Sandbox -logWorkspaceSubscription Dev -templateContainerUri $(outputStorageUri)$(Build.DefinitionName)/$(Build.BuildId) -templateContainerSasToken $(outputStorageContainerSasToken) -apimServiceName validate-test -tShirtSize small
```

This works brilliantly....but when I export the YAML to 

```
pool:
  name: Hosted Windows 2019 with VS2019
  demands: azureps

#Your build pipeline references an undefined variable named ‘outputStorageUri’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references an undefined variable named ‘outputStorageContainerSasToken’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references an undefined variable named ‘outputStorageUri’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references an undefined variable named ‘outputStorageContainerSasToken’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
variables:
  Parameters.outputStorageUri: ''
  Parameters.outputStorageContainerSasToken: ''

steps:
- task: AzureFileCopy@2
  displayName: 'AzureBlob File Copy'
  inputs:
    SourcePath: templates
    azureSubscription: 'REDACTED'
    Destination: AzureBlob
    storage: REDACTED
    ContainerName: arm
    BlobPrefix: '$(Build.DefinitionName)/$(Build.BuildId)'
    outputStorageUri: '$(Parameters.outputStorageUri)'
    outputStorageContainerSasToken: '$(Parameters.outputStorageContainerSasToken)'

- bash: |
   echo ARTIFACT_LOCATION=$(outputStorageUri)
   echo ARTIFACT_LOCATION_SAS_TOKEN=$(outputStorageContainerSasToken)
  displayName: 'Bash Script'

- task: AzureResourceGroupDeployment@2
  displayName: 'Azure Deployment:Create Or Update Resource Group action on Cinch-Frontend-Dev-rg'
  inputs:
    azureSubscription: 'REDACTED'
    resourceGroupName: 'Cinch-Frontend-Dev-rg'
    location: 'North Europe'
    csmFile: templates/cinch.apim.master.template.json
    overrideParameters: '-product Cinch -environment Sandbox -logWorkspaceSubscription Dev -templateContainerUri $(outputStorageUri)$(Build.DefinitionName)/$(Build.BuildId) -templateContainerSasToken $(outputStorageContainerSasToken) -apimServiceName validate-test -tShirtSize small'
    deploymentMode: Validation
```
and try and run this it fails miserably!!! Why
How do you specify Linked Parameter Variables in YAML???
