### ISSUE TITLE
No documentation concerning support for variables in trigger include path

### ISSUE THREAD

**Issue by derwent-m** [MicrosoftDocs/vsts-docs#4773]
Variables are not supported in trigger include paths, e.g.
```
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - subscriptions/$(TF_PATH)/*
```
This should be documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5673ec1-c7d1-e0ac-043a-8fc3d5b226a9
* Version Independent ID: b4872831-51c0-6cf8-1c56-de20beb38a80
* Content: [Build pipeline triggers - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?tabs=yaml&view=azure-devops#feedback)
* Content Source: [docs/pipelines/build/triggers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/triggers.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**
