### ISSUE TITLE
Container example to pass in command args

### ISSUE THREAD

**Issue by adriantorrie** [MicrosoftDocs/vsts-docs#4825]
[Container docs](https://docs.microsoft.com/en-nz/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#container-reference): No examples are provided for passing in CMD args

I currently have the following in my pipeline:
```yaml
      # Run structure tests
      # - https://github.com/GoogleContainerTools/container-structure-test#running-tests-on-google-cloud-build
      - bash: |
          set -e

          # Perform structure tests on container
          docker run \
            --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v $(Build.Repository.LocalPath)/container_structure_test.yml:/container_structure_test.yml \
            gcr.io/gcp-runtimes/container-structure-test:latest test \
              --image $(FULL_IMAGE_NAME) \
              --config /container_structure_test.yml
        displayName: 'Run structure tests'
```

This seems like a good candidate to use the simpler container reference, is something like the following possible?:
```yml
jobs:
- job: structure_tests
  container:
    image: gcr.io/gcp-runtimes/container-structure-test:latest
    options: --rm -v /var/run/docker.sock:/var/run/docker.sock -v $(Build.Repository.LocalPath)/container_structure_test.yml:/container_structure_test.yml
    cmd: test --image $(FULL_IMAGE_NAME) --config /container_structure_test.yml
```

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-nz/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#container-reference)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback -- we will look into adding such an example to the documentation.
Meanwhile, you might consider asking your question here: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by benc-uk** [comment]
I agree this needs to be made easier. The new GitHub Actions lets you do this and it's super simple. Azure Pipelines only supports containers **without an entrypoint** which is kinda goofy as there's LOT of prebuilt containers for various tools out there, that all have entrypoints.

In GitHub Actions I can do this in a step:
```
    - name: Run API tests with Postman/newman
      uses: docker://postman/newman:ubuntu
      with:
        args: run /github/workspace/tests/postman.json
```
Which simply pulls the `postman/newman:ubuntu` image, runs it and passes some args to the the docker run command. It even automatically mounts the workspace into the container, in Pipelines I have to manually do that

AFAIK I don't think there's any way to do this in Azure Pipelines without manually calling `docker run` which is clumsy
