### ISSUE TITLE
Agentless job

### ISSUE THREAD

**Issue by adriantorrie** [MicrosoftDocs/vsts-docs#4826]
[Job docs](https://docs.microsoft.com/en-nz/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#job) shows no examples of running an agentless job, **is this possible**? Should the `pool` key just be left out, or set to one of `[ false | null ] `?

The reason I ask is that we need to add a [manual intervention task](https://docs.microsoft.com/en-nz/azure/devops/pipelines/tasks/utility/manual-intervention?view=azure-devops), and unsure if it will work, as this link states an *agent-less* job is required, but I can see the yaml task is available when editing the `azure-pipelines.yml` file in Azure DevOps web UI?

I can see that I can add a manual intervention task via yaml like so:
```yaml
    - task: ManualIntervention@8
      inputs:
        instructions: 'QA Checks'
        emailRecipients: 'me@interwebs.com'
```
What isn't clear is whether this will actually run within the job (which has a pool), or if I should create another job without a pool? Or if it's actually allowed given there is no "agent-less job" outlined in the documentation.

![image](https://user-images.githubusercontent.com/3909039/61019983-78b9fc80-a3df-11e9-8401-d479a1c0b754.png)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-nz/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#job)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
It's the next section down after `pool`: https://docs.microsoft.com/azure/devops/pipelines/yaml-schema#server (syntax is `pool: server`).

**Comment by vtbassmatt** [comment]
Ah sorry, I just read the words under the screenshot. Yes, you'll need to make a new job that's serverless in order to run a serverless task.

**Comment by adriantorrie** [comment]
How exactly do you create a serverless job?

**Comment by vtbassmatt** [comment]
Wow, I really mistyped that. I meant you'll need to make a server job for an agentless task.

**Comment by nerijusk** [comment]
The following error is generated by pipeline run after adding ManualIntervention@8 task to it:
`"Task execution section of task definition for ID: bcb64569-d51a-4af0-9c01-ea5d05b3b622 is either missing or not valid."`
I suspect it is not supported in yaml pipeline, only in GUI. Why such thing is made for GUI, but not for pipeline as a code is beyond me. This is unacceptable nowadays... :(

**Comment by vtbassmatt** [comment]
@nerijusk Did you add the task to an agent job or a server job? It only works for server jobs, and it doesn't care (or know) whether you're using designer or YAML.

**Comment by nerijusk** [comment]
It's defined as a server job in `azure-pipelines.yaml`:
```
  - stage: manual_approval_before_deploy
    displayName: "Manual approval before deployment"
    jobs:
      - job: manual_approval
        condition: ne(variables['Build.Reason'], 'PullRequest')
        pool: server
        timeoutInMinutes: 60
        steps:
          - task: ManualIntervention@8
            timeoutInMinutes: 60
            displayName: "Manual approval"
            inputs:
              instructions: "review deploy"
              emailRecipients: "my@email.com"
              onTimeout: reject
```
Oh, and "Checks" on environment does not suite my use case. I want to decide to deploy or not, but the decision to stop pipeline right after build should not mark it as "Failed". Checks in environment mark the pipeline as "Failed" if I reject deployment into environment, which is not true. My use case is that DEV/QA environments maybe deployed many times over the day, but I want my STAGING/UAT environments to be more stable and deployed less often maybe once every other day.
