### ISSUE TITLE
What specificBuildWithTriggering does?

### ISSUE THREAD

**Issue by olandese** [MicrosoftDocs/vsts-docs#4859]
Can you please explain what the specificBuildWithTriggering exactly does?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0a16bcf-af6c-e278-f0a6-8ec95012ce4a
* Version Independent ID: ae442106-33b3-786f-2158-34eed3fed6e0
* Content: [Download Build Artifacts task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-build-artifacts?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/download-build-artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/download-build-artifacts.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by ashokirla** [comment]
Can you explain more about the scenario here.

**Comment by buckleyGI** [comment]
It's unclear what this option does. Can you give an example? Thank you.

**Comment by olandese** [comment]
> It's unclear what this option does. Can you give an example? Thank you.

that's the point, more explanation is needed about this option

**Comment by devlie** [comment]
It's mentioned in https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-pipeline-artifact?view=azure-devops

I'm also curious what it does. What's the definition of appropriate?

**Comment by nishants** [comment]
I have a build (BUILD-B) that is triggered by build (BUILD-A).
I am using following parameters  with : 
```yaml
task: DownloadBuildArtifacts@0
inputs:
   buildType: 'specific'
   project: 'MyProject'
   pipeline: 'BUILD-A'
   specificBuildWithTriggering: true
   allowPartiallySucceededBuilds: true
   artifactName: 'coverage'
   itemPattern: 'coverage/lcov.info'
   downloadPath: 'src/test'
```

Do I need to add param `branchName: $(variables['Build.SourceBranch'])` as well ? 
Or, will `specificBuildWithTriggering` make sure the the artifacts are downloaded from correct build id ?
