### ISSUE TITLE
checkout clean settings are wrong

### ISSUE THREAD

**Issue by AArnott** [MicrosoftDocs/vsts-docs#4867]
Under the `checkout: self` step, the clean property must be `true` to clean. The `all | outputs | resources` value is ignored and causes git checkout to _not_ clean at all.
An AZP engineer told me that the `all | outputs | resources` setting only applies to cleaning of *workspaces*.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#job)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
@TingluoHuang or @ericsciple can you clarify here? schema.yml beginning around line 1410 says:

```yaml
    - structure: mapping
      firstKey: checkout
      inherits: taskBase
      properties:
      - name: checkout
        type: string
        data:
          description: "Whether or not to check out the repository containing this pipeline definition"
          enum: "self,none"
      - name: clean
        type: string
        data:
          description: "Scorch the repo before fetching?"
          enum: "outputs,resources,all"
```

That said, `workspace` expects a suspiciously similar enum, so I'm wondering if this is a bug in the schema.
