### ISSUE TITLE
Document priority of variables set in different scopes

### ISSUE THREAD

**Issue by alecmocatta** [MicrosoftDocs/vsts-docs#4879]
I'd like to set global variables, and then optionally override them in certain jobs (specified with a matrix strategy). As far as I can see, whether this works as intended isn't documented?

```yaml
variables:
  rust_toolchain: nightly

strategy:
  matrix:
    windows:
      imageName: 'vs2017-win2016'
      rust_target: 'x86_64-pc-windows-msvc x86_64-pc-windows-gnu'
    mac:
      imageName: 'macos-10.13'
      rust_target: 'x86_64-apple-darwin'
    linux:
      imageName: 'ubuntu-16.04'
      rust_target: 'x86_64-unknown-linux-gnu x86_64-unknown-linux-musl'
      rust_toolchain: 'stable beta nightly'
```

This should dispatch three jobs, two of which have `rust_toolchain: nightly` and one of which has `rust_toolchain: 'stable beta nightly'`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#feedback)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**
