### ISSUE TITLE
How to enable/disable schedule on demand?

### ISSUE THREAD

**Issue by bingosummer** [MicrosoftDocs/vsts-docs#4890]
I have two pipelines which share one configuration. One should be scheduled to trigger, the other should be manually trigger.
Previously I can do it by setting different triggers in UI. But now, seems I can't do this via the triggers in yaml file. How can I do this? Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#triggers)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
We're bringing back the ability to override YAML-based schedule triggers in the UI. Sorry for the temporary inconvenience.

If it's critical right now, you can work around this limitation by moving the core of your pipeline to a template, then wrapping it in two separate outer pipelines (one with the triggers you want, the other without). Example:

```yaml
# azure-pipelines-triggered.yml
schedules:
  cron: '0 0 * * *'
jobs:
- template: myjobs.yml


# azure-pipelines-manual.yml
trigger: none
pr: none
jobs:
- template: myjobs.yml


# myjobs.yml
jobs:
- job: build
  steps:
  ...
```
