### ISSUE TITLE
This access control list is not in canonical form and therefor cannot be modified

### ISSUE THREAD

**Issue by gojanpaolo** [MicrosoftDocs/vsts-docs#4910]
Hi.
I'm getting the following message after [step 7](https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/cd/deploy-webdeploy-iis-deploygroups?view=azure-devops#create-a-deployment-group)
```
This access control list is not in canonical form and therefor cannot be modified
```

I'm using a Hyper-V VM

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca1c5394-611b-b119-dbf3-b88404e351d5
* Version Independent ID: fcc23259-21ec-f9fa-4e25-f587e1e0f41b
* Content: [Deploy to IIS on a Windows VM - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/cd/deploy-webdeploy-iis-deploygroups?view=azure-devops#create-a-deployment-group)
* Content Source: [docs/pipelines/apps/cd/deploy-webdeploy-iis-deploygroups.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/apps/cd/deploy-webdeploy-iis-deploygroups.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by gojanpaolo** [comment]
I ran the agent's `run.cmd` manually. and it looks like it's now running.
But when I deploy I get an error

Error: No package found with specified pattern

**Comment by RoopeshNair** [comment]
package is the release artifact / folder to deploy. You can specify it in the task input field **Package or folder**. In the screenshot below it the last field with the default input value as `$(System.DefaultWorkingDirectory)\**\*.zip`. Ensure that there is a single '*.zip' in the path. If multiple zip files are found it will fail. 

![image](https://user-images.githubusercontent.com/1370480/61430661-4d3b9280-a948-11e9-97c5-e6b7705eeed2.png)

**Comment by gojanpaolo** [comment]
> Ensure that there is a single '*.zip' in the path.  If multiple zip files are found it will fail.

In my case, there was no files at all. As a beginner in using Azure Pipelines, it took me a while to figure out the issue which is editing the `azure-pipelines.yml`.

The generated `azure-pipelines.yml` contains the following steps
```yml
steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
```

That needs to be changed to publish like so:
```yml
steps:

- task: DotNetCoreCLI@2
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'myWebsiteName'
```

Now everything is working as expected. But then again, this is not included in any of the azure pipelines official tutorials / getting started guides.
