### ISSUE TITLE
Docker@2 buildAndPush missing arguments

### ISSUE THREAD

**Issue by mikebollanddp** [MicrosoftDocs/vsts-docs#4928]
To pass in the PAT and FEED_URL to docker file for NuGet Artifact repositories we need to use the arguments but this is only available on 'build' task for Docker@2, the documentation shows 'buildAndPush' instead which does not support arguments

The documentation is not clear on how to use 'build' and 'push' individually to achieve this

I have tried

```
   - 
        task: Docker@2
        displayName: Login to ACR
        inputs:
            command: login
            containerRegistry: $(acrSubscriptionEndpoint)
    -
        task: Docker@2
        displayName: 'Build'
        inputs:
            azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
            azureContainerRegistry: $(DockerNamespace)
            command: build
            dockerFile: '**/Dockerfile'
            arguments: '--build-arg PAT=$(System.AccessToken) --build-arg FEED_URL=$(feedUrl)'
            useDefaultContext: false
            includeLatestTag: true
            buildContext: '$(Build.SourcesDirectory)'
            tags: $(Build.BuildId)' 
    - 
        task: Bash@3
        displayName: Show docker images
        inputs:
          targetType: inline
          script: docker images
    - 
        task: Docker@2
        displayName: "Push to the test ACR"
        inputs:
          azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
          azureContainerRegistry: $(DockerNamespace)
          command: "push"
          repository: $(DockerRepository)
          includeLatestTag: true
          tags: $(Build.BuildId)' 
```

Without luck, its almost like the images built in the build stage are not available to the push stage

Please can someone update the documentation to explain how this should function?

**Comment by WilliamAntonRohm** [comment]
@mikebollanddp  Thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around the general task.

**Comment by mikebollanddp** [comment]
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker?view=azure-devops

**Comment by shashankbarsin** [comment]
@mikebollanddp I've added standalone examples on `build` and `push`.

I noticed from your sample that you are using a lot of task inputs 'azureSubscriptionEndpoint' and 'azureContainerRegistry' which are not supported under [Docker@2 task as per the documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker?view=azure-devops). Can you try correcting these inputs in your tasks based on the following samples for build and push - 

**Build**
```YAML
steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: app/Dockerfile
    arguments: --no-cache
```

**Push**
```YAML
- task: Docker@2
  displayName: Push image
  inputs:
    containerRegistry: $(dockerHub)
    repository: $(imageName)
    command: push
    tags: |
      test1
      test2
```
