### ISSUE TITLE
Mount volume

### ISSUE THREAD

**Issue by patrickhowerter** [MicrosoftDocs/vsts-docs#4941]
How can you mount a volume before running a job in here? That would be a very useful feature.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3339a2e0-be29-1363-f588-b231d4472c02
* Version Independent ID: 72dd11a3-704d-d0fd-6dfa-cf49f3352de3
* Content: [Container Jobs in Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/container-phases.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/container-phases.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @thomps23
* Microsoft Alias: **macoope**

**Comment by richardgavel** [comment]
https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=example#container-reference

Could you use the options property on the container to set up the mount like you would on a normal docker container run invocation?

**Comment by richardgavel** [comment]
It also does support mounting directly here: https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=example#resources

**Comment by patrickhowerter** [comment]
Is there documentation about how to mount azure files volume? I have always mounted using things like azure cli or powershell, not with options in a docker command.

**Comment by vtbassmatt** [comment]
We don't document anything other than native Docker mounts, which are mentioned [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#container-resource). The `volumes` syntax matches Docker Compose format.

**Comment by daveneeley** [comment]
Docker wants absolute paths on the left-hand side of a volume mount. But Container resources are parsed before pipeline variables are available.  These volumes and environment parameters get passed as-is when the agent actually starts the container. On an azure pipelines agent hosted and supported by Microsoft, an absolute path is not a good idea. Wish this worked:

```
container:
  image: my-image:latest
  endpoint: my-acr-endpoint
  env:
    RELEASE_MAJOR: $(Date:yyyyMMdd)
    RELEASE_MINOR: $(Rev:r)
  volumes:
    - $(Build.SourcesDirectory):/srv/src:ro
    - $(Build.ArtifactStagingDirectory):/srv/build:rw
  options:
    --workdir /srv/src
```
