### ISSUE TITLE
How to set a pipeline variable from kubectl get

### ISSUE THREAD

**Issue by sadedil** [MicrosoftDocs/vsts-docs#5032]
Hi,

According to *Commands* part, there is not enough information about `get`
I need to set a pipeline variable from kubectl get, but it's not clear.

Could you add an example of this scenario.

My sample task like this
```
- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'endpoint1'
    namespace: 'namespace1'
    command: 'get'
    arguments: "deployment my-deployment-name"
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
    outputFormat: "jsonpath='{$.spec.template.spec.containers[:1].image}'"
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcbb25d1-a706-e8fc-61e4-d5b86aa54f47
* Version Independent ID: 5634d9dd-fd92-761c-24b8-5e32ed6c6c35
* Content: [Deploy to Kubernetes task - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/kubernetes?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/kubernetes.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/kubernetes.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @shashankbarsin
* Microsoft Alias: **shasb**

**Comment by andrewglind** [comment]
I had a very similar problem, solved by doing below (adapted for your use case):

   - task: AzureCLI@1
     displayName: Get access credentials for the managed cluster
     inputs:
       azureSubscription: ${{ parameters.serviceConnection }}
       scriptLocation: 'inlineScript'
       inlineScript: 'az aks get-credentials -g ${{ parameters.resourceGroup }} -n ${{ parameters.clusterName }}'

   - task: CmdLine@2
     displayName: Make containerImage available as a variable
     inputs:
       script: 'image="##vso[task.setvariable variable=containerImage]"$(kubectl get deployment my-deployment-name -o jsonpath=''{$.spec.template.spec.containers[:1].image}'') -n namespace1'

**Comment by sadedil** [comment]
Hi andrewglind,

I think this is a good approach, thanks for the sample code.

**Comment by msebolt** [comment]
Sorry for the delay on this, re-assigning to the author.

**Comment by shashankbarsin** [comment]
Looks like @andrewglind has already given a workaround for this issue. Will thus close the issue.

Just curious, @sadedil what were you using this variable for later in the pipeline? If it's a commonly occurring use case, we can consider options on how to make this experience better - task improvements or variable improvements...

**Comment by sadedil** [comment]
Hi @shashankbarsin,

I have a Azure YAML Pipeline. This pipeline builds docker image (1), give a new tag to this image from build number (2), and apply K8s manifests using **KubernetesManifest@0** task (3). At the last step, i'm replacing _spec.containers.image_ to use newly generated tag number. This is the default template when you create a new YAML Pipeline with K8s support.

But it's not ideal for all circumstances. Because I don't always want to create a docker image (it takes several minutes). Sometimes I need to change something in the K8s manifest (like label, replicaCount, annotation, etc.) and I want to redeploy manifests using `kubectl apply` without the build image.. The problem starts here because I need to get current image tag first, then apply manifests. This is the reason of need this: **set a pipeline variable from kubectl get**

For this reason I've opened this issue.

---

Currently I've followed this way:

a) Create a yaml task template (_templates/get-deployment-image.yml_)

```yaml
parameters:
  taskNumber: 0
  k8sServiceConnection: ''
  k8sNamespace: 'default'
  imagePullSecrets: ''
  deploymentName: ''
  manifestFile: ''

steps:
- task: Kubernetes@1
  displayName: 'Get ${{ parameters.deploymentName }} image name'
  name: 'task${{ parameters.taskNumber }}'
  continueOnError: true
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: '${{ parameters.k8sServiceConnection }}'
    namespace: '${{ parameters.k8sNamespace }}'
    command: 'get'
    arguments: "deployment ${{ parameters.deploymentName }}"
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
    outputFormat: "jsonpath='{$.spec.template.spec.containers[:1].image}'" # the warning is OK

# taskN.KubectlOutput now holds a value like this (including quotes): 'my-registry/my-image:123'
# so, I need to get rid of quotes, because below KubernetesManifest@0 task does not understand this format.

- task: PowerShell@2
  displayName: 'Trim unnecessary quotes for ${{ parameters.deploymentName }}'
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "##vso[task.setvariable variable=returnValue${{ parameters.taskNumber }}]"$(task${{ parameters.taskNumber }}.KubectlOutput).trim("'").trim()

- task: KubernetesManifest@0
  displayName: 'Apply manifests to Kubernetes cluster ${{ parameters.deploymentName }}'
  inputs:
    action: deploy
    kubernetesServiceConnection: '${{ parameters.k8sServiceConnection }}'
    namespace: '${{ parameters.k8sNamespace }}'
    manifests: '${{ parameters.manifestFile }}'
    imagePullSecrets: |
      ${{ parameters.imagePullSecrets }}
    containers: |
      $(returnValue${{ parameters.taskNumber }})
```


b) Then use in an another pipeline's deploy stage like this (_azure-pipelines.yml_)
(This pipeline doesn't )

```yaml
# skip above
          - template: templates/get-deployment-image.yml
            parameters:
              taskNumber: 1
              k8sServiceConnection: $(kubernetesServiceConnection)
              k8sNamespace: $(k8sNamespace)
              imagePullSecrets: $(imagePullSecret)
              deploymentName: $(deploymentMyAppApi)
              manifestFile: $(System.ArtifactsDirectory)/manifests/dep-myapp-api.yml
# skip below
```

**Comment by roofiq** [comment]
Hey, that workaround from @andrewglind looks good.
But how can we reference to this image? Could you provide some examples?

**Comment by codeConcussion** [comment]
The workaround is fine if you aren't working with an Azure Kubernetes cluster that has Azure AD enabled. If you do, you'll get a security challenge (go to https://microsoft.com/devicelogin and enter a code). That's not a good thing when I'm trying to run this in an DevOps Pipeline. Are there any other options?

**Comment by JWDobken** [comment]
even if the workaround works, this problem requires a constructive permanent solution.

Therefore please reopen this issue

**Comment by JWDobken** [comment]
For me [this StackOverflow](https://stackoverflow.com/a/70496312/5316326) answer solved the issue.

First, give yrou task a name, e.g. `myImageName`

```yaml
- task: Kubernetes@1
  name: myImageNameTask
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'endpoint1'
    namespace: 'namespace1'
    command: 'get'
    ...
```

Now you can refer to the kubectl output with:

```cmd
echo $(myImageNameTask.KubectlOutput)
```
