### ISSUE TITLE
Cannot get templated variables to work

### ISSUE THREAD

**Issue by laurawalker** [MicrosoftDocs/vsts-docs#5062]
Hi, 

I'm attempting to use a template containing only variables, as illustrated by this example: 
https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=example#variable-templates

I have a very basic build with a single job that "echo"s the values from the template, and the template contains literally the examples given in that example. No matter what I do, I cannot get the template values to return anything.

My build script: 
```
name: $(date:yyyyMMdd)$(rev:.rr)-$(BuildID)

resources:
  repositories:
  - repository: self
    clean: true

trigger: none

jobs:
- job: TestUsingTemplateVariables
  displayName: 'Test using template variables'
  timeoutInMinutes: 10
  cancelTimeoutInMinutes: 5
  pool:
    name: Hosted Ubuntu 1604
  variables:
    template: template.yml

  steps:
  - task: CmdLine@1
    displayName: 'Log environment variables'
    inputs:
      filename: printenv

  - script: echo ${{ variables.arch }} ${{ variables.config }}
```

Where template.yml contains literally the values from the example:
```
variables:
- name: vmImage
  value: vs2017-win2016
- name: arch
  value: x64
- name: config
  value: debug
```
The output I get:
```
##[section]Starting: CmdLine
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.151.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
Script contents:
echo
========================== Starting Command Output ===========================
[command]/bin/bash --noprofile --norc /home/vsts/work/_temp/dd99ed11-81a6-40cc-b6c8-eee2ab5152e0.sh

##[section]Finishing: CmdLine
```

Things to note:
  - `script: echo "$(Build.BuildId)"` (which is obviously a not-template-defined variable) works fine
  - I get no error if change the path of the template to something obviously incorrect. This suggests to me that it's possible that it's just not finding the template at all - but I've tried all variation of relative and absolute path that I can think of. It would be really useful if this were to return an error if the template didn't exist so I could rule that out. 

What am I doing wrong?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=example#feedback)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

**Comment by vtbassmatt** [comment]
This appears to be a product bug - the docs and your example should both work. I've filed it internally.

**Comment by laurawalker** [comment]
Thanks

**Comment by BjornVanDoorn** [comment]
Is there any ETA on when this is fixed. I'm having the same issue's and wondering if this is still a bug or something on my side?

**Comment by vtbassmatt** [comment]
Re-reading the example code, I see the problem. Not sure why I didn't catch it before. The variables section is missing a `-`:

```yaml
jobs:
- job: TestUsingTemplateVariables
  # removed lines for clarity
  variables:
  - template: template.yml  # note the leading hyphen
```
