### ISSUE TITLE
Still confused on how cache works

### ISSUE THREAD

**Issue by MisinformedDNA** [MicrosoftDocs/vsts-docs#5095]
I'm still confused about how caching works. In the first YARN example, there are two steps, cache and yarn. Is the yarn step run regardless of whether the cache step gets a hit? But ideally, it will run faster with the cache because it doesn't need to manually download all the dependencies?

```yaml
variables:
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn

steps:
- task: CacheBeta@0
  inputs:
    key: |
      yarn
      $(Agent.OS)
      $(Build.SourcesDirectory)/yarn.lock
    path: $(YARN_CACHE_FOLDER)
  displayName: Cache Yarn packages

- script: yarn --frozen-lockfile
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c20289-dab2-7a6e-4f63-4b30eaff2c71
* Version Independent ID: d75cc196-90c1-8291-9907-ff405bde4edf
* Content: [Pipeline caching - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/caching/index?view=azure-devops#yarn)
* Content Source: [docs/pipelines/caching/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/caching/index.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @willsmythe
* Microsoft Alias: **wismythe**
