### ISSUE TITLE
Simple msi installer

### ISSUE THREAD

**Issue by jherby2k** [MicrosoftDocs/vsts-docs#5260]
How would I cache something really simple like an MSI installer?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c20289-dab2-7a6e-4f63-4b30eaff2c71
* Version Independent ID: d75cc196-90c1-8291-9907-ff405bde4edf
* Content: [Pipeline caching - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/caching/index?view=azure-devops)
* Content Source: [docs/pipelines/caching/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/caching/index.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @willsmythe
* Microsoft Alias: **wismythe**

**Comment by msebolt** [comment]
@jherby2k  Thank you for the question.

There should be no issue provided you place the installer in the right location (like the directory of the build agent) and follow the templates, like:

```
variables:
  MSI_INSTALLER: $(Pipeline.Workspace)/installers

steps:
- task: CacheBeta@0
  inputs:
    key: msi | myinstaller
    path: $(MSI_INSTALLER)
  displayName: Cache MSI installer
```

If there are any issues, please comment below.
