### ISSUE TITLE
clarification request: YAML triggers, path filters - are variables supported?

### ISSUE THREAD

**Issue by NenoLoje** [MicrosoftDocs/vsts-docs#5409]
Can we do something like:

``` YAML
trigger:
  paths:
    include:
    - $(ProjectName)/src/

variables:
  ProjectName: foo
```

Is that supported?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=example#triggers)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
I don't recall off-hand if that works. This should, though:

```yaml
trigger:
  paths:
    include:
    - ${{ variables.ProjectName }}/src/

variables:
  ProjectName: foo
```

(Only works because the variable is statically defined, though - if it was queue-time or computed somehow, it would not work.)
