### ISSUE TITLE
Download azure build agent in build process

### ISSUE THREAD

**Issue by Astasian** [MicrosoftDocs/vsts-docs#5430]
It would align more with docker, if the azure build agent was downloaded in the building process. When I start an array of agents, all of them are first downloading ~230mb for the agent. 
If you really want to update the agent, you should rebuild the image, like any other image.

I found two ways to download the agent:

1. Go to dev.azure.com/yourorg > Agent Pools > New Agent and copy the agent link
But the link contains a version number, which is not practical.

2. With start.sh you must first authenticate, which is also not practical.

Is there another way to just get the latest agent for building the image?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b31d4f6c-d16d-2ba1-1294-6aa94e328046
* Version Independent ID: 88aec599-4410-697d-1002-1c41b1c17bb6
* Content: [Running a self-hosted agent in Docker - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops#feedback)
* Content Source: [docs/pipelines/agents/docker.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/docker.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliobbv
* Microsoft Alias: **juliobv**

**Comment by kirkone** [comment]
I had the same thing in mind.

If you want you can have a look here how I implemented this approach here:
https://github.com/codez-one/docker-azure-pipelines-agent

**Comment by fgervais** [comment]
@Astasian on our side we use your option 1 but in the Dockerfile we make the agent version a build arg and we let the pipeline find the latest version and set it when building the image. Those images then get taggged with the agent version. We also have the pipeline update the "latest" tag.

I actually think this is what Microsoft should be doing, then they would push those images to their dockerhub.

One more note is that we actually require the `AZP_TOKEN` only the first time the container is run, like when using the agent outside of docker. If you do the same, you would create the PAT, make sure `AZP_TOKEN` is set and launch the array of agent. Then you can revoke the token. The containers can be started and stopped they will stay registered.

If it helps here is what we use here.

Dockerfile:
```
FROM ubuntu:16.04 AS base

FROM base AS install
RUN apt-get update && apt-get install -y --no-install-recommends \
        ca-certificates \
        curl \
        jq \
        git \
        iputils-ping \
        libcurl3 \
        libicu55 \
        libunwind8 \
        netcat \
        wget

ARG agent_dir=/azp/agent
ARG agent_version
WORKDIR $agent_dir
# View available versions:
# https://ablcode.visualstudio.com/_apis/distributedtask/packages/agent?platform=linux-x64
RUN wget https://vstsagentpackage.azureedge.net/agent/${agent_version}/vsts-agent-linux-x64-${agent_version}.tar.gz && \
	tar xf vsts-agent-linux-x64-${agent_version}.tar.gz && \
	rm vsts-agent-linux-x64-${agent_version}.tar.gz
COPY start.sh .
RUN chmod +x start.sh
VOLUME $agent_dir

CMD ["./start.sh"]
```
start.sh:
```
#!/bin/bash

CONFIG_TRIGGER_FILE=.agent

print_header() {
  lightcyan='\033[1;36m'
  nocolor='\033[0m'
  echo -e "${lightcyan}$1${nocolor}"
}

source ./env.sh

trap 'cleanup; exit 130' INT
trap 'cleanup; exit 143' TERM

if [ ! -f "$CONFIG_TRIGGER_FILE" ]; then
  print_header "3. Configuring Azure Pipelines agent..."

  if [ "${AZP_TOKEN}" == "" ]; then
    echo "Please define AZP_TOKEN environment variable."
    echo ""
    echo "The following optional variables can also be defined:"
    echo "AZP_AGENT_NAME"
    echo "AZP_POOL"
    exit 1
  fi

  ./config.sh --unattended \
    --agent "${AZP_AGENT_NAME:-$(hostname)}" \
    --url "<<Our url>>" \
    --auth PAT \
    --token "${AZP_TOKEN}" \
    --pool "${AZP_POOL:-<<Our pool name>>}" \
    --work "_work" \
    --replace \
    --acceptTeeEula & wait $!
fi

print_header "4. Running Azure Pipelines agent..."

# `exec` the node runtime so it's aware of TERM and INT signals
# AgentService.js understands how to handle agent self-update and restart
exec ./externals/node/bin/node ./bin/AgentService.js interactive
```
azure-pipelines.yml:
```
jobs:
- job: docker_build
  pool:
    vmImage: 'ubuntu-16.04'

  steps:
  - bash: |
      latest_version=`AZP_TOKEN=$(System.AccessToken) \
                      ./azure-scripts/get-latest-version.sh`
      echo "##vso[task.setvariable variable=agent_version;]$latest_version"
    displayName: Get agent latest version

  - task: Docker@2
    displayName: Login to ACR
    inputs:
      command: login
      containerRegistry: <<Our registry>>

  - task: Docker@2
    displayName: 'Build image'
    inputs:
      command: build
      repository: '$(Build.Repository.Name)'
      tags: |
        $(agent_version)
        latest
      arguments: >
        --build-arg agent_version=$(agent_version)

  - task: Docker@2
    displayName: 'Push image'
    inputs:
      command: push
      repository: '$(Build.Repository.Name)'
      tags: |
        $(agent_version)
        latest

  - task: Docker@2
    displayName: Logout of ACR
    inputs:
      command: logout
      containerRegistry: <<Our registry>>
```
get-latest-version.sh
```
#!/bin/bash

AZP_URL=<<Our url>>

AZP_AGENT_RESPONSE=$(curl -LsS \
  -u user:$AZP_TOKEN \
  -H 'Accept:application/json;api-version=3.0-preview' \
  "$AZP_URL/_apis/distributedtask/packages/agent?platform=linux-x64")

if echo "$AZP_AGENT_RESPONSE" | jq . >/dev/null 2>&1; then
  AZP_AGENTPACKAGE_URL=$(echo "$AZP_AGENT_RESPONSE" \
    | jq -r '.value | map([.version.major,.version.minor,.version.patch])
              | sort | .[length-1] | map(tostring) | join(".")')
fi

echo $AZP_AGENTPACKAGE_URL
```
