### ISSUE TITLE
Invalid YAML in environment example

### ISSUE THREAD

**Issue by mpalumbo7** [MicrosoftDocs/vsts-docs#5502]
The YAML in section #targeting-a-specific-resource-within-an-environment-from-deployment-job is invalid. 

```yaml
# you can't have a string after the column, and then also a nested object `strategy`.
environment: 'smarthotel-dev.bookings'
  strategy: 
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77d95db6-9983-7346-d0eb-4b7443e4e252
* Version Independent ID: 0a22cccc-318d-592f-d1ab-09ec01d88087
* Content: [Environment - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/environments?view=azure-devops#targeting-a-specific-resource-within-an-environment-from-deployment-job)
* Content Source: [docs/pipelines/process/environments.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/environments.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**
