### ISSUE TITLE
Stage reuse (on Azure Devops Server) is unclear

### ISSUE THREAD

**Issue by buck-mbeer** [MicrosoftDocs/vsts-docs#5510]
I'm attempting to reuse a multi-job pipeline by templating a `stage` on Azure Devops Server 2019. Following the documentation here and on the YAML Scheme page, I tried:

```
variables:
  Message: Hello World
resources:
  repositories:
  - repository: common
    type: git
    ref: refs/tags/v1.0.1
    name: TemplatedPipeline
stages:
- template: pipeline-template.yml@common
```
And the pipeline-template.yml file looks as follows:
```
resources:
  containers:
  - container: NetCoreSDK21
    image: mcr.microsoft.com/dotnet/core/sdk:2.1

stages:
- stage: PrimaryStage
  jobs:
  - job: Build
    container: NetCoreSDK21
    pool: LinuxOnPremise
    steps:
    - script: echo "$(Message)"
```

However running this pipeline on Azure Devops Server 2019 results in the error `alpha-pipeline.yml (Line: 9, Col: 1): Unexpected value 'stages'`.

Would appreciate it if the expected use of stage templates could be added to this document, especially for Azure Devops Server.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6724abea-bbdc-bf66-ed5e-3214fa6c3e66
* Version Independent ID: 4f8dab21-3f0e-da32-cc0e-1d85c13c0065
* Content: [Job and step templates - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops-2019)
* Content Source: [docs/pipelines/process/templates.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/templates.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**
