### ISSUE TITLE
Using templates with multi-job script variables

### ISSUE THREAD

**Issue by thisispaulsmith** [MicrosoftDocs/vsts-docs#5541]
I'm having an issue with using templates where the template multi-job variables in script and the template is used more than once in the same pipeline. Probably best illustrated with an example.

pipeline.yaml
```yaml
trigger:
    - master

stages:
- stage: deploy_uat
  displayName: "UAT"
  jobs:
  - template: template.yaml
    parameters:
      Environment: "UAT"

- stage: deploy_production
  displayName: "Production"
  dependsOn: deploy_uat
  jobs:
  - template: template.yaml
    parameters:
      Environment: "Production"
```

template.yaml
```yaml
parameters:
  Environment: ''

jobs:
- job: configure_variables
  displayName: "Configure Variables"
  steps:
  - task: PowerShell@2
    name: variables
    displayName: "Calculate Variables"
    inputs:
      targetType: 'inline'
      script: echo "##vso[task.setvariable variable=NewVariable;isOutput=true;]${{ parameters.Environment }}"
  - script: echo $(variables.NewVariable)

- job: deploy
  displayName: "Deploy"
  dependsOn: configure_variables
  variables:
    Test: $[ dependencies.configure_variables.outputs['variables.NewVariable'] ]
  steps:
  - script: echo $(Test)
```

The second time the template is run the second step displays the variable from the first run. Am I missing something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6724abea-bbdc-bf66-ed5e-3214fa6c3e66
* Version Independent ID: 4f8dab21-3f0e-da32-cc0e-1d85c13c0065
* Content: [Job and step templates - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#passing-parameters)
* Content Source: [docs/pipelines/process/templates.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/templates.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**
