### ISSUE TITLE
Path trigger with YAML syntax not executing while using vairables

### ISSUE THREAD

**Issue by segraef** [MicrosoftDocs/vsts-docs#5611]
Hi,

Path trigger with YAML syntax not executing while using variables

```
variables:
  ModuleName: ApplicationSecurityGroups
  ModuleVersion: 2.0
  ModulePath: Modules/$(ModuleName)/$(ModuleVersion)

trigger:
  branches:
    include:
      - master
  paths:
    include:
    - $(ModulePath)/*
```

This trigger is working while NOT using variables in paths

```
variables:
  ModuleName: ApplicationSecurityGroups
  ModuleVersion: 2.0
  ModulePath: Modules/$(ModuleName)/$(ModuleVersion)

trigger:
  branches:
    include:
      - master
  paths:
    include:
    - Modules/ApplicationSecurityGroups/2.0/*
```
