### ISSUE TITLE
How to merge coverage for multiple VS Test tasks?

### ISSUE THREAD

**Issue by 304NotModified** [MicrosoftDocs/vsts-docs#5625]
Hi,

I'm trying to migrate to Azure Devops.

Previously I ran (stripped version):

```
nuget.exe install OpenCover -ExcludeVersion -DependencyVersion Ignore
OpenCover\tools\OpenCover.Console.exe -register:user -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:"test -f netcoreapp1.1  -c debug NLog.Extensions.Logging.Tests" -filter:"+[NLog.Extensions.Logging]* +[NLog.Extensions.Hosting]* -[NLog.Extensions.Logging.Tests]* -[NLog.Extensions.Hosting.Tests]*" -output:"coverage.xml" -oldstyle -targetdir:"test"
OpenCover\tools\OpenCover.Console.exe -register:user -mergeoutput -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:"test -f netcoreapp2.0  -c debug NLog.Extensions.Logging.Tests" -filter:"+[NLog.Extensions.Logging]* -[NLog.Extensions.Logging.Tests]*" -output:"coverage.xml" -oldstyle -targetdir:"test"
```

So running the test for multiple platforms and merge the coverage.

Now I'm doing this, but it looks like the coverage is not merged (only 79% coverage, should be 87%)

```yaml
  - task: VSTest@2
    displayName: 'test logging 1'
    inputs:
      testAssemblyVer2: "**/bin/Release/netcoreapp1.1/NLog.Extensions.Logging.Tests.dll"
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'
      codeCoverageEnabled: true
      runInParallel: true
  - task: VSTest@2
    displayName: 'test logging 2'
    inputs:
      testAssemblyVer2: "**/bin/Release/netcoreapp2.0/NLog.Extensions.Logging.Tests.dll"
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'
      codeCoverageEnabled: true
      runInParallel: true
```

How could I get the coverage merged so I will record the correct %? 

(if there is an easier way to run test and coverage for multiple platforms - and same project, please let me know)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16bd8dd1-7650-8c18-2553-38a8bc54e892
* Version Independent ID: f9fa517a-7adc-e327-d12e-256295a1ed52
* Content: [Visual Studio Test task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/vstest?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/test/vstest.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/test/vstest.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @PBoraMSFT
* Microsoft Alias: **pbora**
