### ISSUE TITLE
How to share files between stages?

### ISSUE THREAD

**Issue by ebashmakov** [MicrosoftDocs/vsts-docs#5703]
Let's say I have Build, Test, Publish, and Deploy stages:

```yml
stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - script: dotnet build
- stage: Test
  jobs:
  - job: TestJob
    steps:
    - script: dotnet test --no-build
- stage: Publish
  jobs:
  - job: PublishJob
    steps:
    - script: dotnet publish src/myProject.csproj --no-build
- stage: Deploy
  jobs:
  - job: DeployJob
    steps:
    - script: az functionapp deployment source config-zip -g myResourceGroup -n myWebApp --src myProject.zip
```
How can I share the job results (artifacts) between stages? So for example the "Deploy" stage will have "myProject.zip" file from the "Publish" stage. 
Do I have to publish artifacts after each stage? Is it possible to share files (pipeline environment) between stages automatically?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4266f72c-c774-0046-4593-d01eb775d3c3
* Version Independent ID: f20827aa-a6c5-96a8-5969-e576ffbc2e38
* Content: [Stages in Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/stages?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/stages.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/stages.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**
