### ISSUE TITLE
Cannot find any file based on /Users/vsts/agent/2.155.1/work/1/s/{APP_FILE}

### ISSUE THREAD

**Issue by li2** [MicrosoftDocs/vsts-docs#5747]
I followed the doc to set `appFile: '{APP_FILE}'`

```
  - task: AppCenterDistribute@3
    inputs:
      serverEndpoint: 'AppCenter'
      appSlug: '{APP_CENTER_SLUG}'
      appFile: '{APP_FILE}'
```
then I got the following error:
![image](https://user-images.githubusercontent.com/6058601/65665642-5bf8a100-e07f-11e9-9f43-e522fadfa6ac.png)

Finally, I fixed it by `appFile: '$(APP_FILE)'`, please update docs thanks

```
- task: AppCenterDistribute@3
  inputs:
    serverEndpoint: 'AppCenter'
    appSlug: '$(APP_CENTER_SLUG)'
    appFile: '$(APP_FILE)'
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da6643ac-ea32-1761-a7e9-0f17a3c0b8ee
* Version Independent ID: 2442af0f-3f01-a91c-a98a-29c2f32d35b9
* Content: [App Center Distribute task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/app-center-distribute?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/app-center-distribute.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/app-center-distribute.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @DavidStaheli
* Microsoft Alias: **dastahel**
