### ISSUE TITLE
Bitbucket repository resource type not documented

### ISSUE THREAD

**Issue by bkaidbb** [MicrosoftDocs/vsts-docs#5757]
According to [Repository resource type](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#type):
> Pipelines support two types of repositories, git and github. git refers to Azure Repos Git repos.

It seems Bitbucket is also supported.  I was successfully able to do the following with my pipeline:

```
resources:
  repositories:
    - repository: templates
      type: bitbucket
      name: myorg/myrepo
      endpoint: MyProject.ServiceConnection.Bitbucket
      ref: refs/heads/my-ref

steps:
- template: path/to/my-step.yml@templates
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#feedback)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**
