### ISSUE TITLE
Incorrect task name in example snippet

### ISSUE THREAD

**Issue by eloisetaylor5693** [MicrosoftDocs/vsts-docs#5824]
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops

The test task snippet has an incorrect task name (`DotNetCLI` instead of `DotNetCoreCLI`)

**Currently this:**
```yaml
# Run tests and auto publish test results.
- task: DotNetCLI@2
  inputs:
    command: 'test'
```

**Should be:**
```yaml
# Run tests and auto publish test results.
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
```
