### ISSUE TITLE
Insert local template in remote template

### ISSUE THREAD

**Issue by poltj18** [MicrosoftDocs/vsts-docs#5839]
Regarding the Insertion section of this documentation:

https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#insertion

Is it possible to reference a local template as an inserted step(s) in a remote template.

For example, I can't seem to get something like this to work:

```
# File: jobs/build.yml (remotetemplates)

parameters:
  preBuild: []
  preTest: []
  preSign: []

jobs:
- job: Build
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: cred-scan
  - ${{ parameters.preBuild }}
  - task: msbuild@1
  - ${{ parameters.preTest }}
  - task: vstest@2
  - ${{ parameters.preSign }}
  - script: sign

# File: .vsts.ci.yml

jobs:
- template: jobs/build.yml@remotetemplates
  parameters:
    preBuild:
    - template: templates/steps/my-local-steps.yml
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6724abea-bbdc-bf66-ed5e-3214fa6c3e66
* Version Independent ID: 4f8dab21-3f0e-da32-cc0e-1d85c13c0065
* Content: [Templates - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#insertion)
* Content Source: [docs/pipelines/process/templates.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/templates.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**
