### ISSUE TITLE
Using a variable for the matrix strategy

### ISSUE THREAD

**Issue by aapalm** [MicrosoftDocs/vsts-docs#5900]
The example in this page shows how you can use an output variable as your matrix strategy, however I find it is also possible to use variables as your strategy as well.

**Example**
```
variables:
  myVariable: "{'a':{'myvar':'A'}, 'b':{'myvar':'B'}}"
...
  strategy:
    matrix: $[ variables.myVariable ]
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67504b34-d64b-02a4-2e10-ab99f3b8cfe4
* Version Independent ID: 2cf63b2e-184b-7726-3b8a-d8baffd6fcce
* Content: [Jobs in Azure Pipelines, Azure DevOps Server, and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/process/phases.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/phases.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by damccorm** [comment]
Hey @aapalm, thanks for the feedback - you definitely can do that, we don't doc it because for the vast majority of use cases its probably simpler to do the following (which is what we doc and recommend):

```
strategy:
    matrix:
        a:
            myvar: A
        b:
            myvar: B
```

The reason output variables are useful for this in particular is because they can dynamically generate the matrix for the next job, if you just use normal variables you don't get that advantage.

I'm going to close since I think this is a no-op on our end.
