### ISSUE TITLE
Typos in DeleteFilesV1.md

### ISSUE THREAD

**Issue by asgeroverby** [MicrosoftDocs/vsts-docs#5903]
The documentation in [DeleteFilesV1.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/_shared/yaml/DeleteFilesV1.md) is inconsistent with the implementation.

Current:

```YAML
# Delete files
# Delete folders, or files matching a pattern
- task: DeleteFiles@1
  inputs:
    #sourceFolder: # Optional
    #contents: 'myFileShare' 
    #removeSourceFolder: # Optional
```
Should be (note the initial uppercase in the `inputs` attributes)

```YAML
# Delete files
# Delete folders, or files matching a pattern
- task: DeleteFiles@1
  inputs:
    #SourceFolder: # Optional
    #Contents: 'myFileShare' 
    #RemoveSourceFolder: # Optional
```
