### ISSUE TITLE
[Bug] Variables cannot be used in environment field

### ISSUE THREAD

**Issue by kevinhartman** [MicrosoftDocs/vsts-docs#5940]
https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#environment

Neither Stage nor Job variables can be used when specifying the environment name:

```
- deployment: MyDeployment
  dependsOn: []
  variables:
    pipelineEnv: '$(deployment.pipeline.environment)'
  pool:
    vmImage: 'Ubuntu-16.04'
  environment: '$(pipelineEnv)' # [BUG] this will get used verbatim, without de-referencing
  strategy:
    runOnce:
    ...
```

I've tried using the long-hand form as well (where environment `name` and `resourceName` are specified explicitly), but this didn't help.

Any work arounds?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#environment)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**
