### ISSUE TITLE
Parameter Condition does not work with contains?

### ISSUE THREAD

**Issue by BlairMcc** [MicrosoftDocs/vsts-docs#6001]
Here is my job condition
` condition: contains('${{ parameters.projects }}', 'customer')`

And here is the output in when the build is run

> "Evaluating: contains('$(projects)', 'customer') Expanded: contains('$(projects)', 'customer') Result: False

Am I doing something wrong?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f151218-9a11-0078-e038-f96198a76143
* Version Independent ID: 09c4d032-62f3-d97c-79d7-6fbfd89910e9
* Content: [Conditions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/conditions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/conditions.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by ArchSerpo** [comment]
For what it is worth, this was my work around that is working as expected

In an early job I do this 

- powershell: | # Work around for https://github.com/MicrosoftDocs/vsts-docs/issues/6001
         Write-Host "##vso[task.setvariable variable=localProjects;isOutput=true]${{ parameters.projects }}"
        name: setParamsToVars
        displayName: Set Params to Vars

And later in my job conditions I use this output variable combined with a dependsOn: init

condition: contains(dependencies.init.outputs['setParamsToVars.localProjects'], 'core')

**Comment by msebolt** [comment]
@ArchSerpo  Thank you for the question and posting a reliable work-around.

Can you also include the YAML that sets the parameter?

**Comment by ArchSerpo** [comment]
In my build.yml

```
name: $(majorMinor).$(patch)
trigger:
  batch: true
  branches:
    include:
    - 'deploy/*'
variables:
  majorMinor: '1.3'
  patch: $[counter(variables['majorMinor'], 0)]
  projects: 'core,customer'  

stages: 
- template: templates/template.yml
  parameters:
    majorMinor: $(majorMinor)
    patch: $(patch)
    projects: $(projects)
```

And in template.yml

```
parameters:
  majorMinor: 1.0
  patch: 0
  projects: ''

    - job: corebuild
      displayName: Core Build
      variables:                
      condition: contains('${{ parameters.projects }}', 'core')
```
