### ISSUE TITLE
Is it possible to publish a Pipeline Artifact across jobs in a single stage?

### ISSUE THREAD

**Issue by ArchSerpo** [MicrosoftDocs/vsts-docs#6042]
With build artifacts I am able to push to the same artifact name across different jobs within the same stage. 

In the example below build artifact completes without error, but pipeline artifacts gives me a "##

> [error]Artifact drop already exists for build ####."

I know I could (and probably should) move to a pipeline artifact per job, but the discrepancy has me curious

Cheers

Job 1:
```
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: manifest.txt'
      inputs:
        PathtoPublish: '$(System.DefaultWorkingDirectory)/manifest.json' 
        artifactName: drop-build-artifact         
    - task: PublishPipelineArtifact@1
      inputs:
        path: '$(System.DefaultWorkingDirectory)/manifest.json'
        artifact: drop-pipeline    
```       

Job 2:
```
- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifact: dlls'
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: drop-build-artifact

- task: PublishPipelineArtifact@1
  displayName: 'Publish Pipeline Artifact: dlls'
  inputs:
    path: '$(Build.ArtifactStagingDirectory)'
    artifact: drop-pipeline
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 861ce7a5-4fa4-55f1-2c97-46a9cc6a2f66
* Version Independent ID: bdf954b9-9bbe-8b34-b674-71ad8153519d
* Content: [Publish and consume artifacts in pipelines - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=azure-devops&tabs=yaml#single-artifact)
* Content Source: [docs/pipelines/artifacts/pipeline-artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/artifacts/pipeline-artifacts.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**
