### ISSUE TITLE
Add the possibility to include/exclude pipelines names for schedules

### ISSUE THREAD

**Issue by agneszitte-nventive** [MicrosoftDocs/vsts-docs#6055]
At the moment, if I'm adding a scheduled trigger in my yaml file, I don't have the possibility to include/exclude pipelines names.
For example, I'm adding this schedule and use the same yaml for multiple pipelines but I want to exclude one specific pipeline to use this schedule.

```
schedules:
- cron: "30 09 * * Mon-Fri"
  displayName: 'Nightly weekdays build - 4:30 EST'
  always: false
  branches:
    include:
    - master
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5673ec1-c7d1-e0ac-043a-8fc3d5b226a9
* Version Independent ID: b4872831-51c0-6cf8-1c56-de20beb38a80
* Content: [Build pipeline triggers - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/build/triggers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/triggers.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**
