### ISSUE TITLE
Multi Line not working in windows-2019

### ISSUE THREAD

**Issue by DanielHabenicht** [MicrosoftDocs/vsts-docs#6116]
Hi just tried to run 
```
- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod
  displayName: 'npm install and build'
  workingDirectory: '_interactive/decison-model'
```
but it does not execute commands after `npm install -g @angular/cli` on vmImage `windows-2019`. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a79d17fd-6e65-d8f0-ea05-f62d68456474
* Version Independent ID: 3f7338a7-aae7-b6b6-3291-5c985c6fa6f3
* Content: [Command Line task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/command-line?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/tasks/utility/command-line.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/command-line.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by DanielHabenicht** [comment]
Here the build log: https://dev.azure.com/DanielHabenicht/bachelor_thesis/_build/results?buildId=1953&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9

**Comment by vtbassmatt** [comment]
`npm` on Windows is a batch script wrapper. You must execute it using `call`, otherwise the underlying process terminates. (This is annoying, and you don't notice it on an interactive terminal, which leads to this confusion.)

```yaml
- script: |
    call npm install -g @angular/cli
    call npm install
    ng build --prod
  displayName: 'npm install and build'
  workingDirectory: '_interactive/decison-model'
```
