### ISSUE TITLE
Using expression

### ISSUE THREAD

**Issue by Jon889** [MicrosoftDocs/vsts-docs#6158]
Is it possible to use functions like coalesce? For example I want the build number to be based on the PR number, unless it was run manually, then it should use the date. Something like `name: $[coalesce(system.pullRequest.pullRequestNumber, Build.SourceBranchName)].$(Rev:r)`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a57f8545-bb15-3a71-1876-3a9ec1a59b93
* Version Independent ID: 28c87c8d-c28d-7493-0c7c-8c38b04fbcd7
* Content: [Run (build) number - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/run-number?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/run-number.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/run-number.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@Jon889  Thank you for the question.

The `coalesce` function under [functions](https://docs.microsoft.com/azure/devops/pipelines/process/expressions?view=azure-devops#functions) is supported unless you are not including a literal expression at the end of the parameter sequence or the `pullRequestNumber` is being evaluated to something other than a given value or the empty string/null value.

Please see https://github.com/Microsoft/azure-pipelines-agent/issues/1751 onr some of the caveats for using `coalesce` and comment below if any of this applies.

**Comment by StephenHodgson** [comment]
I was finally able to get my use case working by setting some variables to a string, then coalesce to either choose the macro value or keep the string null so it'll collapse correctly:

```yaml
variables:
  ${{ if eq( variables['build.reason'], 'PullRequest' ) }}:
    date: ''
  ${{ if ne( variables['build.reason'], 'PullRequest' ) }}:
    date: ${{ '$(Date:yyyyMMdd)' }}

name: ${{ coalesce( variables['date'], '$(System.PullRequest.PullRequestNumber)', 'Yet another fallback value' ) }}$(Rev:.r)
```

Hope this helps
