### ISSUE TITLE
Using other repositories mistake

### ISSUE THREAD

**Issue by roizentner** [MicrosoftDocs/vsts-docs#6187]
In both examples (Contoso/LinuxProduct and Contoso/WindowsProduct), the repository and name parameters are wrong:
```
resources:
  repositories:
    - repository: templates
      type: github
      name: Contoso/BuildTemplates
```

It should be the other way around:
```
resources:
  repositories:
    - repository: Contoso/BuildTemplates
      type: github
      name: templates
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6724abea-bbdc-bf66-ed5e-3214fa6c3e66
* Version Independent ID: 4f8dab21-3f0e-da32-cc0e-1d85c13c0065
* Content: [Templates - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#using-other-repositories)
* Content Source: [docs/pipelines/process/templates.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/templates.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**
