### ISSUE TITLE
Parameter conditions not working

### ISSUE THREAD

**Issue by phatcher** [MicrosoftDocs/vsts-docs#6222]
I can't get parameter condition to work at all, I have...

```
parameters:
    publishPackages: true

- task: NuGetCommand@2
  condition: and(succeeded(), eq('${{publishPackages}}', 'true'))
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '${{parameters.nugetFeed}}'
    allowPackageConflicts: true
```

I've tried quoting and not quoting the parameter expression/result and both return in the error...

`Unrecognized value: 'publishPackages'. Located at position 51 within expression: format('and(succeeded(), eq(''{0}'', ''true''))', publishPackages).
`

So either it's a regression or the docs are wrong.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f151218-9a11-0078-e038-f96198a76143
* Version Independent ID: 09c4d032-62f3-d97c-79d7-6fbfd89910e9
* Content: [Conditions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/process/conditions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/conditions.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
