### ISSUE TITLE
"else" and "end" for if-statement

### ISSUE THREAD

**Issue by OskarKlintrot** [MicrosoftDocs/vsts-docs#6275]
I can not find anything in the docs about working with if-statements. The example for conditional insertion only shows how to use an if-statement that conditionally turns on/off everything below it:

```yml
# File: steps/build.yml

parameters:
  toolset: msbuild

steps:
# msbuild
- ${{ if eq(parameters.toolset, 'msbuild') }}:
  - task: msbuild@1
  - task: vstest@2

# dotnet
- ${{ if eq(parameters.toolset, 'dotnet') }}:
  - task: dotnet@1
    inputs:
      command: build
  - task: dotnet@1
    inputs:
      command: test
```

What if I want to use an `else` (or equivalent) in the statement? Or close the statement? Something like this:

```yml
# File: steps/build.yml

parameters:
  toolset: msbuild

steps:
# msbuild
- ${{ if eq(parameters.toolset, 'msbuild') }}:
  - task: msbuild@1
# dotnet
- ${{ else }}:
  - task: dotnet@1
    inputs:
      command: build
  - task: vstest@2
```

or

```yml
# File: steps/build.yml

parameters:
  test: true

steps:
  - task: dotnet@1
    inputs:
      command: build
- ${{ if eq(parameters.test, 'true') }}:
  - task: vstest@2
- ${{ end; }}:
  - task: # publish artifact etc
```

Maybe not the best examples but I think you get the point. I want to use it in a template to conditionally insert a task for database-migrations if the project using it have a database. Currently I use `conditions` to solve it but then it shows up as a skipped.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6724abea-bbdc-bf66-ed5e-3214fa6c3e66
* Version Independent ID: 4f8dab21-3f0e-da32-cc0e-1d85c13c0065
* Content: [Templates - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#feedback)
* Content Source: [docs/pipelines/process/templates.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/templates.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**
