### ISSUE TITLE
Inconsistencies in templated variables documentation

### ISSUE THREAD

**Issue by denravonska** [MicrosoftDocs/vsts-docs#6316]
I'm trying to get templated variables to work inside templated steps (so far no luck) and ran into a syntax inconsistency in the documentation:

https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#variable-re-use

```
# File: vars.yml
variables:
  favoriteVeggie: 'brussels sprouts'
```

and https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=example#variable-templates

```
# File: variables/build.yml
variables:
- name: vmImage
  value: vs2017-win2016
- name: arch
  value: x64
- name: config
  value: debug
```

Which style is the correct one, or are they both valid?
