### ISSUE TITLE
Pipeline resource predefined "meta-data" variables

### ISSUE THREAD

**Issue by benc-uk** [MicrosoftDocs/vsts-docs#6350]
I'm trying to use the new pipeline resource to have my build pipeline trigger a CD/release pipeline.
I need to pass the Build.BuildId from my build to the release, which is a very common scenario

The docs mention pre-defined "pipeline-resource-meta-data" variables I can use. However none of these seem to be populated. These variables mention an `<Alias>` but it's never explained what `Alias` refers to? I tried the pipeline resource reference I used, but it didn't work

![image](https://user-images.githubusercontent.com/14982936/68751185-12492300-05f9-11ea-8ef9-ad61162e5cb7.png)

Basically the docs seem incomplete.

https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#pipeline-resource-meta-data-as-pre-defined-variables

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#resources)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by benc-uk** [comment]
Any response?
Linking pipelines together is practically pointless if you can not pass information like build-id between them

**Comment by benc-uk** [comment]
I have got this working now, e.g.

```
trigger: none

resources: 
  pipelines:
  - pipeline: buildpipeline
    source: My Build Pipeline
    trigger: true

jobs:
- deployment: deployToAKS

  pool:
    vmImage: ubuntu-latest

  strategy:
    runOnce:
      deploy:
        steps:
        - download: buildpipeline
          artifact: helm-charts
        - bash: echo "Build run name was: $(resources.pipeline.buildpipeline.runName)"
```

I still think a worked example of CI & CD separated across two pipelines is badly needed in the docs
