### ISSUE TITLE
Need clarification on pipeline resource completion trigger

### ISSUE THREAD

**Issue by sugarjig** [MicrosoftDocs/vsts-docs#6363]
The section for pipeline resources says "And you can also enable pipeline completion triggers." What is a pipeline completion trigger? Is that when the dependent pipeline completes successfully?  If so, it is not clear how this is achieved. Is it done through the `trigger` key? Also the example shows several different uses, but it's not clear what they do:
```
resources: 
  pipelines:
  - pipeline: MyAppA 
    source: MyCIPipelineA
  - pipeline: MyAppB
    source: MyCIPipelineB
    trigger: true
  - pipeline: MyAppC
    project:  DevOpsProject 
    source: MyCIPipelineC
    branch: releases/M159  
    version: 20190718.2 
    trigger:
      branches:  
        include:  
        - master
        - releases/*
        exclude:   
        - users/*  
```
The first pipeline resource has no triggers defined. What happens in this case? The second has `trigger: true`. What does that do exactly?

Also, how do these triggers interact with any triggers defined at the pipeline level?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#resources)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**
