### ISSUE TITLE
Using other repositories: How to use variables

### ISSUE THREAD

**Issue by yangao22** [MicrosoftDocs/vsts-docs#6422]
```
variables:
  - name: branchname
    value: 'my-branch'

resources:
  repositories:
    - repository: templates
      type: github
      name: Contoso/BuildTemplates
      ref: $(branchname)

jobs:
    .....
```

I want to use the variable `branchname` for my template repo's branch, and I got the error 

> could not get the latest source version for repository xxx hosted on xxx using ref refs/head/$(branch name)

If the branch name is hardcoded in repository.ref, it works. Assume the branch exists on the repo and no typo.

What's the correct format of using variables using other repositories?
