### ISSUE TITLE
Variable Availability during compile/parse-time vs run time

### ISSUE THREAD

**Issue by JoeBrockhaus** [MicrosoftDocs/vsts-docs#6534]
From above: 

> Another common use of expressions is in defining variables. Expressions can be evaluated at compile time or at run time. Compile-time expressions can be used anywhere; runtime expressions are more limited.
> 
> The difference between these syntaxes is primarily what context is available. In a parse time expression, you have access to parameters and statically-defined variables. In a runtime expression, you have access to more variables but no parameters.

I'm looking to understand _exactly which variables_ are available during each of these phases, because it seems there are some subtle differences, specifically around _queue-time_ variables.  

**_To be very specific: I would like to control conditional insertion at the root pipeline based on a manually-entered queue-time variable._** 

#### For instance:
- At _parse-time_, if only _statically-typed_ variables are available, how am I able to perform conditional insertion with supposed _queue-time_ variables like `build.sourcebranch`? 
  ```yml
    - template: template.yml
      parameters:
        ${{ if eq(variables['build.sourcebranch'], 'refs/head/master') }}:
          param_1: value a
        ${{ if ne(variables['build.sourcebranch'], 'refs/head/master') }}:
          param_1: value b
  ```

- However 'normal' _queue-time_ variables are unavailable. That is, a variable not defined in the YAML, but is added in the UI when triggering a new build in AzureDevOps: 
  - This works fine _(statically-typed)_: 
    ```yml
      variables:
        releaseBranchName: 'refs/head/master'

      - template: template.yml
        parameters:
          ${{ if eq(variables['build.sourcebranch'], variables['releaseBranchName']) }}:
            param_1: value a
          ${{ if ne(variables['build.sourcebranch'], variables['releaseBranchName']) }}:
            param_1: value b
    ```

  - But I've been unable to support manually overriding conditional insertion based on a 'normal' queue-time variable supplied from the UI  _(ie: `releaseBranchNameOverride`)_: 
    ```yml
      variables:
        # expected to work
        releaseBranchName: ${{ coalesce(variables['releaseBranchNameOverride'], 'refs/head/master') }}
        # not expected to work (runtime expressions are processed after compile-time, so conditional insertion can't be based on a runtime expression)
        # releaseBranchName: $[coalesce(variables['releaseBranchNameOverride'], 'refs/head/master')]
    
      - template: template.yml
        parameters:
          ${{ if eq(variables['build.sourcebranch'], variables['releaseBranchName']) }}:
            param_1: value a
          ${{ if ne(variables['build.sourcebranch'], variables['releaseBranchName']) }}:
            param_1: value b
    ```

  - _In the commented-out runtime expression, accessing `releaseBranchName` as part of a Task, **or even in a condition**, would result in the expected value, which is confusing at first._ This is one reason folks may want Template expansion to support Conditions, though I understand that's a runtime concern _(perhaps solved w/ Condition projection on compilation?)_. 
   
  - The latter results in the following `InitializePipeline.txt` when run against the branch `refs/pull/1/merge` and with `releaseBranchNameOverride` of `refs/pull/1/merge`: 
    ```
    Begin evaluating template 'template.yml'
    Evaluating: coalesce(variables['releaseBranchNameOverride'], 'refs/head/master')
    Expanded: coalesce(Null, 'refs/head/master')
    Result: 'refs/head/master'
    Evaluating: coalesce(variables['build.sourcebranch'], 'source-branch')
    Expanded: coalesce('refs/pull/1/merge', 'source-branch')
    Result: 'refs/pull/1/merge'
    Begin transform: variables
    Evaluating: value
    Result: Object
    Evaluating: pair['key']
    Result: 'releaseBranchName'
    Evaluating: pair['value']
    Result: 'refs/head/master'
    Evaluating: pair['key']
    Result: 'sourceBranchName'
    Evaluating: pair['value']
    Result: 'refs/pull/1/merge'
    End transform: variables
    ```

  - The end result: Despite being a 'static' (not expression) + known 'queue-time' value _(which is seemingly known prior to running the pipeline)_, Template Parameter **`param_1`** will not resolve to **`value a`** when a matching override value for `releaseBranchNameOverride` is supplied at queue-time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c58a78-a567-e99a-9eb7-62dddd1b90b6
* Version Independent ID: 680a79bc-11de-39fc-43e3-e07dc762db18
* Content: [Expressions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops)
* Content Source: [docs/pipelines/process/expressions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/expressions.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
