### ISSUE TITLE
DotNetCLI@2 pack seems to be ignoring configuration inputs

### ISSUE THREAD

**Issue by nuno-barreiro** [MicrosoftDocs/vsts-docs#6545]
The below YAML snippet does not seem to work as expected.
I configured it in a pipeline that runs using the windows-latest image and it attempts to restore all of the projects that are in the repo, instead of looking just to the solution file.
Also, it seems to completely ignore the --no-restore flag

```
    - task: DotNetCoreCLI@2
      displayName: Package to Staging directory
      inputs:
        command: pack
        configuration: $(BUILD_CONFIGURATION)
        projects: 'support-libs.sln'
        packDirectory: $(Build.ArtifactStagingDirectory)
        nugetConfigPath: 'sf-solution/nuget.config'
        arguments: '--no-restore'
        verbosityRestore: Minimal
```

The command that appears on the step logs is:

```
"C:\Program Files\dotnet\dotnet.exe" pack d:\a\1\s\sf-solution\SampleProject\SampleProject.csproj --output d:\a\1\a /p:Configuration=Debug --verbosity Detailed
```

The above project is not included in the support-libs SLN file the snippet has configured.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d1d9884-19f7-592b-f47c-8cf100639ff0
* Version Independent ID: 555c3826-60d9-2589-54af-850efbfbb13a
* Content: [.NET Core CLI task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/build/dotnet-core-cli.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/dotnet-core-cli.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @pulkitaggarwl
* Microsoft Alias: **puagarw**
