### ISSUE TITLE
Possible error in Environment stanza 

### ISSUE THREAD

**Issue by a30001539** [MicrosoftDocs/vsts-docs#6643]
The full definition at https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#environment, indicates that the 'strategy' element can be declared inside the 'environment' stanza, but if you do that you get an error.

/provisioning/azure_devops_templates/jobs/sql.yaml (Line: 12, Col: 7): Unexpected value 'strategy'

My yaml looks like this

jobs:
- deployment: deploy_sql
  pool: Windows-Domain
  environment:
    name: ${{ parameters.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
          - script etc etc

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#feedback)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@a30001539 Thank you for the feedback, assigning this to the author review.

**Comment by steved0x** [comment]
#reassign:juliakm

**Comment by RoopeshNair** [comment]
Yaml is space sensitive, it is not clear from the sample, if you are indenting it correctly.

```yaml
jobs:
- deployment: deploy_sql
  pool:                # see pool schema
    name: Windows-Domain
  environment: ${{ parameters.environment }}
  strategy:
    runOnce:
      deploy:
        steps:
        - script: echo hello world
```
