### ISSUE TITLE
Explicit documentation for the option feedRestore that is not usable for dotnet test

### ISSUE THREAD

**Issue by christopheblin** [MicrosoftDocs/vsts-docs#6666]
If you use

```
jobs:
- job: Build_and_test 
  steps:
  - task: DotNetCoreCLI@2
    displayName: "Xxx.sln"
    inputs:
      command: 'test'
      workingDirectory: 'Xxx'
      feedsToUse: 'select'
      feedRestore: 'xxx/xxx #private feed
      includeNuGetOrg: true
```

Then the feedRestore (and other options) are simply ignored and the build fails with an error saying `error NU1101: Unable to find package XXX. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org`

The solution is to explicitly have restore > build > test tasks but this should be explicitly added to the documentation (maybe in troubleshooting section)

There are more details in https://stackoverflow.com/a/59317254/1545567

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d1d9884-19f7-592b-f47c-8cf100639ff0
* Version Independent ID: 555c3826-60d9-2589-54af-850efbfbb13a
* Content: [.NET Core CLI task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/dotnet-core-cli.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/dotnet-core-cli.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @pulkitaggarwl
* Microsoft Alias: **puagarw**
