### ISSUE TITLE
Fails when running in a deployment job

### ISSUE THREAD

**Issue by JaDevGuy** [MicrosoftDocs/vsts-docs#6683]
When used in a deployment job you get this message 
"Checkout of repository 'MyRepoAlias' is not supported. Only 'self', 'none', or a repository alias are supported"
If specifying an inline reference it gives this instead 
"The checkout step references the repository 'git://DemoProj/MyRepo@refs/head/master' which is not defined by the pipeline"

Any idea when deployment jobs will support this feature?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a0499c0-bd1c-47a0-b472-54a5d6c159b4
* Version Independent ID: ec3feae0-4f23-68ab-6307-75fde645468a
* Content: [Check out multiple repositories in your pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/multi-repo-checkout?view=azure-devops#feedback)
* Content Source: [docs/pipelines/repos/multi-repo-checkout.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/repos/multi-repo-checkout.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 

Also, the product teams aren’t always watching this repository, so to make sure it gets in front of them for triage, please [submit your idea]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21) here.

**Comment by arammaliachi** [comment]
Currently investigating, apologies for the inconveniences. As a workaround please turn all of the jobs with checkout steps to be 'regular' jobs by calling them as - job: instead of - deployment:

https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml#specifying-jobs

**Comment by jpricket** [comment]
@JaDevGuy - Thanks for reporting this issue. I created a bug and I have a fix that should get in this week, but because of the holidays, it won't start rolling out until January sometime. Sorry for the oversight.

**Comment by JaDevGuy** [comment]
Thanks @jpricket ! I'll standby for the fix and test again once it's ready. Appreciate the quick turnaround!

**Comment by Doomblaster** [comment]
> 
> 
> @JaDevGuy - Thanks for reporting this issue. I created a bug and I have a fix that should get in this week, but because of the holidays, it won't start rolling out until January sometime. Sorry for the oversight.

any idea when in january it's rolling out?

**Comment by jpricket** [comment]
The fix has rolled out to our first ring already. It should be completely rolled out in the next 3 weeks.

**Comment by JoeBrockhaus** [comment]
> The fix has rolled out to our first ring already. It should be completely rolled out in the next 3 weeks.

@jpricket I've recently noticed some unexpected logic failures in some of our repos that all depend on some standard templates, and it's related to the value of the built-in `variables['build.sourcebranch']`. 

In particular, this variable previously returned `refs/head/master`, but now it returns `refs/heads/master` _(the additional `s` on `heads`)_. 

I'm curious if that is related to this fix, or if this was part of another change, and if there is any documentation of this _(breaking, for us)_ change we can refer to in documenting this change?

**Comment by jpricket** [comment]
@JoeBrockhaus I don't think that is related to my changes, but refs/heads/ is the correct prefix. This variable should come directly from the server. The agent just passes it along.
@leantk Do you know of any changes in the build.sourcebranch variable lately?

**Comment by jontreynes** [comment]
I'm running into this issue with windows-latest using deployment job

Code looks like

**main.yml**
```
resources:
  repositories:
  - repository: adf_publush
    type: git
    name: my_data
    ref: adf_publish

stages:

- template: deploy.yml
  parameters:
    varPath: config/common/variables.yml
    envVarPath: config/dev/variables.yml
    environment: dev
```

deploy.yml
```
parameters:
  - name: varPath
    type: string
    displayName: "varPath: The path to the common variable template"
  - name: envVarPath
    type: string
    displayName: "varPath: The path to the common variable template"
  - name: environment
    type: string
    displayName: "environment: The name of the environment to deploy"

stages:
- stage: deploy_${{parameters.environment}}
  displayName: ${{parameters.environment}} Deploy
  variables:
  - template: ${{parameters.varPath}}
  - template: ${{parameters.envVarPath}}
  jobs:
  - template: ./templates/adf_pre_deploy.yml
    parameters:
      environment: ${{parameters.environment}}
      agent_pool: $(agent_pool)
```
adf_pre_deploy.yml
```
parameters:
  - name: environment
    type: string
    displayName: "environment: The name of the environment to deploy"
  - name: agent_pool
    type: string
  - name: adfPublishBranch
    type: string
    default: adf_publish


jobs:
- deployment: deploy
  displayName: ${{parameters.environment}} deploy
  environment: ${{parameters.environment}}
  pool:
    vmImage: ${{parameters.agent_pool}}
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
          persistCredentials: true
        - checkout: ${{parameters.adfPublishBranch}}
```
and I receive

![image](https://user-images.githubusercontent.com/19974635/133114952-2dfad13b-b8fe-4e9f-974b-88bdc25adbf1.png)
