### ISSUE TITLE
runtime expression with coalesce includes variables

### ISSUE THREAD

**Issue by NewFuture** [MicrosoftDocs/vsts-docs#6777]
```yaml
variables:  
  CONTAINER_NAME: $[coalesce(variables.CONTAINER_NAME, 'web')]
steps:
  - bash: echo '$(CONTAINER_NAME)'
```
the output will be ` $[coalesce(variables.CONTAINER_NAME, 'web')]` (the expression it self, not the value)
So, how to use it with the expressions with user defined variables (in yaml or pipelines)?

---
#### 文件的詳細資料

⚠ *請勿編輯此部分。 docs.microsoft.com 必要 ➟ 連結 GitHub 問題。*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Variables - Azure Pipelines](https://docs.microsoft.com/zh-hk/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#feedback)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
