### ISSUE TITLE
Unable to download  Build Artifacts in build pipeline

### ISSUE THREAD

**Issue by vipulnewaskar7** [MicrosoftDocs/vsts-docs#6790]
I have 2 Projects say - A and B Both have a build and release pipeline.

I want to use artifacts published by build pipeline of **Project A** in "**Build Pipeline**" of **Project B**.
So for this I tried using both tasks 

1. Download Build Artifacts 
2. Download Pipeline Artifacts

I provide Project Name , Pipeline Name  in the task from the dropdown menu.
When I run pipeline, I get 

> VS800075: The project with id 'vstfs:///Classification/TeamProject/XXXXXXXX-XXXX-XXXX-XXXXXXXXXXXX' does not exist, or you do not have permission to access it.

**NOTE : I can use those artifacts in "Release Pipeline" of Project B**
**So don't seem it as a permission issue**
**Since I have selected Project and Build Pipelines from dropdown menu, no chance of putting wrong project ID**

**Comment by WilliamAntonRohm** [comment]
@vipulnewaskar7 -- Vipul, thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around the general task.  

Meanwhile, you may find additional information here:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

**Comment by dkmiller** [comment]
I can reproduce this issue. The relevant task looks like:

```yml
- task: DownloadBuildArtifacts@0
  displayName: Download AnE.Wiki.Redirection
  inputs:
    buildType: specific
    project: 21fa5fbd-1bc8-4dc5-a421-77bc81fac831
    pipeline: 300
    buildVersionToDownload: latestFromBranch
    artifactName: drop
```

and identical code works in other projects.
