### ISSUE TITLE
Variable syntax does not work in templates

### ISSUE THREAD

**Issue by mtaylorfsmb** [MicrosoftDocs/vsts-docs#6890]
Trying to use variables inside a template as discussed here doesn't work. When you run the build it says `variables` is an unexpected value. It doesn't matter whether the variables section precedes or follows the parameters. 

```yaml
parameters:
  version: ""
  isPrerelease: ""
  buildLabel: ""

# Fails here with 'unexpected value variables`
variables:
  GitVersion.SemVer: ''
  UseGitVersion: false

steps:
- template: read-propsfile.yml
```
Note that elsewhere it is mentioned the syntax for variables is as follows but that doesn't work either.

```yaml
variables:
- name: SomeVar
   value: true
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6724abea-bbdc-bf66-ed5e-3214fa6c3e66
* Version Independent ID: 4f8dab21-3f0e-da32-cc0e-1d85c13c0065
* Content: [Templates - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops)
* Content Source: [docs/pipelines/process/templates.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/templates.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@mtaylorfsmb Thank you for the feedback, assigning this to the author for review.

**Comment by ElvenSpellmaker** [comment]
@mtaylorfsmb You can't assign variables at the `step` level, only at `job`, `stage`, and `global.

**Comment by juliakm** [comment]
As @ElvenSpellmaker mentioned, your variables are in the wrong spot. Here's a rewritten version. 

```
# File: azure-pipelines.yml

parameters:
- name: version
  type: string
  default: ""

variables:
# a regular variable
- name: UseGitVersion
  value: false
# a reference to a variable template
- template: vars.yml  # Template reference

trigger: none

steps:
- script: echo My favorite vegetable is ${{ variables.favoriteVeggie }}.
```

```
# vars.yml
# File: vars.yml
parameters:
  version: ""

variables:
  favoriteVeggie: 'brussels sprouts'
```
I'll add a more complex example to the docs.
