### ISSUE TITLE
Is 'include:' required under 'branches:' for a pipeline trigger?

### ISSUE THREAD

**Issue by cacti77** [MicrosoftDocs/vsts-docs#6914]
In the first YAML example under https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#pipeline-triggers there is no 'include:' item under 'branches:' but in the other examples there is an 'include:' item.  So is 'include:' optional or required?

The schema comments at https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#pipeline-resource don't clarify this either.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5673ec1-c7d1-e0ac-043a-8fc3d5b226a9
* Version Independent ID: b4872831-51c0-6cf8-1c56-de20beb38a80
* Content: [Build pipeline triggers - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#pipeline-triggers)
* Content Source: [docs/pipelines/build/triggers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/triggers.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by Michaelvsk** [comment]
It is optional. If you specify branch names directly below `branches:` then it means include these branches. 
Example: Get triggered by build in release/* and master branches
```
resources:
  pipelines:
  - pipeline: SmartHotel
    source: SmartHotel-CI 
    trigger: 
      branches:
      - releases/*
      - master
```
However sometimes you want to include some branches using wildcards and but exclude others, then include and exclude keywords become handy:

Get triggered by all release/* branches except the ones in /release/old/*. So release/1.20 would trigger your pipeline but /release/old/0.2.0 would not:
```
resources:
  pipelines:
  - pipeline: SmartHotel
    source: SmartHotel-CI 
    trigger: 
      branches:
        include: 
        - releases/*
        exclude:
        - release/old/*
```

Some more info about the resource schema: https://github.com/microsoft/azure-pipelines-yaml/blob/master/design/pipeline-triggers.md#pipelines
