### ISSUE TITLE
Has anyone tried using this task on a VSTS agent container?

### ISSUE THREAD

**Issue by worldspawn** [MicrosoftDocs/vsts-docs#6927]
Seems like docker is not installed on the agent container, this task fails with docker not found.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77386c22-1c7f-ab78-f541-52d50fa9fd8e
* Version Independent ID: be836c7f-2b53-c59a-7252-dfc15ec63537
* Content: [Docker task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/build/docker.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/docker.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @shashankbarsin
* Microsoft Alias: **shasb**

**Comment by worldspawn** [comment]
If its not compatible it would be nice to note that here.

**Comment by msebolt** [comment]
@worldspawn Thank you for the feedback, we're sorry for the issues with the container.

Please try a newer container such as [Windows 1803](https://github.com/Microsoft/azure-pipelines-image-generation/releases) with Docker pre-installed.

Assigning this to the author for review.

**Comment by worldspawn** [comment]
Yes apparently I needed to do more reading :)

FYI I used `microsoft/vsts-agent:ubuntu-16.04-docker-18.06.1-ce-standard`. The `docker` gives you docker obviously, the `standard` gives you everything else.

``` yaml
apiVersion: v1
kind: ReplicationController
metadata:
  name: vsts-agent
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vsts-agent
    spec:
      containers:
      - name: vsts-agent
        image: microsoft/vsts-agent:ubuntu-16.04-docker-18.06.1-ce-standard
        env:
          - name: VSTS_ACCOUNT
            value: drawboard
          - name: VSTS_TOKEN
            value: supersecretcode
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-volume
      volumes:
      - name: docker-volume
        hostPath:
          path: /var/run/docker.sock
```
