### ISSUE TITLE
Mixing template variables with non-template variables

### ISSUE THREAD

**Issue by AlexDenton** [MicrosoftDocs/vsts-docs#6948]
Some of my variables change between pipelines. Some don't. What I'd like to do is something like:

```
variables:
- template: some-variables.yml
  parameters:
    someParameters: someValue
  someVariable1: someValue1
  someVariable2: someValue2
```

If I run that right now I get an error: `Unexpected value 'someVariable1'`. 

Is there someway of doing this that I'm just not aware of?

Edit: I botched the sample code and just updated it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6724abea-bbdc-bf66-ed5e-3214fa6c3e66
* Version Independent ID: 4f8dab21-3f0e-da32-cc0e-1d85c13c0065
* Content: [Templates - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#feedback)
* Content Source: [docs/pipelines/process/templates.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/templates.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
