### ISSUE TITLE
Documentation on expressions is missing information about "if" statements

### ISSUE THREAD

**Issue by DaRosenberg** [MicrosoftDocs/vsts-docs#6989]
Expressions are useful to calculate a value, sure.
Expressions are also useful in the places in YAML that explicitly support conditions, sure.

However, without the ability to do things conditionally based on the result of expressions, their usefulness is limited. For example:
- Conditionally assign the value of a variable based on an expression
- Conditionally set inputs on a task based on an expression

It turns out this is possible using conditional insertion syntax, but it was extremely difficult to find because it's only documented in relation to templates. It should be documented, or at least referred to, in the documentation page for expressions, because a) it is actually not specific to using templates and b) this is the place you would be looking.

It works fine even without loading an external template to do this, for example, to conditionally set different properties of a task:

```yaml
- task: DotNetCoreCLI@2
  displayName: Package
  inputs:
    command: pack
    packagesToPack: src/SomeProject/*.csproj
    packDirectory: $(Build.StagingDirectory)
    ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
      versioningScheme: byEnvVar
      versionEnvVar: PACKAGE_VERSION
    ${{ if ne(variables['Build.SourceBranchName'], 'master') }}:
      majorVersion: $(major)
      minorVersion: $(minor)
      patchVersion: $(patch)
      versioningScheme: byPrereleaseNumber
```

It also works fine to do this to conditionally set variables:

```yaml
variables:
  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
    stackName: prod
  ${{ if ne(variables['Build.SourceBranchName'], 'master') }}:
    stackName: dev
```

This information should not be buries in the documentation on templates, because it's not specific to templates and has more to do with expressions in general and how to apply them to do things conditionally.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c58a78-a567-e99a-9eb7-62dddd1b90b6
* Version Independent ID: 680a79bc-11de-39fc-43e3-e07dc762db18
* Content: [Expressions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#feedback)
* Content Source: [docs/pipelines/process/expressions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/expressions.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by DaRosenberg** [comment]
On a related note (and I know this is more of a product feedback than a documentation issue) it's worth mentioning that it would be extremely useful to have an `if()` function available in the expression syntax.

So instead of:
```yaml
variables:
  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
    stackName: prod
  ${{ if ne(variables['Build.SourceBranchName'], 'master') }}:
    stackName: dev
```

We could do:
```yaml
variables:
    stackName: ${{ if(eq(variables['Build.SourceBranchName'], 'master'), 'prod', 'dev' }}
```

It would also be very useful to have an `else` statement so we could do:
```yaml
variables:
  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
    stackName: prod
  ${{ else }}:
    stackName: dev
```
