### ISSUE TITLE
Multi-line script format isn't clear

### ISSUE THREAD

**Issue by KyMidd** [MicrosoftDocs/vsts-docs#7076]
Hey team, 

In the YML guidelines it says we can use a pipe | character to send multi-line input to commands. This doesn't appear to work for the script attribute of the bash tool. Is it possible to have documentation added to show how to get a multi-line script to work? I am testing and have not found a way yet. 

Here's what I've attempted and it seems to combine the commands into an invalid string. 
- task: Bash@3
              displayName: 'Do things'
              inputs:
                targetType: 'inline'
                script: |
                  'command 1'
                  'command 2'
                  'command 3'
                workingDirectory: $(working_directory)
                failOnStderr: true

**Comment by msebolt** [comment]
@KyMidd Thank you for the feedback.

Assigning this to the author of [Bash task](https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/bash) for further review.

**Comment by vtbassmatt** [comment]
@KyMidd in the [YAML basics](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#yaml-basics) section, we link out to [Learn YAML in Y Minutes](https://learnxinyminutes.com/docs/yaml/), which is a pretty good overview of YAML syntax. Your problem is the extraneous `'`s. It should read:

```yaml
- task: Bash@3
  displayName: 'Do things'
  inputs:
    targetType: 'inline'
    script: |
      command 1    # no quotes needed
      command 2
      command 3
  workingDirectory: $(working_directory)
  failOnStderr: true
```

@msebolt for future routing, this is a YAML formatting question, not a Bash task question.
