### ISSUE TITLE
Devops KubernetesManifest@0 Container replace

### ISSUE THREAD

**Issue by rauntska** [MicrosoftDocs/vsts-docs#7181]
Hi,

Using the KubernetesManifest@0 in devops pipeline in two builds.
1. for a regular pod deployment (this one works fine)
2. for a cronjob deployment ( does not work)

Seems like the Containers command is not working for the  cronjob deployment. Meaning that the image field is not replaced. To be exact - the ':tag' field is not updated. When checking from the kubernetes dashboard- i see that the tag has not updated.

The only difference as to the regular pod deployment is the "jobTemplate" field in the  'dev_my-docker.yml' file. Could this be causing some issues that the replacing will not work ?

```
          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: 'deploy'
              kubernetesServiceConnection: 'connection'
              namespace: 'default'
              manifests: '$(System.ArtifactsDirectory)/manifests/dev_my-docker.yml'
              containers: '$(containerRegistry)/$(imageRepository):$(tag)'
              imagePullSecrets: '$(imagePullSecret)'
```
the content for the cronjob 'dev_my-docker.yml'

```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name:x_repox
spec:
  schedule: "0 */6 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: baseline-calculate
              image: mystuff.azurecr.io/x_repo
              envFrom:
              - configMapRef:
                  name: global-config
          restartPolicy: OnFailure           
          imagePullSecrets:
            - name: password
```

BR,
Rauno
