### ISSUE TITLE
Missing function to check whether an object contains a key

### ISSUE THREAD

**Issue by couven92** [MicrosoftDocs/vsts-docs#7219]
According to the documentation, there is no function that can be used to check whether an object (a YAML mapping) contains a key or not. You can iterate over the key-value-pairs in an object (`each`) and you can check whether any of the keys in an object has a specified value `containsValue`.

I would like to request a function `containsKey(object, key)` with the following properties:
* if `object` is an Object, return `True` if there is a key in `object` that is equal to `key` casted to a `string`.
* if `object` is an array (a YAML sequence), return `True` if `key` can be converted to a number that is an integer and less than equal to the length of `object`.
* otherwise return `False`

In essence the `containsKey` function would return `True` in all cases where doing `object[key]` would return a meaningful value.

Since you can pass `null` into the key of an object using the following literal expression
``` yaml
object:
  key: ${{ null }}
```
the expression `eq(null, object.key)` is not sufficient to determine whether `key` is present as a key within `object`. In the example above, iterating over `object` would yield a key-value-pair with the `key` being equal to `'key'` and `value` being equal to `null`.

My use-case for this specifically is that I need to merge two objects while adding possibly missing keys from default values. I do that the following way:
``` yaml
left:
  foo: ${{ null }}
  bar: This is foobar from bar
right:
  foo: Hmmm
  baz: Maybe
merged:
  # I only specifically know how to handle foo
  ${{ if containsValue(left, 'foo') }}:
    foo: ${{ left.foo }}
  ${{ if not(containsValue(left, 'foo')) }}:
    foo: default value
  
  # insert additional keys of left
  ${{ each pair in left }}:
    ${{ if notIn(pair.key, 'foo') }}:
      ${{ pair.key }}: ${{ pair.value }}

  # insert additional keys of right (except those already in left)
  ${{ each pair in right }}:
    ${{ if and(notIn(pair.key, 'foo'), not(containsKey(left, pair.key))) }}:
      ${{ pair.key }}: ${{ pair.value }}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c58a78-a567-e99a-9eb7-62dddd1b90b6
* Version Independent ID: 680a79bc-11de-39fc-43e3-e07dc762db18
* Content: [Expressions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops)
* Content Source: [docs/pipelines/process/expressions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/expressions.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
