### ISSUE TITLE
How I can pass agent workdir to service container volume

### ISSUE THREAD

**Issue by sseliverstov** [MicrosoftDocs/vsts-docs#7249]
[Enter feedback here]
This one does not work:
```
resources:
  containers:
  - container: myservice
    image: my/image
    volumes:
    - $(Agent.BuildDirectory)/hostdir:/servicedir
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d1c794c-d676-fc7e-758e-3464f16a1554
* Version Independent ID: 941de04a-2d34-ec82-8612-00e4070de673
* Content: [Service Containers - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/service-containers?view=azure-devops&tabs=yaml#volumes)
* Content Source: [docs/pipelines/process/service-containers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/service-containers.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by WilliamAntonRohm** [comment]
@sseliverstov -- Stanislav, thank you for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please provide more context around your general task.

**Comment by sseliverstov** [comment]
I have an external report system that shows the testing process in real-time, it accepts results for every test in internal format. For the CI integration, we have a client wrapped to the docker image. It watches to results directory and sends all new files. So I need to start it before tests execution and grant access to the test-result directory. Azure Pipeline's services look good, but I hadn't found any example of how to pass the right path to the working directory to volumes on service configuration stage. If you have any recipe how it possibly makes in another way, it will be great too.

**Comment by WilliamAntonRohm** [comment]
@sseliverstov -- Stanislav, thank you for clarifying. Are you reading a specific docs.microsoft.com article?

**Comment by pburls** [comment]
@sseliverstov did you ever find a way to do this? 
I am also trying to mount a volume but binding to a path in source code checked out on the host using `$(Build.SourcesDirectory)`
e.g. 
```
resources:
  containers:
  - container: myservice
    image: my/image
    volumes:
    - $(Build.SourcesDirectory)/hostdir:/servicedir
```
