### ISSUE TITLE
Multiple Sets of Stages Templates and linkage

### ISSUE THREAD

**Issue by joshuaquek** [MicrosoftDocs/vsts-docs#7275]
Under here : https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#stage-reuse 
it is mentioned that one can link a set of stages to another file like this:

```
stages:
- template: 'templates/stages.yml'
```

However, is it possible to do the following?

```
stages: 
- template: './somefolder/my-first-set-of-stages.yml'
stages: 
- template: './somefolder/my-second-set-of-stages.yml'
```

and even if this possible, how does a stage within 'my-first-set-of-stages.yml' link to another stage from within 'my-second-set-of-stages.yml' ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6724abea-bbdc-bf66-ed5e-3214fa6c3e66
* Version Independent ID: 4f8dab21-3f0e-da32-cc0e-1d85c13c0065
* Content: [Templates - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#stage-reuse)
* Content Source: [docs/pipelines/process/templates.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/templates.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@joshuaquek I think that the problem is that you are declaring `stages` twice in your pipeline. I'm assuming that's your first code sample is `azure-pipelines.yml`. Here's an overly complicated example of using multiple templates. Stage D's template in is included in Stage C's template. 

azure-pipelines.yml
```
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: parta
  displayName: Part A
  jobs: 
    - job: jobone
      displayName: Job One
      steps:
      - task: Npm@1
        inputs:
          command: 'install'
- template: templates/stageb.yml
- template: templates/stagec.yml
```

templates/stageb.yml
```
stages:
- stage: partb
  displayName: Part B
  jobs:
  - job: jobtwo
    displayName: Job Two
    steps:
      - script: 'echo Hello world'
```

templates/stagec.yml
```
stages:
- stage: partc
  displayName: Part C
  jobs:
  - job: jobtwo
    displayName: Job Three
    steps:
      - script: 'echo Hello again'
- template: staged.yml
```

templates/staged.yml
```
stages:
- stage: partd
  displayName: Part D
  jobs:
  - job: jobtwo
    displayName: Job Four
    steps:
      - script: 'echo Hello D'
```
