### ISSUE TITLE
Document is very outdated

### ISSUE THREAD

**Issue by mydiemho** [MicrosoftDocs/vsts-docs#7358]
When you view the yaml after creating the Bash task in UI, the configuration is completely different.  Please get this updated

```
steps:
- task: Bash@3
  displayName: 'run pandoc'
  inputs:
    targetType: filePath
    filePath: ./sample.sh
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80c8d60d-0b2d-d225-8cfb-f21d3350caa2
* Version Independent ID: 23398b3a-d23f-ea88-6b75-e9dafc4838a3
* Content: [Shell Script task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/shell-script?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/shell-script.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/shell-script.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**
