### ISSUE TITLE
No (documented?) way to access a service contain from a host

### ISSUE THREAD

**Issue by wichert** [MicrosoftDocs/vsts-docs#7463]
I am runing a CI task on a host machine, on a `ubuntu-18.04` image on a MS-hosted agent. The task needs PostgreSQL, so I am running it like this:

```yaml


resources:
  containers:
    - container: postgresql
      image: circleci/postgres:12-ram
      ports:
        - 5432:5432
jobs:
  - job: test
    displayName: Run tests

    pool:
      vmImage: ubuntu-18.04

    services:
      postgresql: postgresql

    steps:
      - template: steps-python.yml

      - script: poetry run py.test --junitxml=TEST-pytest.xml --sql-uri=postgresql://localhost/circle_test
        displayName: Run tests
```

This always fails:

```
E       OperationalError: could not connect to server: Connection refused
E       	Is the server running on host "localhost" (127.0.0.1) and accepting
E       	TCP/IP connections on port 5432?
```

Is there a way to make this work? Or is required to run CI steps inside a container as well to allow access to service containers?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d1c794c-d676-fc7e-758e-3464f16a1554
* Version Independent ID: 941de04a-2d34-ec82-8612-00e4070de673
* Content: [Service Containers - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/service-containers?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/service-containers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/service-containers.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by WilliamAntonRohm** [comment]
Thanks for your questions. You may find answers here: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by nazarsh** [comment]
@WilliamAntonRohm Could you please point me to the specific instructions for it? Neither of the links above contained an answer to this question (from what I can tell) and I am facing the same issue as @wichert
Thanks!

**Comment by nazarsh** [comment]
Followup for anybody who ended up having the same issue:
My co-worker pointed out that Dockerhub's Postgres documentation requires a POSTGRES_PASSWORD  env variable to be set.

You would do it like so
```
resources:
  containers:
  - container: postgres
    image: postgres:12-alpine
    ports:
    - 5432/tcp
    env:
      POSTGRES_USER: some_password_preferably_from_variable_group
```
You will then follow documentation on how to reference the post in the host.
