### ISSUE TITLE
.artifactignore doesn't do anything in react native android setup

### ISSUE THREAD

**Issue by karthikeyan-kandasamy** [MicrosoftDocs/vsts-docs#7537]
React native project .artifactignore file is seems like not working  
I have output as complete project 

My Git files

<img width="1015" alt="Screen Shot 2020-03-09 at 5 25 55 PM" src="https://user-images.githubusercontent.com/5136587/76210899-109c0e80-622b-11ea-933c-5b65e5f41072.png">

Artifact ignore
```
**/*
!android/app/build/outputs/apk/debug/**.*
!android/app/build/outputs/apk/release/**.*
!ios/**.*
```

YML

```
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Pipeline.Workspace)/'
    Contents: '**/.artifactignore'
    TargetFolder: '$(Pipeline.Workspace)'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifact: 'my-artifact'
```

output as complete project with node_modules and all the files in my git file size 504mb.

<img width="1135" alt="Screen Shot 2020-03-09 at 5 22 48 PM" src="https://user-images.githubusercontent.com/5136587/76210693-a4210f80-622a-11ea-8ea2-0fd5e543bdc2.png">

<img width="1135" alt="Screen Shot 2020-03-09 at 5 23 52 PM" src="https://user-images.githubusercontent.com/5136587/76210758-c581fb80-622a-11ea-916d-7bb2a7f43bc2.png">

**Comment by WilliamAntonRohm** [comment]
@karthikeyan-kandasamy -- Karthikeyan, thank you for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which docs.microsoft.com topic you’re referencing, or provide more context around your general task.

**Comment by karthikeyan-kandasamy** [comment]
@WilliamAntonRohm 
As we are running into problem when try to establish azure pipeline
on Android Task 
[https://docs.microsoft.com/en-us/azure/devops/pipelines/?view=azure-devops]()

**Comment by WilliamAntonRohm** [comment]
@karthikeyan-kandasamy -- Karthikeyan, thank you for clarifying.  You may find answers here:
- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. 

 
@KathrynEE -- Kathryn, please look into this issue.

**Comment by KathrynEE** [comment]
@WilliamAntonRohm - Please assign this to one of the Azure Pipelines writers. This isn't my content area. Also, the article referenced is a landing page and doesn't have any relevant content to address.

**Comment by WilliamAntonRohm** [comment]
@karthikeyan-kandasamy -- Karthikeyan, please specify which article you're following.

**Comment by karthikeyan-kandasamy** [comment]
Referring the official documentation
[https://docs.microsoft.com/en-us/azure/devops/artifacts/reference/artifactignore?view=azure-devops]()

But it seems little tricky to implement it. so I decide not to go with artifact ignore.

```
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(system.defaultWorkingDirectory)/android/app/build/outputs/apk'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
```

Above way, I can able to copy only the needed files

Anyway thanks for all your mentions.
I am closing this issue.
