### ISSUE TITLE
Pipeline resource variables available at compile time?

### ISSUE THREAD

**Issue by tylerwengerd-cr** [MicrosoftDocs/vsts-docs#7603]
Can you clarify if the pipeline resource variables (e.g. `variables.resources.pipeline.Alias.sourceBranch`) are available at compile time or only at run time? These variables act like they are only available at run time but I'd like to know if I'm missing something.

Background: I've been trying to use expressions to set a parameter based on the branch of the triggering pipeline resource but haven't been able to do so successfully in the way I was hoping.

This doesn't work (compile time var) - appEnvironment is not set:
```
  - template: template-repo/deploy.yml@templateRepo
    parameters:
      appName: ${{ variables.appName }}
      ${{ if eq(variables.resources.pipeline.appBuildPipeline.sourceBranch, 'refs/heads/dev') }}:
        appEnvironment: dev
```

This works (run time var):
```
      - job: MyJob
        condition: eq(variables['resources.pipeline.appBuildPipeline.sourceBranch'], 'refs/heads/dev')
        steps:
          - download: artifactToDownload
            artifact: artifact-dev
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee4ec9d0-e0d5-4fb4-7c3e-b84abfa290c2
* Version Independent ID: 3e2b80d9-30e5-0c48-49f0-4fcdfedf5eee
* Content: [Resources - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema)
* Content Source: [docs/pipelines/process/resources.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/resources.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
