### ISSUE TITLE
Missing required params from body

### ISSUE THREAD

**Issue by car5tenV** [MicrosoftDocs/vsts-docs#7699]
It seems like for iOS it is not working or the documentation lack information. If I want to use this task I always receive:
`##[error]"{\"error\":\"Error: Missing required params from body: build_version, unique_identifier, Service id: {ID}\"}"`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da6643ac-ea32-1761-a7e9-0f17a3c0b8ee
* Version Independent ID: 2442af0f-3f01-a91c-a98a-29c2f32d35b9
* Content: [App Center Distribute task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/app-center-distribute?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/app-center-distribute.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/app-center-distribute.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by WilliamAntonRohm** [comment]
@car5tenV -- thank you for your feedback.  Please provide more context around your general task.

Meanwhile, you may find answers here:
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by car5tenV** [comment]
@WilliamAntonRohm please find below the whole pipeline(Please note I replaced correct values with XYZ, which are project depending):

```
pool:
  name: Azure Pipelines
  demands: xcode

steps:
- task: InstallAppleCertificate@2
  displayName: 'Install an Apple certificate'
  inputs:
    certSecureFile: '6b7b57d2-29b9-469d-af11-bdb2d8cd6688'
    certPwd: '$(P12password)'

- task: InstallAppleProvisioningProfile@1
  displayName: 'Install an Apple provisioning profile'
  inputs:
    provProfileSecureFile: '3a7911af-33ff-4a07-af66-618c4242edf2'

- task: Xcode@5
  displayName: 'Xcode clean build'
  inputs:
    actions: 'clean build'
    xcWorkspacePath: '$(Parameters.xcWorkspacePath)'
    scheme: '$(Parameters.scheme)'
    xcodeVersion: '$(Parameters.xcodeVersion)'
    packageApp: true
    exportOptions: specify
    exportMethod: enterprise
    exportTeamId: XYZ

- task: AppCenterDistribute@3
  displayName: 'Deploy **/*.ipa to Visual Studio App Center'
  inputs:
    serverEndpoint: 'XYZ'
    appSlug: 'XYZ'
    appFile: '**/*.ipa'
    symbolsIncludeParentDirectory: false
    releaseNotesInput: Updates
    isSilent: false
```

**Comment by WilliamAntonRohm** [comment]
@car5tenV -- thank you for clarifying.  It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)  
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by xxycode** [comment]
@car5tenV  I‘ve got the same error. Have you solved this error?

**Comment by car5tenV** [comment]
@xxycode nope unfortunately I didnt' find a fix for this. I added a hook in app center to get triggered once a push to a branch is made

**Comment by daelhoser** [comment]
@xxycode , were you able to solve the issue? I too am facing this.

**Comment by xxycode** [comment]
I have solved this issue. My code signing was wrong. It works well after I fix my code signing.

**Comment by ShaunFS** [comment]
@xxycode Can you elaborate on what the fix was for your code signing?  I am running into this issue right now

**Comment by xxycode** [comment]
> @xxycode Can you elaborate on what the fix was for your code signing? I am running into this issue right now

When I copy provision file, I named "embedded.mobileprovision" to "embedded.provisionprofile", the right name is "embedded.mobileprovision".

**Comment by SalvoSwift21** [comment]
@xxycode , please can you help me I don't know what to watch anymore. I have the same error: `## [error] "{\" error \ ": \" Error: Missing required params from body: build_version, unique_identifier, Service id: {ID} \ "}"`

Here is my configuration by replacing the variables that depend on the project with xyz.
Thanks in advance

```
steps:
- task: InstallAppleCertificate@2
  displayName: 'Install an Apple certificate-Distribution'
  inputs:
    certSecureFile: 'Distribution.p12'
    certPwd: '$(P12password)'

steps:
- task: InstallAppleProvisioningProfile@1
  displayName: 'Install an Apple provisioning profile-Distribution-AdHoc'
  inputs:
    provProfileSecureFile: 'xyz.mobileprovision'


variables:
  Scheme-STUB: 'XYZ'

steps:
- task: Xcode@5
  displayName: 'Xcode archive-Release-STUB'
  inputs:
    actions: 'clean build'
    xcWorkspacePath: '$(Parameters.xcWorkspacePath)'
    scheme: '$(Scheme-STUB)'
    xcodeVersion: '$(Parameters.xcodeVersion)'
    packageApp: true
    exportOptions: specify
    exportMethod: 'ad-hoc'
    exportTeamId: xyz
    signingOption: manual
    signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
    provisioningProfileUuid: '$(APPLE_PROV_PROFILE_UUID)'
    args: 'CODE_SIGNING_ALLOWED=NO'

 steps:
- task: AppCenterDistribute@3
  displayName: 'Deploy **/*.ipa Stub to Visual Studio App Center'
  inputs:
    serverEndpoint: 'xyz'
    appSlug: 'xyz'
    appFile: '**/*.ipa'
    symbolsIncludeParentDirectory: false
    releaseNotesInput: 'Stub release'
    isMandatory: true
    distributionGroupId: 'xyz'
    isSilent: true


```
