### ISSUE TITLE
Helm .tgz files stored as application/octet-stream

### ISSUE THREAD

**Issue by Sakkyoku-Sha** [MicrosoftDocs/vsts-docs#7700]
As it stand now the .tgz files created using the "helm package" tool are being stored as 'application/octet-stream' which cannot be used by a subsequent 'helm install' command. Or else the following error is throw: 

`Error: file 'd:\a\r1\a\....\helm-charts\.....tgz' does not appear to be a gzipped archive; got 'application/octet-stream'`

The publish command in the pipelines yaml is as follows: 

```
      - task: PublishPipelineArtifact@1

        displayName: "Publish Pipeline Artifacts"
        inputs:

          artifactName: 'helm-charts'
          targetPath: `'$(Build.Repository.LocalPath)/tf-helm'`
```

where the 'tf-helm' folder is a folder containing the aforementioned .tgz file.

Is there any reason the .tgz files cannot be stored as a gzipped archive?
