### ISSUE TITLE
Runtime expression syntax for variables doesn't work for env parameter of the powershell task

### ISSUE THREAD

**Issue by johnbooze** [MicrosoftDocs/vsts-docs#7809]
```
variables:
  myVar: 'My Var'

steps:
  - powershell: |
      Write-Host 'My environment variables:'
      Get-ChildItem env:my* | Sort-Object Name | % { Write-Host ($_.Name + ': ' + $_.Value) }
    env:
      myEnvVarRunTime1: $(myVar)
      myEnvVarRunTime2: $[variables.myVar]
      myEnvVarCompileTime: ${{ variables.myVar }}
      myEnvVarUndefRunTime1: $(myUndefVar)
      myEnvVarUndefRunTime2: $[variables.myUndefVar]
      myEnvVarUndefCompileTime: ${{ variables.myUndefVar }}
```

Produces this output:
```
My environment variables:
myEnvVarCompileTime: My Var
myEnvVarRunTime1: My Var
myEnvVarRunTime2: $[variables.myVar]
myEnvVarUndefCompileTime: 
myEnvVarUndefRunTime1: $(myUndefVar)
myEnvVarUndefRunTime2: $[variables.myUndefVar]
MYVAR: My Var
```

Why doesn't this match the runtime expression variable behavior as described in the `Understand variable syntax` section?
1.  The variable isn't being expanded when it is defined
2.  The variable should be silently coalesced to the empty string when it isn't found

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c58a78-a567-e99a-9eb7-62dddd1b90b6
* Version Independent ID: 680a79bc-11de-39fc-43e3-e07dc762db18
* Content: [Expressions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#feedback)
* Content Source: [docs/pipelines/process/expressions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/expressions.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
