### ISSUE TITLE
String parameter can't be empty

### ISSUE THREAD

**Issue by waltervos** [MicrosoftDocs/vsts-docs#7865]
Considering this definition:
```
parameters:
- name: deployEnvironment
  displayName: Select your target environment.
  type: string
  default: Build_only
  values:
  - Build_only
  - TST
  - PP
  - P
- name: releaseName
  type: string
  default: ''

steps:
- script: echo "Hi!"
```
Why is releaseName a required parameter? I was hoping that by specifying `default: ''` I could allow it to be left empty. I couldn't find anything about this in the documentation here, but I'm pretty sure that's how it works for template parameters.

![image](https://user-images.githubusercontent.com/30372/78793243-6858a180-79b2-11ea-9881-86a7eccbcb2e.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 790318bb-8220-3241-4ca7-73351074492f
* Version Independent ID: db1da9db-3694-779b-17aa-1ed67fcecf86
* Content: [Use runtime and type-safe parameters - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/runtime-parameters?view=azure-devops#feedback)
* Content Source: [docs/pipelines/process/runtime-parameters.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/runtime-parameters.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
